/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S10BestInclassDocumentation() {
  return (
    <section className="Section theme--Dark accent--Teal Section--angleTop Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="StripeSet StripeSet--TopRight StripeSet--layoutIntersecting" data-js-controller="StripeSet" aria-hidden="true">
                <div className="Stripe Stripe--accentNone Stripe--variantSolid Stripe--insetNormal Stripe--widthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes"></div>
                <div className="Stripe Stripe--accentNone Stripe--variantSolid Stripe--insetNone Stripe--widthMedium" aria-hidden="true" data-js-target-list="StripeSet.stripes"></div>
                <div className="Stripe Stripe--accentNone Stripe--variantIntersection Stripe--insetNormal Stripe--widthFull Stripe--intersectionInsetNone Stripe--intersectionWidthMedium" aria-hidden="true" data-js-target-list="StripeSet.stripes">
                  <div className="Stripe__intersection" data-js-target="StripeSet.intersection"></div>
                </div>
              </div>
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2" data-columns-tablet="1">
                  <div className="RowLayout SideBySide__leftRowLayout">
                    <section className="Copy variant--Section">
                      <header className="Copy__header">
                        <h2 className="Copy__caption">
                          {"Best in-class documentation"}
                        </h2>
                        <h1 className="Copy__title">
                          {" Developer-centric to get started fast "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"A single integration and extensive documentation mean faster time to market, less maintenance of legacy systems, and more focus on customer and product experiences."}
                        </p>
                      </div>
                      <footer className="Copy__footer">
                        <section className="List" data-column-count="1">
                          <ul className="List__list">
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                <a className="Link" href="https://github.com/stripe-samples" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                  {"Sample code and examples"}
                                </a>
                                <br />
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                <a className="Link" href="https://stripe.com/docs/stripe-cli" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                  {"CLI for development and testing"}
                                </a>
                                <br />
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                <a className="Link" href="https://stripe.com/docs/upgrades" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                  {"Versioned API changes"}
                                </a>
                                <br />
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                <a className="Link" href="https://stripe.com/docs/webhooks" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                  {"Webhooks"}
                                </a>
                                <br />
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                <a className="Link" href="https://stripe.com/docs/testing" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                  {"Test environment"}
                                </a>
                                <br />
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                <a className="Link" href="https://stripe.com/docs/payments/charges-api#storing-information-in-metadata" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                  {"Metadata support"}
                                </a>
                                <br />
                              </span>
                            </li>
                          </ul>
                        </section>
                        <a className="CtaButton variant--Button CtaButton--arrow" href="https://docs.stripe.com/payments" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="payments_developers_explore_the_docs">
                          {"Explore the docs"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                      </footer>
                    </section>
                  </div>
                  <div className="RowLayout SideBySide__rightRowLayout">
                    <figure className="DeveloperCentricCodeEditor" data-js-controller="DeveloperCentricCodeEditor">
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" const stripe = require('stripe')('sk_test_••••••••••••••••••••••••'); // Create a payment intent to start a purchase flow. let paymentIntent = await stripe.paymentIntents.create({ amount: 2000, currency: 'usd', description: 'My first payment', }); // Complete the payment using a test card. await stripe.paymentIntents.confirm(paymentIntent.id, { payment_method: 'pm_card_mastercard', }); "}
                      </div>
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" Stripe.api_key = 'sk_test_••••••••••••••••••••••••' # Create a payment intent to start a purchase flow. payment_intent = Stripe::PaymentIntent.create({ amount: 2000, currency: 'usd', description: 'My first payment', }) # Complete the payment using a test card. Stripe::PaymentIntent.confirm(payment_intent.id, { payment_method: 'pm_card_mastercard', }) "}
                      </div>
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" stripe.api_key = 'sk_test_••••••••••••••••••••••••' # Create a payment intent to start a purchase flow. payment_intent = stripe.PaymentIntent.create( amount=2000, currency='usd', description='My first payment', ) # Complete the payment using a test card. stripe.PaymentIntent.confirm( payment_intent.id, payment_method='pm_card_mastercard', ) "}
                      </div>
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" stripe.Key = \"sk_test_••••••••••••••••••••••••\" // Create a payment intent to start a purchase flow. params := &stripe.PaymentIntentParams{ Amount: stripe.Int64(2000), Currency: stripe.String(string(stripe.CurrencyUSD)), Description: stripe.String(\"My first payment\"), } pi, _ := paymentintent.New(params) // Complete the payment using a test card. confirmParams := &stripe.PaymentIntentConfirmParams{ PaymentMethod: stripe.String(\"pm_card_mastercard\"), } paymentintent.Confirm(pi.ID, confirmParams) "}
                      </div>
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" $stripe = new \\Stripe\\StripeClient('sk_test_••••••••••••••••••••••••'); // Create a payment intent to start a purchase flow. $payment_intent = $stripe->paymentIntents->create([ 'amount' => 2000, 'currency' => 'usd', 'description' => 'My first payment', ]); // Complete the payment using a test card. $payment_intent->confirm([ 'payment_method' => 'pm_card_mastercard', ]); "}
                      </div>
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" Stripe.apiKey = \"sk_test_••••••••••••••••••••••••\"; // Create a payment intent to start a purchase flow. PaymentIntentCreateParams params = PaymentIntentCreateParams.builder() .setAmount(2000L) .setCurrency(\"usd\") .setDescription(\"My first payment\") .build(); PaymentIntent paymentIntent = PaymentIntent.create(params); // Complete the payment using a test card. PaymentIntentConfirmParams confirmParams = PaymentIntentConfirmParams.builder() .setPaymentMethod(\"pm_card_mastercard\") .build(); paymentIntent.confirm(confirmParams); "}
                      </div>
                      <div style={{ display: "none" }} aria-hidden="true" data-js-target-list="DeveloperCentricCodeEditor.snippets">
                        {" StripeConfiguration.ApiKey = \"sk_test_••••••••••••••••••••••••\"; // Create a payment intent to start a purchase flow. var options = new PaymentIntentCreateOptions { Amount = 2000, Currency = \"usd\", Description = \"My first payment\", }; var service = new PaymentIntentService(); var paymentIntent = service.Create(options); // Complete the payment using a test card. var confirmOptions = new PaymentIntentConfirmOptions { PaymentMethod = \"pm_card_mastercard\", }; service.Confirm(paymentIntent.Id, confirmOptions); "}
                      </div>
                      <div className="Card Card--border">
                        <div className="DeveloperCentricCodeEditor__languages">
                          <nav className="SegmentedControl" data-js-controller="SegmentedControl" data-selection-mode="single">
                            <div className="SegmentedControl__container">
                              <div className="HorizontalOverflowContainer" data-js-controller="HorizontalOverflowContainer" style={{ "--horizontalOverflowSpacing": "16px" }}>
                                <div className="HorizontalOverflowContainer__track" data-js-target="HorizontalOverflowContainer.track">
                                  <div className="SegmentedControl__backContainer" data-js-target="SegmentedControl.backButtonContainer" aria-hidden="true"></div>
                                  <div className="HorizontalOverflowContainer__items">
                                    <div className="SegmentedControl__buttons" data-js-target="SegmentedControl.items">
                                      <button className="SegmentedControlButton SegmentedControlButton--active" data-js-target-list="SegmentedControl.buttons">
                                        {" Node.js "}
                                      </button>
                                      {" "}
                                      <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                        {" Ruby "}
                                      </button>
                                      {" "}
                                      <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                        {" Python "}
                                      </button>
                                      {" "}
                                      <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                        {" Go "}
                                      </button>
                                      {" "}
                                      <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                        {" PHP "}
                                      </button>
                                      {" "}
                                      <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                        {" Java "}
                                      </button>
                                      {" "}
                                      <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                        {" .NET "}
                                      </button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </nav>
                        </div>
                        <div className="CodeEditor CodeEditor--focused" aria-hidden="true" data-js-controller="CodeEditor" data-js-language-mode="javascript">
                          <div data-js-target="CodeEditor.finalCode" style={{ display: "none" }}>
                            {"const stripe = require('stripe')('sk_test_••••••••••••••••••••••••'); // Create a payment intent to start a purchase flow. let paymentIntent = await stripe.paymentIntents.create({ amount: 2000, currency: 'usd', description: 'My first payment', }); // Complete the payment using a test card. await stripe.paymentIntents.confirm(paymentIntent.id, { payment_method: 'pm_card_mastercard', });"}
                          </div>
                          <code className="CodeEditor__scrollContainer" data-js-target="CodeEditor.scrollContainer">
                            <pre className="CodeSyntax CodeEditor__editor">
                              <div className="CodeEditorLineNumbers" data-js-controller="CodeEditorLineNumbers">
                                {"\n  "}
                                <div className="CodeEditorLineNumbers__lineNumbersContainer" data-js-target="CodeEditorLineNumbers.lineNumbersContainer">
                                  {"\n    "}
                                  <span className="CodeEditorLineNumbers__number" data-js-target="CodeEditorLineNumbers.firstLineNumber">
                                    {"~"}
                                  </span>
                                  {"\n  "}
                                </div>
                                {"\n\n  \n"}
                              </div>
                              {"\n        \n        "}
                              <span className="CodeEditorAsciiLoader"></span>
                              {"\n        \n        "}
                              <span className="CodeEditor__typingArea">
                                <span data-js-target="CodeEditor.editor"></span>
                                {"\n          \n        "}
                              </span>
                            </pre>
                          </code>
                        </div>
                        <footer className="CodeEditor__footer">
                          <section className="Copy variant--Detail">
                            <header className="Copy__header">
                              <h1 className="Copy__title">
                                {" Comprehensive libraries "}
                              </h1>
                            </header>
                            <div className="Copy__body">
                              {" Stripe libraries are available for all of the most commonly used languages and frameworks. "}
                            </div>
                            <footer className="Copy__footer">
                              <div className="CtaGroup CtaGroup--inline Copy__ctaGroup">
                                <a className="CtaButton variant--Link CtaButton--arrow" href="https://docs.stripe.com/libraries" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="developer_centric_to__comprehensive_libraries__learn_more">
                                  {"Learn more"}
                                  <span className="nobr">
                                    <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                      <g fillRule="evenodd">
                                        <path className="HoverArrow__linePath" d="M0 5h7" />
                                        <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                      </g>
                                    </svg>
                                  </span>
                                </a>
                              </div>
                            </footer>
                          </section>
                        </footer>
                      </div>
                    </figure>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
