/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S05ForDevelopers() {
  return (
    <section className="Section theme--Dark accent--Yellow Section--angleBoth Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2" data-columns-tablet="1">
                  <div className="RowLayout SideBySide__leftRowLayout">
                    <section className="Copy variant--Section">
                      <header className="Copy__header">
                        <h2 className="Copy__caption">
                          {"For developers"}
                        </h2>
                        <h1 className="Copy__title">
                          {" APIs for automated invoicing "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Use Stripe’s APIs to create, send, and reconcile invoices. Automate workflows that scale with your business and integrate easily with existing systems."}
                        </p>
                      </div>
                      <footer className="Copy__footer">
                        <section className="List" data-column-count="1">
                          <ul className="List__list">
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Automate invoice delivery and reminders"}
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Store payment details for recurring invoices"}
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zm3.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" fill="var(--accentColor)" fillRule="evenodd" />
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"For platforms, enable your users to send invoices"}
                              </span>
                            </li>
                          </ul>
                        </section>
                        <a className="CtaButton variant--Button CtaButton--arrow" href="https://docs.stripe.com/api/invoices" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="apis_for_programmatic__explore_the_docs">
                          {"Explore the docs"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                      </footer>
                    </section>
                  </div>
                  <div className="RowLayout SideBySide__rightRowLayout">
                    <figure className="SnippetsCodeEditor" data-js-controller="SnippetsCodeEditor">
                      <div data-js-target-list="SnippetsCodeEditor.snippets" aria-hidden="true" style={{ display: "none" }}>
                        {"const stripe = require('stripe')('sk_test_abc123'); await stripe.invoiceItems.create({ customer: 'cus_IFwlG2M3UyNbOG', amount: 1000, currency: 'usd', }); const invoice = await stripe.invoices.create({ customer: 'cus_IFwlG2M3UyNbOG', collection_method: 'send_invoice', days_until_due: 30, }); await stripe.invoices.sendInvoice(invoice.id);"}
                      </div>
                      <div className="Card Card--border">
                        <div className="CodeEditor CodeEditor--focused CodeEditor--autosize" aria-hidden="true" data-js-controller="CodeEditor" data-js-language-mode="javascript">
                          <div data-js-target="CodeEditor.finalCode" style={{ display: "none" }}>
                            {"const stripe = require('stripe')('sk_test_abc123'); await stripe.invoiceItems.create({ customer: 'cus_IFwlG2M3UyNbOG', amount: 1000, currency: 'usd', }); const invoice = await stripe.invoices.create({ customer: 'cus_IFwlG2M3UyNbOG', collection_method: 'send_invoice', days_until_due: 30, }); await stripe.invoices.sendInvoice(invoice.id);"}
                          </div>
                          <code className="CodeEditor__scrollContainer" data-js-target="CodeEditor.scrollContainer">
                            <pre className="CodeSyntax CodeEditor__editor">
                              <div className="CodeEditorLineNumbers" data-js-controller="CodeEditorLineNumbers">
                                {"\n  "}
                                <div className="CodeEditorLineNumbers__lineNumbersContainer" data-js-target="CodeEditorLineNumbers.lineNumbersContainer">
                                  {"\n    "}
                                  <span className="CodeEditorLineNumbers__number" data-js-target="CodeEditorLineNumbers.firstLineNumber">
                                    {"~"}
                                  </span>
                                  {"\n  "}
                                </div>
                                {"\n\n  \n"}
                              </div>
                              {"\n        \n        "}
                              <span className="CodeEditorAsciiLoader"></span>
                              {"\n        \n        "}
                              <span className="CodeEditor__typingArea">
                                <span data-js-target="CodeEditor.editor"></span>
                                {"\n          \n        "}
                              </span>
                            </pre>
                          </code>
                        </div>
                        <footer className="CodeEditor__footer">
                          <section className="Copy variant--Detail">
                            <header className="Copy__header">
                              <h1 className="Copy__title">
                                {" Comprehensive libraries "}
                              </h1>
                            </header>
                            <div className="Copy__body">
                              <p>
                                {"Create an invoice and automatically email it to your customers using a language of your choice. Stripe libraries are available for all of the most commonly used languages and frameworks."}
                              </p>
                            </div>
                            <footer className="Copy__footer">
                              <a className="CtaButton variant--Link CtaButton--arrow" href="https://docs.stripe.com/libraries" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="apis_for_programmatic__comprehensive_libraries__learn_more">
                                {"Learn more"}
                                <span className="nobr">
                                  <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                    <g fillRule="evenodd">
                                      <path className="HoverArrow__linePath" d="M0 5h7" />
                                      <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                    </g>
                                  </svg>
                                </span>
                              </a>
                            </footer>
                          </section>
                        </footer>
                      </div>
                    </figure>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
