/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S00ManagedPaymentsHero() {
  return (
    <section className="hds-color-mode managed-payments-hero section section--white hds-mode--light">
      <div className="section-container product-hero-subnav">
        <nav className="hero-static-subnav hero-subnav" aria-label="Managed Payments sub navigation" aria-hidden="false">
          <span className="hero-subnav__title">
            <span className="product-hero-subnav__title">
              <span className="hds-text hds-text--lg hds-text--emphasized">
                <a className="hds-link hero-subnav__title-link" href="/managed-payments" data-analytics-label="hero__top_nav__managed_payments">
                  {"Managed Payments"}
                </a>
              </span>
            </span>
          </span>
          <div className="hero-subnav__content">
            <div className="horizontal-scrollable-container hero-subnav-page-nav">
              <div className="horizontal-scrollable-container__inner">
                <ul className="hero-subnav-items">
                  <li className="hero-subnav-item">
                    <span className="hds-text hds-text--sm">
                      <a className="hds-link hero-subnav-item__link hero-subnav-item__link--active" href="/managed-payments" data-analytics-label="hero__top_nav__overview" aria-current="page">
                        {"Overview"}
                      </a>
                    </span>
                  </li>
                  <li className="hero-subnav-item">
                    <span className="hds-text hds-text--sm">
                      <a className="hds-link hero-subnav-item__link" href="https://stripe.com/pricing#managed-payments" data-analytics-label="hero__top_nav__pricing">
                        {"Pricing"}
                      </a>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <div className="hero-subnav-secondary-nav">
              <ul className="hero-subnav-items">
                <li className="hero-subnav-item">
                  <span className="hds-text hds-text--sm">
                    <a className="hds-link hero-subnav-item__link" href="https://docs.stripe.com/payments/managed-payments" data-analytics-label="hero__top_nav__docs">
                      {"Docs"}
                      <span className="hero-subnav-item__icon-end">
                        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" className="icon" aria-hidden="true">
                          <path fill="currentColor" d="M3.87744 2.37744H2.62646c-.13783.0002-.2499.11214-.25.25v6.74512c0 .13794.1121.2498.25.25h6.74708c.13797-.00011.25-.112.25-.25V8.11475h1.49996v1.25781c0 .96644-.7836 1.74984-1.74996 1.75004H2.62646c-.96632-.0002-1.749995-.7837-1.749995-1.75004V2.62744C.876564 1.66115 1.6602.877642 2.62646.877441h1.25098zm7.24416 4.0127H9.62158V3.47021l-3.90234 3.9043c-.29272.29231-.7677.29215-1.06055 0-.29284-.29278-.29268-.76861 0-1.06152l3.92774-3.92871h-2.9795V.884277h5.51467z" />
                        </svg>
                      </span>
                    </a>
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <nav className="hero-mobile-static-subnav hero-subnav" aria-label="Managed Payments sub navigation" aria-hidden="false">
          <span className="product-hero-subnav__title">
            <span className="hds-text hds-text--lg hds-text--emphasized">
              <a className="hds-link hero-subnav__title-link" href="/managed-payments" data-analytics-label="hero__top_nav__managed_payments">
                {"Managed Payments"}
              </a>
            </span>
          </span>
          <button type="button" className="hds-ui-button hero-subnav__mobile-toggle-button hds-ui-button--quiet hds-ui-button--small" aria-label="Toggle navigation menu" aria-expanded="false">
            <svg width="9" height="9" viewBox="0 0 9 9" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" className="cross-toggle-icon">
              <path className="cross-toggle-icon__vertical" d="M0 3.656h9V4.97H0z" />
              <path className="cross-toggle-icon__horizontal" d="M4.972 0v9H3.66V0z" />
            </svg>
          </button>
          <div className="hero-mobile-static-subnav__content-container" inert>
            <div className="hero-mobile-static-subnav__content-clip">
              <div className="hero-mobile-static-subnav__content">
                <div className="horizontal-scrollable-container hero-subnav-page-nav">
                  <div className="horizontal-scrollable-container__inner">
                    <ul className="hero-subnav-items">
                      <li className="hero-subnav-item">
                        <span className="hds-text hds-text--sm">
                          <a className="hds-link hero-subnav-item__link hero-subnav-item__link--active" href="/managed-payments" data-analytics-label="hero__top_nav__overview" aria-current="page">
                            {"Overview"}
                          </a>
                        </span>
                      </li>
                      <li className="hero-subnav-item">
                        <span className="hds-text hds-text--sm">
                          <a className="hds-link hero-subnav-item__link" href="https://stripe.com/pricing#managed-payments" data-analytics-label="hero__top_nav__pricing">
                            {"Pricing"}
                          </a>
                        </span>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="hero-subnav-secondary-nav">
                  <ul className="hero-subnav-items">
                    <li className="hero-subnav-item">
                      <span className="hds-text hds-text--sm">
                        <a className="hds-link hero-subnav-item__link" href="https://docs.stripe.com/payments/managed-payments" data-analytics-label="hero__top_nav__docs">
                          {"Docs"}
                          <span className="hero-subnav-item__icon-end">
                            <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" className="icon" aria-hidden="true">
                              <path fill="currentColor" d="M3.87744 2.37744H2.62646c-.13783.0002-.2499.11214-.25.25v6.74512c0 .13794.1121.2498.25.25h6.74708c.13797-.00011.25-.112.25-.25V8.11475h1.49996v1.25781c0 .96644-.7836 1.74984-1.74996 1.75004H2.62646c-.96632-.0002-1.749995-.7837-1.749995-1.75004V2.62744C.876564 1.66115 1.6602.877642 2.62646.877441h1.25098zm7.24416 4.0127H9.62158V3.47021l-3.90234 3.9043c-.29272.29231-.7677.29215-1.06055 0-.29284-.29278-.29268-.76861 0-1.06152l3.92774-3.92871h-2.9795V.884277h5.51467z" />
                            </svg>
                          </span>
                        </a>
                      </span>
                    </li>
                  </ul>
                  <div className="hds-button-group">
                    <a className="hds-button hds-button--primary hds-button--compact" href="https://dashboard.stripe.com/register/managed_payments" data-analytics-label="hero__sticky_sub_nav__start_now">
                      {"Start now"}
                      <span className="hds-nowrap-svg">
                        <svg className="hds-icon hds-icon-hover-arrow" width="5" height="8" fill="none" viewBox="0 0.5 5 8">
                          <defs>
                            <clipPath id=":R3le8qr6l6:">
                              <rect x="0" y="0" width="12" height="9" />
                            </clipPath>
                          </defs>
                          <g clipPath="url(#:R3le8qr6l6:)">
                            <g className="arrow-group">
                              <rect className="shaft" x="-10" y="3.375" width="13" height="1.75" fill="currentColor" />
                              <path d="M4.84766 3.63379L5.45898 4.25L4.84766 4.86621L1.24219 8.49902L0 7.2666L2.99316 4.24902L0 1.23242L1.24219 0L4.84766 3.63379Z" fill="currentColor" />
                            </g>
                          </g>
                        </svg>
                      </span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </div>
      <div className="section-container managed-payments-hero__container">
        <div className="section-row section-row-gap section-row-align" style={{ "--section-row-gap-mb": "var(--hds-space-core-400)", "--section-row-align-mb": "center" }}>
          <div className="section-row managed-payments-hero__wrapper section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-200)", "--section-row-gap-tb": "var(--hds-space-core-150)", "--section-row-gap-dt": "var(--hds-space-core-150)" }}>
            <h1 className="hds-heading managed-payments-hero__heading hds-heading--md">
              {"Sell globally without the complexity"}
            </h1>
            <p className="hds-text managed-payments-hero__description hds-text--xl hds-text--subdued">
              {"Focus on growth while Stripe Managed Payments handles tax, fraud, disputes, and more as your merchant of record."}
            </p>
          </div>
          <div className="hds-button-group">
            <a className="hds-button hds-button--primary" href="https://dashboard.stripe.com/register/managed_payments" data-analytics-label="hero__start_now">
              {"Start now"}
              <span className="hds-nowrap-svg">
                <svg className="hds-icon hds-icon-hover-arrow" width="5" height="8" fill="none" viewBox="0 0.5 5 8">
                  <defs>
                    <clipPath id=":Rspgqr6l6:">
                      <rect x="0" y="0" width="12" height="9" />
                    </clipPath>
                  </defs>
                  <g clipPath="url(#:Rspgqr6l6:)">
                    <g className="arrow-group">
                      <rect className="shaft" x="-10" y="3.375" width="13" height="1.75" fill="currentColor" />
                      <path d="M4.84766 3.63379L5.45898 4.25L4.84766 4.86621L1.24219 8.49902L0 7.2666L2.99316 4.24902L0 1.23242L1.24219 0L4.84766 3.63379Z" fill="currentColor" />
                    </g>
                  </g>
                </svg>
              </span>
            </a>
            <a className="hds-button hds-button--secondary" href="https://stripe.com/contact/sales" data-analytics-label="hero__contact_sales">
              {"Contact sales"}
            </a>
          </div>
        </div>
        <div className="managed-payments-hero__anim-container">
          <div className="managed-payments-hero__ui-anim-container">
            <div className="dom-graphic dom-graphic--variant-default" style={{ "--graphic-source-width": "555px", "--graphic-source-height": "628px", "--graphic-aspect-ratio": "555 / 628", "--graphic-scale": "1", "--graphic-max-width": "555px" }} data-status="measuring" aria-hidden="true">
              <div className="dom-graphic__content dom-graphic__content--horizontal-scale-left">
                <div className="managed-payments-hero__ui-anim-overlay">
                  <div className="managed-payments-hero__ui-anim-overlay-icon">
                    <div className="charm-icon">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                        <path fill="url(#globe-gradient-id-:Rjagqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M12 2c5.5228 0 10 4.47715 10 10 0 5.5228-4.4772 10-10 10-5.52285 0-10-4.4772-10-10C2 6.47715 6.47715 2 12 2M8.01807 12.75c.09971 2.2449.63979 4.2028 1.40722 5.5981C10.3068 19.9508 11.2811 20.5 12 20.5s1.6932-.5492 2.5747-2.1519c.7674-1.3953 1.3075-3.3532 1.4072-5.5981zm-4.48487 0c.27413 3.1354 2.25031 5.7823 4.99951 7.0122-1.14021-1.6859-1.90033-4.1854-2.01562-7.0122zm13.9497 0c-.1153 2.8269-.8758 5.3263-2.0161 7.0122 2.7494-1.2298 4.7259-3.8766 5-7.0122zM8.53271 4.2373C5.78341 5.46718 3.80734 8.1145 3.5332 11.25h2.98389c.1153-2.82697.87529-5.32681 2.01562-7.0127M12 3.5c-.7189 0-1.6932.54918-2.57471 2.15186C8.65786 7.0472 8.11778 9.00507 8.01807 11.25h7.96383c-.0997-2.24493-.6398-4.2028-1.4072-5.59814C13.6932 4.04918 12.7189 3.5 12 3.5m3.4668.7373c1.1404 1.68589 1.9008 4.1856 2.0161 7.0127h2.9839c-.2742-3.13566-2.2505-5.7829-5-7.0127" />
                        <defs>
                          <linearGradient id="globe-gradient-id-:Rjagqr6l6:" x1="15.63" x2="8.28648" y1="2" y2="21.9999" gradientUnits="userSpaceOnUse">
                            <stop stopColor="var(--icon-gradient-start)" />
                            <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                            <stop offset="1" stopColor="var(--icon-gradient-end)" />
                          </linearGradient>
                        </defs>
                      </svg>
                    </div>
                  </div>
                  <div className="managed-payments-hero__ui-anim-overlay-content">
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-heading hds-text--lg">
                      {"Global payment optimization"}
                    </p>
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-description hds-text--md hds-text--subdued">
                      {"Improve international payment performance"}
                    </p>
                  </div>
                </div>
                <div className="managed-payments-hero__ui-anim-overlay">
                  <div className="managed-payments-hero__ui-anim-overlay-icon">
                    <div className="charm-icon">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                        <path fill="url(#money-stack-gradient-id-:Rlagqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M13.5 12.5c1.6569 0 3 1.2727 3 3.5l-.0039.2061C16.4157 18.3056 15.1051 19.5 13.5 19.5l-.1543-.0039c-1.534-.0743-2.764-1.2582-2.8418-3.29L10.5 16c0-2.2273 1.3431-3.5 3-3.5m0 1.5c-.4296 0-.7686.1572-1.0117.4243C12.2405 14.6967 12 15.1892 12 16s.2405 1.3033.4883 1.5757c.2431.2671.5821.4243 1.0117.4243s.7686-.1572 1.0117-.4243C14.7595 17.3033 15 16.8108 15 16s-.2405-1.3033-.4883-1.5757C14.2686 14.1572 13.9296 14 13.5 14" />
                        <path fill="url(#money-stack-gradient-id-:Rlagqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M16.1543 2.00391c1.534.07771 2.7641 1.30775 2.8418 2.84179L19 5v3.5h-1.5V7h-14v5c0 .8284.67157 1.5 1.5 1.5V10h17v12H5v-7c-1.65685 0-3-1.3431-3-3V5l.00391-.1543c.07772-1.53404 1.30775-2.76408 2.84179-2.84179L5 2h11zM6.5 20.5h14v-9h-14zM5 3.5c-.82843 0-1.5.67157-1.5 1.5v.5h14V5c0-.82843-.6716-1.5-1.5-1.5z" />
                        <defs>
                          <linearGradient id="money-stack-gradient-id-:Rlagqr6l6:" x1="15.63" x2="8.28648" y1="2" y2="21.9999" gradientUnits="userSpaceOnUse">
                            <stop stopColor="var(--icon-gradient-start)" />
                            <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                            <stop offset="1" stopColor="var(--icon-gradient-end)" />
                          </linearGradient>
                        </defs>
                      </svg>
                    </div>
                  </div>
                  <div className="managed-payments-hero__ui-anim-overlay-content">
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-heading hds-text--lg">
                      {"Tax collection and remittance"}
                    </p>
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-description hds-text--md hds-text--subdued">
                      {"Automated in 80+ countries"}
                    </p>
                  </div>
                </div>
                <div className="managed-payments-hero__ui-anim-overlay">
                  <div className="managed-payments-hero__ui-anim-overlay-icon">
                    <div className="charm-icon">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                        <path fill="url(#shield-gradient-id-:Rnagqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M21 9.44629C21 15.5177 16.6024 19.468 11.999 22.5 7.39625 19.4674 3 15.5176 3 9.44629V3h18zm-16.5 0c0 4.62111 2.92882 7.93331 6.75 10.71291V4.5H4.5zm8.25 10.71191c3.8211-2.779 6.75-6.0915 6.75-10.71191V4.5h-6.75z" />
                        <defs>
                          <linearGradient id="shield-gradient-id-:Rnagqr6l6:" x1="15.267" x2="7.66716" y1="3" y2="22.1058" gradientUnits="userSpaceOnUse">
                            <stop stopColor="var(--icon-gradient-start)" />
                            <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                            <stop offset="1" stopColor="var(--icon-gradient-end)" />
                          </linearGradient>
                        </defs>
                      </svg>
                    </div>
                  </div>
                  <div className="managed-payments-hero__ui-anim-overlay-content">
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-heading hds-text--lg">
                      {"Fraud and risk protection"}
                    </p>
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-description hds-text--md hds-text--subdued">
                      {"38% average reduction in fraud"}
                    </p>
                  </div>
                </div>
                <div className="managed-payments-hero__ui-anim-overlay">
                  <div className="managed-payments-hero__ui-anim-overlay-icon">
                    <div className="charm-icon">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                        <path fill="url(#document-check-gradient-id-:Rpagqr6l6:)" d="M20 13h-1.5V4.5h-13v13C5.5 18.8807 6.61929 20 8 20h4v1.5H8c-2.20914 0-4-1.7909-4-4V3h16z" />
                        <path fill="url(#document-check-gradient-id-:Rpagqr6l6:)" d="M22.6743 14.4414 17.5439 21.5H15.936l-2.9809-4.1006 1.2134-.8818 2.5717 3.5371 4.7207-6.4951z" />
                        <path fill="url(#document-check-gradient-id-:Rpagqr6l6:)" d="M14 13H8v-1.5h6z" />
                        <path fill="url(#document-check-gradient-id-:Rpagqr6l6:)" d="M16 9H8V7.5h8z" />
                        <defs>
                          <linearGradient id="document-check-gradient-id-:Rpagqr6l6:" x1="16.7265" x2="9.98231" y1="3" y2="21.5408" gradientUnits="userSpaceOnUse">
                            <stop stopColor="var(--icon-gradient-start)" />
                            <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                            <stop offset="1" stopColor="var(--icon-gradient-end)" />
                          </linearGradient>
                        </defs>
                      </svg>
                    </div>
                  </div>
                  <div className="managed-payments-hero__ui-anim-overlay-content">
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-heading hds-text--lg">
                      {"Dispute handling"}
                    </p>
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-description hds-text--md hds-text--subdued">
                      {"Disputes handled on your behalf"}
                    </p>
                  </div>
                </div>
                <div className="managed-payments-hero__ui-anim-overlay">
                  <div className="managed-payments-hero__ui-anim-overlay-icon">
                    <div className="charm-icon">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                        <path fill="url(#person-stack-gradient-id-:Rragqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M9.48682 13c1.88938 0 3.52118 1.3221 3.91308 3.1704l.2817 1.3296h7.4668l-.2158-1.0186c-.2449-1.1551-1.2649-1.9814-2.4458-1.9814h-3.9565l-1.064-1.5h5.0205c1.8894 0 3.5212 1.3221 3.9131 3.1704L23 19H1l.6001-2.8296c.37964-1.7904 1.92262-3.0871 3.73633-3.1665L5.51318 13zm-3.97364 1.5c-1.18084 0-2.20085.8263-2.4458 1.9814L2.85156 17.5h9.29684l-.2158-1.0186C11.6877 15.3263 10.6677 14.5 9.48682 14.5z" />
                        <path fill="url(#person-stack-gradient-id-:Rragqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M7.5 4.5C9.433 4.5 11 6.067 11 8s-1.567 3.5-3.5 3.5S4 9.933 4 8s1.567-3.5 3.5-3.5m0 1.5c-1.10457 0-2 .89543-2 2s.89543 2 2 2 2-.89543 2-2-.89543-2-2-2" />
                        <path fill="url(#person-stack-gradient-id-:Rragqr6l6:)" fillRule="evenodd" clipRule="evenodd" d="M16.5 4.5C18.433 4.5 20 6.067 20 8s-1.567 3.5-3.5 3.5S13 9.933 13 8s1.567-3.5 3.5-3.5m0 1.5c-1.1046 0-2 .89543-2 2s.8954 2 2 2 2-.89543 2-2-.8954-2-2-2" />
                        <defs>
                          <linearGradient id="person-stack-gradient-id-:Rragqr6l6:" x1="15.993" x2="12.2312" y1="4.5" y2="20.0444" gradientUnits="userSpaceOnUse">
                            <stop stopColor="var(--icon-gradient-start)" />
                            <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                            <stop offset="1" stopColor="var(--icon-gradient-end)" />
                          </linearGradient>
                        </defs>
                      </svg>
                    </div>
                  </div>
                  <div className="managed-payments-hero__ui-anim-overlay-content">
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-heading hds-text--lg">
                      {"Customer support"}
                    </p>
                    <p className="hds-text managed-payments-hero__ui-anim-overlay-description hds-text--md hds-text--subdued">
                      {"24/7 multilingual support"}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="section-background section-background--border-top" aria-hidden="true"></div>
    </section>
  );
}
