/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S05BuiltForYourGlobal() {
  return (
    <section className="hds-color-mode section hds-mode--light">
      <div className="section-container">
        <div className="section-row anchor-offset--nav section-row-gap" id="optimize" style={{ "--section-row-gap-mb": "var(--hds-space-core-400)", "--section-row-gap-tb": "var(--hds-space-core-600)", "--section-row-gap-dt": "var(--hds-space-core-800)" }}>
          <div className="section-title section-title--span-9">
            <h2>
              <span className="hds-heading hds-heading--lg hds-heading--inline">
                {"Built for your global growth strategy."}
              </span>
              <span className="hds-heading hds-heading--lg hds-heading--subdued hds-heading--inline">
                {"Scale quickly with the flexibility and control you need for every stage of expansion."}
              </span>
            </h2>
          </div>
          <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-600)", "--section-row-gap-tb": "var(--hds-space-core-1000)", "--section-row-gap-dt": "var(--hds-space-core-1600)" }}>
            <div className="columns columns-row-gap" style={{ "--columns-count-dt": "3", "--columns-row-gap-mb": "var(--hds-space-core-400)" }}>
              <div className="feature-detail">
                <div className="charm-icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                    <path fill="url(#fast-forward-gradient-id-:R9jar6l6:)" fillRule="evenodd" clipRule="evenodd" d="M15.75 11.2529V12.7461L4 21L4 3L15.75 11.2529ZM5.5 18.1133L14.2021 12L5.5 5.8877L5.5 18.1133Z" />
                    <path fill="url(#fast-forward-gradient-id-:R9jar6l6:)" d="M22 11.4287V12.5703L10 21V16.7852L11.5 15.7314V18.1133L20.2021 12H20.2051L10 4.83105V3L22 11.4287Z" />
                    <defs>
                      <linearGradient id="fast-forward-gradient-id-:R9jar6l6:" x1="16.267" y1="21" x2="9.65783" y2="3.00008" gradientUnits="userSpaceOnUse">
                        <stop stopColor="var(--icon-gradient-start)" />
                        <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                        <stop offset="1" stopColor="var(--icon-gradient-end)" />
                      </linearGradient>
                    </defs>
                  </svg>
                </div>
                <div className="feature-detail__content feature-detail__content--stacked">
                  <h4 className="hds-text hds-text--md hds-text--emphasized">
                    {"Launch globally from day one"}
                  </h4>
                  <p className="hds-text hds-text--md hds-text--soft">
                    {"Offer software subscriptions, digital content, or virtual goods to customers in supported countries without establishing local entities or navigating tax regulations."}
                  </p>
                </div>
              </div>
              <div className="feature-detail">
                <div className="charm-icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                    <path fill="url(#clipboard-gradient-id-:Rajar6l6:)" d="M16 16L8 16L8 14.5L16 14.5V16Z" />
                    <path fill="url(#clipboard-gradient-id-:Rajar6l6:)" d="M16 12L8 12V10.5L16 10.5V12Z" />
                    <path fill="url(#clipboard-gradient-id-:Rajar6l6:)" fillRule="evenodd" clipRule="evenodd" d="M13.2944 1.5C14.3969 1.5 15.3715 2.09783 15.8931 3L20.5 3L20.5 19C20.5 20.6051 19.2394 21.9158 17.6543 21.9961L17.5 22L6.5 22L6.3457 21.9961C4.76055 21.9158 3.5 20.6051 3.5 19L3.5 3L8.10742 3C8.62879 2.09775 9.6035 1.50003 10.7061 1.5L13.2944 1.5ZM5 4.5L5 19C5 19.8284 5.67157 20.5 6.5 20.5L17.5 20.5C18.3284 20.5 19 19.8284 19 19L19 4.5L16.3105 4.5L16.5693 7L7.43164 7L7.69043 4.5L5 4.5ZM10.7061 3C9.93758 3.00004 9.29349 3.58104 9.21436 4.3457L9.09473 5.5L14.9062 5.5L14.7866 4.3457C14.7075 3.58126 14.0632 3 13.2944 3L10.7061 3Z" />
                    <defs>
                      <linearGradient id="clipboard-gradient-id-:Rajar6l6:" x1="15.0855" y1="1.5" x2="6.47336" y2="20.9505" gradientUnits="userSpaceOnUse">
                        <stop stopColor="var(--icon-gradient-start)" />
                        <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                        <stop offset="1" stopColor="var(--icon-gradient-end)" />
                      </linearGradient>
                    </defs>
                  </svg>
                </div>
                <div className="feature-detail__content feature-detail__content--stacked">
                  <h4 className="hds-text hds-text--md hds-text--emphasized">
                    {"Test and validate new markets"}
                  </h4>
                  <p className="hds-text hds-text--md hds-text--soft">
                    {"Test market potential and customer fit before scaling, with Managed Payments handling compliance and payment requirements."}
                  </p>
                </div>
              </div>
              <div className="feature-detail">
                <div className="charm-icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" className="icon" aria-hidden="true">
                    <path fill="url(#globe-arrows-left-right-gradient-id-:Rbjar6l6:)" fillRule="evenodd" clipRule="evenodd" d="M12.0005 2c3.9041 0 7.2853 2.23755 8.9321 5.5h-1.7202c-.8921-1.42679-2.1959-2.56975-3.7451-3.2627.5995.88623 1.0939 1.99736 1.4448 3.2627h-1.564c-.216-.68899-.4772-1.31045-.7729-1.84814C13.6937 4.04918 12.7194 3.5 12.0005 3.5c-.719 0-1.6932.54918-2.57472 2.15186C8.65835 7.0472 8.11827 9.00507 8.01855 11.25H19.9619l-1.4614-1.061V8.33496l4 2.90474v1.521l-4 2.9043v-1.8535l1.4614-1.0615H8.01855c.09972 2.2449.6398 4.2028 1.40723 5.5981C10.3073 19.9508 11.2815 20.5 12.0005 20.5V22C6.47764 22 2.00049 17.5228 2.00049 12c0-5.52285 4.47715-10 10.00001-10M3.53369 12.75c.27413 3.1354 2.25031 5.7823 4.99951 7.0122-1.14021-1.6859-1.90033-4.1854-2.01562-7.0122zM8.5332 4.2373C5.7839 5.46718 3.80783 8.1145 3.53369 11.25h2.98389c.1153-2.82697.87529-5.32681 2.01562-7.0127" />
                    <path fill="url(#globe-arrows-left-right-gradient-id-:Rbjar6l6:)" d="m16.0005 16.189-1.4614 1.061h7.9614v1.5h-7.9614l1.4614 1.0615v1.8535l-4-2.9043v-1.521l4-2.9047z" />
                    <defs>
                      <linearGradient id="globe-arrows-left-right-gradient-id-:Rbjar6l6:" x1="15.9712" x2="8.76558" y1="2" y2="22.1151" gradientUnits="userSpaceOnUse">
                        <stop stopColor="var(--icon-gradient-start)" />
                        <stop offset="0.5" stopColor="var(--icon-gradient-middle)" />
                        <stop offset="1" stopColor="var(--icon-gradient-end)" />
                      </linearGradient>
                    </defs>
                  </svg>
                </div>
                <div className="feature-detail__content feature-detail__content--stacked">
                  <h4 className="hds-text hds-text--md hds-text--emphasized">
                    {"Optimize by region"}
                  </h4>
                  <p className="hds-text hds-text--md hds-text--soft">
                    {"Implement a hybrid approach by using Stripe’s merchant of record solution selectively and maintaining your existing setup for regions where direct control is preferred."}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
