/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S06Block() {
  return (
    <section className="hds-color-mode section section--white hds-mode--light">
      <div className="section-container">
        <div className="side-by-side anchor-offset--nav side-by-side-row-gap side-by-side-align" style={{ "--side-by-side-template-cols": "6fr 6fr", "--side-by-side-row-gap-mb": "var(--hds-space-core-400)", "--side-by-side-align-mb": "center" }} id="conversion">
          <div className="side-by-side-content side-by-side-content--left side-by-side-content-padding-inline-buffer" style={{ "--side-by-side-content-padding-inline-buffer-tb": "var(--hds-space-core-300)" }}>
            <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-200)", "--section-row-gap-tb": "var(--hds-space-core-300)", "--section-row-gap-dt": "var(--hds-space-core-400)" }}>
              <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-200)" }}>
                <span className="hds-heading hds-heading--lg">
                  {"Maximize your in-app revenue"}
                </span>
                <p className="hds-text hds-text--xl hds-text--soft">
                  {"Redirect app users to a web-based checkout optimized for conversion and designed to feel native. Save on payment costs while maintaining operational efficiency with Managed Payments."}
                </p>
              </div>
              <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-300)", "--section-row-gap-tb": "var(--hds-space-core-400)" }}>
                <a className="hds-button hds-button--secondary-on-quiet" href="https://stripe.com/use-cases/in-app-payments" data-analytics-label="maximise_your_inapp__accept_inapp_payments">
                  {"Accept in-app payments"}
                </a>
              </div>
            </div>
          </div>
          <div className="graphic-with-background graphic-with-background-aspect-ratio" style={{ "--graphic-with-background-aspect-ratio-mb": "368/395", "--graphic-with-background-aspect-ratio-tb": "608/692", "--graphic-with-background-aspect-ratio-dt": "608/692" }}>
            <picture className="graphic-with-background__background">
              <source type="image/webp" srcSet="/sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-16ea6d0c1b.webp 296w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-478e47846b.webp 396w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-424628729f.webp 608w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-a34b7cd97f.webp 816w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-f6a86103e5.webp 1216w" />
              <img loading="lazy" width="1216" height="1216" alt="" className="graphic-with-background__background-img" sizes="(min-width: 1296px) 608px, (min-width: 640px) calc(50vw - 32px), calc(100vw - 32px)" srcSet="/sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-c1784dd082.png 296w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-819da61fcd.png 396w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-9ca571272d.png 608w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-d791349139.png 816w, /sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-0a758539e3.png 1216w" src="/sites/stripe-com-9ababc9a/products/in-app-revenue-graphic-bg-c1784dd082.png" />
            </picture>
            <div className="graphic-with-background__foreground graphic-with-background-fg-width" style={{ "--graphic-with-background-fg-width-mb": "52.5%", "--graphic-with-background-fg-width-tb": "55%", "--graphic-with-background-fg-width-dt": "100%" }}>
              <div className="dom-graphic dom-graphic--variant-default" style={{ "--graphic-source-width": "280px", "--graphic-source-height": "570px", "--graphic-aspect-ratio": "280 / 570", "--graphic-scale": "1", "--graphic-max-width": "280px" }} data-status="measuring" role="img" aria-label="A phone showing a Stripe-hosted mobile checkout for the merchant ElementaraAI, with a product image, a $20.00 per month subscription price, a one-click Link payment button above a saved card ending in 5432, and a browser address bar reading checkout.stripe.com.">
                <div className="dom-graphic__content dom-graphic__content--horizontal-scale-left" aria-hidden="true">
                  <div className="phone-graphic" style={{ "--phone-graphic-width": "280px", "--phone-graphic-height": "570px", "--phone-graphic-mobile-width": "280px", "--phone-graphic-mobile-height": "570px" }}>
                    <div className="phone-graphic__screen">
                      <div className="in-app-revenue-graphic">
                        <div className="phone-header">
                          <div></div>
                          <div className="phone-header__status">
                            <svg width="13" height="8" viewBox="0 0 13 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path fillRule="evenodd" clipRule="evenodd" d="M12.4467 0.743057C12.4467 0.332678 12.1371 0 11.7552 0H11.0637C10.6818 0 10.3722 0.332678 10.3722 0.743057V7.18289C10.3722 7.59326 10.6818 7.92594 11.0637 7.92594H11.7552C12.1371 7.92594 12.4467 7.59326 12.4467 7.18289V0.743057ZM7.6274 1.58519H8.31888C8.70077 1.58519 9.01036 1.92585 9.01036 2.34608V7.16505C9.01036 7.58528 8.70077 7.92594 8.31888 7.92594H7.6274C7.2455 7.92594 6.93592 7.58528 6.93592 7.16505V2.34608C6.93592 1.92585 7.2455 1.58519 7.6274 1.58519ZM4.81927 3.30247H4.12779C3.74589 3.30247 3.43631 3.64747 3.43631 4.07305V7.15536C3.43631 7.58094 3.74589 7.92594 4.12779 7.92594H4.81927C5.20116 7.92594 5.51075 7.58094 5.51075 7.15536V4.07305C5.51075 3.64747 5.20116 3.30247 4.81927 3.30247ZM1.38296 4.88767H0.691481C0.309587 4.88767 0 5.22774 0 5.64724V7.16637C0 7.58587 0.309587 7.92594 0.691481 7.92594H1.38296C1.76486 7.92594 2.07444 7.58587 2.07444 7.16637V5.64724C2.07444 5.22774 1.76486 4.88767 1.38296 4.88767Z" fill="#0e0e0e" />
                            </svg>
                            <svg width="12" height="8" viewBox="0 0 12 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path fillRule="evenodd" clipRule="evenodd" d="M5.55647 1.5988C7.16877 1.59887 8.71942 2.19662 9.88792 3.26851C9.97591 3.35127 10.1166 3.35022 10.2032 3.26617L11.0443 2.44711C11.0882 2.40448 11.1127 2.34674 11.1123 2.28666C11.112 2.22657 11.0868 2.16911 11.0424 2.12698C7.97545 -0.708992 3.13699 -0.708992 0.0700488 2.12698C0.025622 2.16908 0.000414737 2.22653 5.07201e-06 2.28661C-0.000404593 2.34669 0.0240171 2.40445 0.0678659 2.44711L0.909225 3.26617C0.995831 3.35035 1.13658 3.3514 1.22452 3.26851C2.39317 2.19655 3.944 1.5988 5.55647 1.5988ZM5.55429 4.33465C6.43419 4.3346 7.28269 4.66634 7.93492 5.26542C8.02314 5.35044 8.16211 5.3486 8.2481 5.26127L9.0826 4.40601C9.12654 4.36115 9.15093 4.30029 9.1503 4.23705C9.14966 4.17381 9.12406 4.11347 9.07923 4.06952C7.09305 2.19549 4.01721 2.19549 2.03104 4.06952C1.98618 4.11347 1.96058 4.17384 1.95999 4.2371C1.9594 4.30036 1.98387 4.36121 2.02791 4.40601L2.86217 5.26127C2.94816 5.3486 3.08713 5.35044 3.17534 5.26542C3.82714 4.66674 4.67497 4.33502 5.55429 4.33465ZM7.19078 6.14561C7.19203 6.21391 7.168 6.27975 7.12438 6.3276L5.71333 7.91891C5.67196 7.96568 5.61557 7.992 5.55672 7.992C5.49788 7.992 5.44149 7.96568 5.40012 7.91891L3.98884 6.3276C3.94524 6.27972 3.92125 6.21385 3.92255 6.14556C3.92384 6.07726 3.95029 6.01259 3.99566 5.96681C4.89682 5.11506 6.21663 5.11506 7.11778 5.96681C7.16312 6.01262 7.18953 6.07732 7.19078 6.14561Z" fill="#0e0e0e" />
                            </svg>
                            <svg width="18" height="9" viewBox="0 0 18 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <rect opacity="0.35" x="0.324132" y="0.324132" width="15.5583" height="7.77917" rx="2.67587" stroke="#0e0e0e" strokeWidth="0.648264" />
                              <path opacity="0.4" d="M16.8549 3.09943V5.74141C17.3765 5.51765 17.7158 4.99712 17.7158 4.42042C17.7158 3.84372 17.3765 3.32319 16.8549 3.09943Z" fill="#0e0e0e" />
                              <rect x="1.29651" y="1.29651" width="13.6135" height="5.83437" rx="2" fill="#0e0e0e" />
                            </svg>
                          </div>
                        </div>
                        <div className="in-app-revenue-graphic__header">
                          <div className="in-app-revenue-graphic__store">
                            <div className="in-app-revenue-graphic__back">
                              <span className="in-app-revenue-graphic__back-chevron">
                                <svg xmlns="http://www.w3.org/2000/svg" width="6.22" height="6.06" fill="none" viewBox="0 0 6.22 6.06">
                                  <path fill="currentColor" d="M5.65845 0C5.81636 0 5.9492 0.0576497 6.05698 0.172949C6.16476 0.285742 6.21865 0.442399 6.21865 0.64292V5.4103C6.21865 5.61082 6.16476 5.76748 6.05698 5.88027C5.95171 5.99557 5.82012 6.05322 5.66221 6.05322C5.57949 6.05322 5.50054 6.03818 5.42534 6.00811C5.35015 5.97803 5.26367 5.93918 5.16592 5.89155L0.48501 3.63569C0.314567 3.55298 0.190495 3.46274 0.112793 3.36499C0.0375977 3.26724 0 3.15444 0 3.02661C0 2.89878 0.0375977 2.78599 0.112793 2.68823C0.190495 2.59048 0.314567 2.5015 0.48501 2.42129L5.16592 0.16167C5.26117 0.116553 5.34639 0.0789551 5.42158 0.048877C5.49678 0.0162923 5.57573 0 5.65845 0Z" />
                                </svg>
                              </span>
                              <span className="in-app-revenue-graphic__back-label">
                                {"ElementaraAI"}
                              </span>
                            </div>
                            <div className="in-app-revenue-graphic__nav">
                              <span className="in-app-revenue-graphic__nav-title">
                                {"ElementaraAI"}
                              </span>
                              <div className="in-app-revenue-graphic__nav-details">
                                <span className="in-app-revenue-graphic__nav-details-label">
                                  {"Details"}
                                </span>
                                <span className="in-app-revenue-graphic__nav-chevron">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="7.92" height="7.92" fill="none" viewBox="0 0 8 8">
                                    <path fill="currentColor" fillRule="evenodd" clipRule="evenodd" d="M6.73095 2.62175C6.92453 2.42817 7.23839 2.42817 7.43197 2.62175C7.62555 2.81533 7.62555 3.12919 7.43197 3.32277L4.3121 6.44264C4.1187 6.63604 3.80513 6.63604 3.61173 6.44264L0.491866 3.32277C0.298284 3.12919 0.298284 2.81533 0.491866 2.62175C0.685447 2.42817 0.999305 2.42817 1.19289 2.62175L3.96192 5.39078L6.73095 2.62175Z" />
                                  </svg>
                                </span>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="in-app-revenue-graphic__product">
                          <div className="in-app-revenue-graphic__product-image">
                            <img src="/sites/stripe-com-9ababc9a/products/in-app-revenue-phone-graphic-image-c662281a7a.png" aria-hidden="true" alt="" />
                          </div>
                          <div className="in-app-revenue-graphic__product-header">
                            <span className="in-app-revenue-graphic__product-title">
                              {"Pay ElementaraAI"}
                            </span>
                            <div className="in-app-revenue-graphic__product-price">
                              <span className="in-app-revenue-graphic__product-amount tabular-nums--tight">
                                {"$20.00"}
                              </span>
                              <span className="in-app-revenue-graphic__product-interval">
                                {"per month"}
                              </span>
                            </div>
                          </div>
                        </div>
                        <div className="in-app-revenue-graphic__checkout">
                          <div className="in-app-revenue-graphic__buttons">
                            <div className="in-app-revenue-graphic__button in-app-revenue-graphic__button--link">
                              <span className="in-app-revenue-graphic__button-logo">
                                <svg className="link-brand-logo link-brand-logo--black" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 78 26" fill="none" width="38" height="13" aria-hidden="true">
                                  <path className="link-brand-logo__text" d="M39.321 3.983c0-1.222 1.035-2.215 2.252-2.215 1.218 0 2.253.998 2.253 2.215a2.254 2.254 0 0 1-2.253 2.241 2.234 2.234 0 0 1-2.252-2.241M32.638 2.08h3.919v21.84h-3.92zM43.554 8.32h-3.95v15.6h3.95zM71.954 15.59c2.973-1.82 4.996-4.53 5.795-7.276H73.8c-1.03 2.621-3.392 4.592-5.989 5.43V2.073h-3.95v21.84h3.95V17.42c3.015.748 5.398 3.343 6.213 6.494H78c-.606-3.307-2.88-6.4-6.046-8.325M50.556 10.067c1.035-1.368 3.052-2.163 4.687-2.163 3.052 0 5.576 2.22 5.58 5.574v10.436h-3.95v-9.568c0-1.378-.616-2.969-2.617-2.969-2.352 0-3.705 2.075-3.705 4.503v8.045H46.6V8.33h3.955z" />
                                  <circle className="link-brand-logo__circle" cx="13" cy="13" r="13" />
                                  <path className="link-brand-logo__mark" d="M12.462 5.2H8.434c.783 3.26 3.072 6.048 5.936 7.8-2.87 1.753-5.153 4.54-5.936 7.8h4.028c.998-3.016 3.763-5.637 7.16-6.172v-3.26c-3.402-.531-6.167-3.152-7.16-6.168" />
                                </svg>
                              </span>
                            </div>
                            <div className="in-app-revenue-graphic__button in-app-revenue-graphic__button--card">
                              <span>
                                {"Pay with"}
                              </span>
                              <span className="in-app-revenue-graphic__card-details">
                                <span className="in-app-revenue-graphic__card-icon">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="14.69" height="9.79" fill="none" viewBox="0 0 14.69 9.79">
                                    <path fill="#252525" d="M13.464 0H1.224C0.548003 0 0 0.548003 0 1.224V8.568C0 9.244 0.548003 9.792 1.224 9.792H13.464C14.14 9.792 14.688 9.244 14.688 8.568V1.224C14.688 0.548003 14.14 0 13.464 0Z" />
                                    <path fill="#eb001b" d="M5.508 7.95594C7.19799 7.95594 8.568 6.58593 8.568 4.89594C8.568 3.20595 7.19799 1.83594 5.508 1.83594C3.81801 1.83594 2.448 3.20595 2.448 4.89594C2.448 6.58593 3.81801 7.95594 5.508 7.95594Z" />
                                    <path fill="#f79e1b" d="M9.18012 7.95594C10.8701 7.95594 12.2401 6.58593 12.2401 4.89594C12.2401 3.20595 10.8701 1.83594 9.18012 1.83594C7.49013 1.83594 6.12012 3.20595 6.12012 4.89594C6.12012 6.58593 7.49013 7.95594 9.18012 7.95594Z" />
                                    <path fill="#ff5f00" fillRule="evenodd" clipRule="evenodd" d="M7.34412 2.44727C8.08736 3.00554 8.56812 3.89437 8.56812 4.89549C8.56812 5.89661 8.08736 6.78544 7.34412 7.34371C6.60088 6.78544 6.12012 5.89661 6.12012 4.89549C6.12012 3.89437 6.60088 3.00554 7.34412 2.44727Z" />
                                  </svg>
                                </span>
                                <span className="in-app-revenue-graphic__card-number tabular-nums--tight">
                                  {"•••• 5432"}
                                </span>
                              </span>
                            </div>
                          </div>
                          <span className="in-app-revenue-graphic__alt-text">
                            {"Or pay another way"}
                          </span>
                        </div>
                        <div className="in-app-revenue-graphic__chrome">
                          <span className="in-app-revenue-graphic__url-pill">
                            {"checkout.stripe.com"}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
