/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S08Block() {
  return (
    <section className="hds-color-mode section hds-mode--dark">
      <div className="section-container">
        <div className="side-by-side anchor-offset--nav side-by-side-row-gap side-by-side-align" style={{ "--side-by-side-template-cols": "6fr 6fr", "--side-by-side-row-gap-mb": "var(--hds-space-core-400)", "--side-by-side-align-mb": "center" }} id="conversion">
          <div className="side-by-side-content side-by-side-content--left side-by-side-content-padding-inline-buffer" style={{ "--side-by-side-content-padding-inline-buffer-tb": "var(--hds-space-core-300)" }}>
            <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-200)", "--section-row-gap-tb": "var(--hds-space-core-300)", "--section-row-gap-dt": "var(--hds-space-core-400)" }}>
              <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-200)" }}>
                <span className="hds-heading hds-heading--lg">
                  {"Get started in minutes"}
                </span>
                <p className="hds-text hds-text--xl hds-text--soft">
                  {"Go live instantly using payment links, or add one line of code to Checkout. Stay live on a reliable platform with 99.999% historical uptime."}
                </p>
              </div>
              <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-300)", "--section-row-gap-tb": "var(--hds-space-core-400)" }}>
                <a className="hds-button hds-button--secondary-on-quiet" href="https://docs.stripe.com/payments/managed-payments/update-checkout" data-analytics-label="managed_payments__get_started__update_checkout">
                  {"Explore the docs"}
                </a>
              </div>
            </div>
          </div>
          <div className="dom-graphic dom-graphic--variant-default" style={{ "--graphic-source-width": "608px", "--graphic-source-height": "360px", "--graphic-aspect-ratio": "608 / 360", "--graphic-scale": "1", "--graphic-max-width": "608px" }} data-status="measuring" role="img" aria-label="Code sample showing a Stripe Checkout Session created with managed payments enabled.">
            <div className="dom-graphic__content dom-graphic__content--horizontal-scale-left" aria-hidden="true">
              <div className="checkout-session-code-graphic__window">
                <div className="checkout-session-code-graphic__code-block">
                  <div className="checkout-session-code-graphic__line-numbers">
                    <span className="checkout-session-code-graphic__line-number">
                      {"1"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"2"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"3"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"4"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"5"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"6"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"7"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"8"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"9"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"10"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"11"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"12"}
                    </span>
                    <span className="checkout-session-code-graphic__line-number">
                      {"13"}
                    </span>
                  </div>
                  <div className="checkout-session-code-graphic__lines">
                    <span className="checkout-session-code-graphic__line">
                      <span className="checkout-session-code-graphic__token--keyword">
                        {"const"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {" session = "}
                      </span>
                      <span className="checkout-session-code-graphic__token--keyword">
                        {"await"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {" stripe.checkout.sessions."}
                      </span>
                      <span className="checkout-session-code-graphic__token--method">
                        {"create"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {"({"}
                      </span>
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" line_items: ["}
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" {"}
                    </span>
                    <span className="checkout-session-code-graphic__line">
                      <span className="checkout-session-code-graphic__token--plain">
                        {" price: "}
                      </span>
                      <span className="checkout-session-code-graphic__token--string">
                        {"'{{PRICE_ID}}'"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {","}
                      </span>
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" quantity: 1,"}
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" },"}
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" ],"}
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" managed_payments: {"}
                    </span>
                    <span className="checkout-session-code-graphic__line">
                      <span className="checkout-session-code-graphic__token--plain">
                        {" enabled: "}
                      </span>
                      <span className="checkout-session-code-graphic__token--keyword">
                        {"true"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {","}
                      </span>
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {" },"}
                    </span>
                    <span className="checkout-session-code-graphic__line">
                      <span className="checkout-session-code-graphic__token--plain">
                        {" mode: "}
                      </span>
                      <span className="checkout-session-code-graphic__token--string">
                        {"'subscription'"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {","}
                      </span>
                    </span>
                    <span className="checkout-session-code-graphic__line">
                      <span className="checkout-session-code-graphic__token--plain">
                        {" success_url: "}
                      </span>
                      <span className="checkout-session-code-graphic__token--string">
                        {"'https://localhost:4242/success'"}
                      </span>
                      <span className="checkout-session-code-graphic__token--plain">
                        {","}
                      </span>
                    </span>
                    <span className="checkout-session-code-graphic__line checkout-session-code-graphic__token--plain">
                      {"});"}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
