/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S01IncreaseAuthorizationRatesWith() {
  return (
    <section className="Section theme--White Section--angleTop Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div>
                  <div className="ColumnLayout" data-columns="1,1,1,1">
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" viewBox="0 0 39 37" xmlns="http://www.w3.org/2000/svg" width="39" height="37">
                            <defs>
                              <clipPath id="areaChartIconClipPath--a">
                                <path d="M1.55 35.68l12.32-6.4a1 1 0 0 0 .44-.45L24.8 6.7a1 1 0 0 1 1.56-.33l12.3 10.64a1 1 0 0 1 .34.76V33a4 4 0 0 1-4 4H1.87a.7.7 0 0 1-.32-1.32z" className="Icon__blendBackground" fill="var(--blendBackground)" />
                              </clipPath>
                            </defs>
                            <path d="M1.55 35.68l12.32-6.4a1 1 0 0 0 .44-.45L24.8 6.7a1 1 0 0 1 1.56-.33l12.3 10.64a1 1 0 0 1 .34.76V33a4 4 0 0 1-4 4H1.87a.7.7 0 0 1-.32-1.32z" className="Icon__blendBackground" fill="var(--blendBackground)" />
                            <path d="M.76 34.6L12.1 19.26a1 1 0 0 1 1.09-.37l11.65 3.4a1 1 0 0 0 1.17-.5L37.1.6a1 1 0 0 1 1.89.46V33a4 4 0 0 1-4 4H1.97a1.5 1.5 0 0 1-1.2-2.4z" className="Icon__blendForeground" fill="var(--blendForeground)" />
                            <g clipPath="url(#areaChartIconClipPath--a)">
                              <path d="M.76 34.6L12.1 19.26a1 1 0 0 1 1.09-.37l11.65 3.4a1 1 0 0 0 1.17-.5L37.1.6a1 1 0 0 1 1.89.46V33a4 4 0 0 1-4 4H1.97a1.5 1.5 0 0 1-1.2-2.4z" className="Icon__blendForeground" fill="var(--blendIntersection)" />
                            </g>
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Increase authorization rates with AI "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Recover false declines with real-time retries and maximize acceptance using issuer-optimized preferences."}
                        </p>
                      </div>
                      <footer className="Copy__footer">
                        <a className="CtaButton variant--Link CtaButton--arrow CtaButton--jumpArrowLink" href="https://stripe.com/authorization#ai-powered" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="authorization_ai_powered_jump">
                          {"Explore"}
                          <svg className="JumpArrow" width="28" height="28" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
                            <rect width="28" height="28" rx="14" className="JumpArrow__iconRect" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--a" strokeWidth="1.75" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--b" strokeWidth="1.75" />
                          </svg>
                        </a>
                      </footer>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 37" width="40" height="37">
                            <defs>
                              <clipPath id="GlobeWithMoneyIconClipPath--a">
                                <path d="M11.17 23.81c3.13.32 6.29.32 9.42 0a.4.4 0 0 1 .43.49c-1.03 4.54-2.88 7.6-5 7.76h-.14v-.01h-.16c-2.12-.14-3.96-3.21-4.99-7.75a.4.4 0 0 1 .44-.49zm19.17-2.77a.4.4 0 0 1 .57.49 16.1 16.1 0 0 1-9.56 9.56.4.4 0 0 1-.5-.57 21.48 21.48 0 0 0 2.35-6.82.4.4 0 0 1 .31-.32c2.4-.4 4.7-1.18 6.83-2.34zm-28.68 0a21.57 21.57 0 0 0 6.83 2.34.4.4 0 0 1 .31.32c.4 2.39 1.18 4.7 2.35 6.82a.4.4 0 0 1-.5.57 16.1 16.1 0 0 1-9.56-9.56.4.4 0 0 1 .57-.5zm14.22-10.98c1.77 0 3.55.1 5.31.34a.4.4 0 0 1 .35.35c.46 3.52.46 7.1 0 10.62a.41.41 0 0 1-.35.35c-3.53.47-7.1.47-10.62 0a.4.4 0 0 1-.36-.34c-.44-3.53-.44-7.1 0-10.63a.4.4 0 0 1 .35-.35c1.76-.22 3.54-.33 5.32-.34zm-7.9.95c.1.09.15.21.14.34a46.42 46.42 0 0 0 0 9.42.4.4 0 0 1-.49.43c-10-2.24-10.33-7.86 0-10.28a.4.4 0 0 1 .35.1zm16.32-.1l.08.01c10.32 2.42 10 8.04-.01 10.28a.4.4 0 0 1-.49-.43c.32-3.13.32-6.29 0-9.42a.4.4 0 0 1 .5-.43zm-2.97-9.88a16.1 16.1 0 0 1 9.57 9.56.4.4 0 0 1-.57.5 21.57 21.57 0 0 0-6.83-2.35.4.4 0 0 1-.31-.32c-.4-2.39-1.19-4.7-2.35-6.83a.4.4 0 0 1 .5-.56zm-10.66 0a.4.4 0 0 1 .49.56A21.57 21.57 0 0 0 8.8 8.42a.4.4 0 0 1-.31.32c-2.4.4-4.7 1.18-6.83 2.34l-.08.04a.4.4 0 0 1-.49-.53 16.1 16.1 0 0 1 9.57-9.56zm5.36-.97c2.11.14 3.96 3.22 4.99 7.75a.4.4 0 0 1-.43.5 46.42 46.42 0 0 0-9.42 0 .4.4 0 0 1-.43-.5C11.76 3.29 13.6.22 15.72.07h.3z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                              </clipPath>
                            </defs>
                            <path d="M11.17 23.81c3.13.32 6.29.32 9.42 0a.4.4 0 0 1 .43.49c-1.03 4.54-2.88 7.6-5 7.76h-.14v-.01h-.16c-2.12-.14-3.96-3.21-4.99-7.75a.4.4 0 0 1 .44-.49zm19.17-2.77a.4.4 0 0 1 .57.49 16.1 16.1 0 0 1-9.56 9.56.4.4 0 0 1-.5-.57 21.48 21.48 0 0 0 2.35-6.82.4.4 0 0 1 .31-.32c2.4-.4 4.7-1.18 6.83-2.34zm-28.68 0a21.57 21.57 0 0 0 6.83 2.34.4.4 0 0 1 .31.32c.4 2.39 1.18 4.7 2.35 6.82a.4.4 0 0 1-.5.57 16.1 16.1 0 0 1-9.56-9.56.4.4 0 0 1 .57-.5zm14.22-10.98c1.77 0 3.55.1 5.31.34a.4.4 0 0 1 .35.35c.46 3.52.46 7.1 0 10.62a.41.41 0 0 1-.35.35c-3.53.47-7.1.47-10.62 0a.4.4 0 0 1-.36-.34c-.44-3.53-.44-7.1 0-10.63a.4.4 0 0 1 .35-.35c1.76-.22 3.54-.33 5.32-.34zm-7.9.95c.1.09.15.21.14.34a46.42 46.42 0 0 0 0 9.42.4.4 0 0 1-.49.43c-10-2.24-10.33-7.86 0-10.28a.4.4 0 0 1 .35.1zm16.32-.1l.08.01c10.32 2.42 10 8.04-.01 10.28a.4.4 0 0 1-.49-.43c.32-3.13.32-6.29 0-9.42a.4.4 0 0 1 .5-.43zm-2.97-9.88a16.1 16.1 0 0 1 9.57 9.56.4.4 0 0 1-.57.5 21.57 21.57 0 0 0-6.83-2.35.4.4 0 0 1-.31-.32c-.4-2.39-1.19-4.7-2.35-6.83a.4.4 0 0 1 .5-.56zm-10.66 0a.4.4 0 0 1 .49.56A21.57 21.57 0 0 0 8.8 8.42a.4.4 0 0 1-.31.32c-2.4.4-4.7 1.18-6.83 2.34l-.08.04a.4.4 0 0 1-.49-.53 16.1 16.1 0 0 1 9.57-9.56zm5.36-.97c2.11.14 3.96 3.22 4.99 7.75a.4.4 0 0 1-.43.5 46.42 46.42 0 0 0-9.42 0 .4.4 0 0 1-.43-.5C11.76 3.29 13.6.22 15.72.07h.3z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                            <path d="M34.87 15c1.79 0 2.43.19 3.08.53.66.35 1.17.86 1.52 1.52.34.65.53 1.3.53 3.08v11.74c0 1.79-.19 2.43-.53 3.08a3.63 3.63 0 0 1-1.52 1.52c-.65.34-1.3.53-3.08.53H13.13c-1.79 0-2.43-.19-3.08-.53a3.63 3.63 0 0 1-1.52-1.52C8.2 34.3 8 33.65 8 31.87V20.13c0-1.79.19-2.43.53-3.08.35-.66.86-1.17 1.52-1.52.65-.34 1.3-.53 3.08-.53h21.74zM24 21a5 5 0 1 0 0 10 5 5 0 0 0 0-10z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                            <g clipPath="url(#GlobeWithMoneyIconClipPath--a)">
                              <path d="M34.87 15c1.79 0 2.43.19 3.08.53.66.35 1.17.86 1.52 1.52.34.65.53 1.3.53 3.08v11.74c0 1.79-.19 2.43-.53 3.08a3.63 3.63 0 0 1-1.52 1.52c-.65.34-1.3.53-3.08.53H13.13c-1.79 0-2.43-.19-3.08-.53a3.63 3.63 0 0 1-1.52-1.52C8.2 34.3 8 33.65 8 31.87V20.13c0-1.79.19-2.43.53-3.08.35-.66.86-1.17 1.52-1.52.65-.34 1.3-.53 3.08-.53h21.74zM24 21a5 5 0 1 0 0 10 5 5 0 0 0 0-10z" className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} />
                            </g>
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Lower card processing costs "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Reduce costs with network tokens and AI-powered optimizations, such as decline prevention and excessive retry prevention."}
                        </p>
                      </div>
                      <footer className="Copy__footer">
                        <a className="CtaButton variant--Link CtaButton--arrow CtaButton--jumpArrowLink" href="https://stripe.com/authorization#cost-optimization" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="authorization_cost_optimization_jump">
                          {"Explore"}
                          <svg className="JumpArrow" width="28" height="28" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
                            <rect width="28" height="28" rx="14" className="JumpArrow__iconRect" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--a" strokeWidth="1.75" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--b" strokeWidth="1.75" />
                          </svg>
                        </a>
                      </footer>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <defs>
                              <clipPath id="CardWithCheckmarkIconClipPath-">
                                <path fillRule="evenodd" clipRule="evenodd" d="M4 6C1.79086 6 0 7.79086 0 10V24C0 26.2091 1.79086 28 4 28H28C30.2091 28 32 26.2091 32 24V10C32 7.79086 30.2091 6 28 6H4ZM3.75 10C3.33579 10 3 10.3358 3 10.75V12.25C3 12.6642 3.33579 13 3.75 13H28.25C28.6642 13 29 12.6642 29 12.25V10.75C29 10.3358 28.6642 10 28.25 10H3.75Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                              </clipPath>
                            </defs>
                            <path fillRule="evenodd" clipRule="evenodd" d="M4 6C1.79086 6 0 7.79086 0 10V24C0 26.2091 1.79086 28 4 28H28C30.2091 28 32 26.2091 32 24V10C32 7.79086 30.2091 6 28 6H4ZM3.75 10C3.33579 10 3 10.3358 3 10.75V12.25C3 12.6642 3.33579 13 3.75 13H28.25C28.6642 13 29 12.6642 29 12.25V10.75C29 10.3358 28.6642 10 28.25 10H3.75Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                            <path fillRule="evenodd" clipRule="evenodd" d="M30 16C34.9706 16 39 20.0294 39 25C39 29.9706 34.9706 34 30 34C25.0294 34 21 29.9706 21 25C21 20.0294 25.0294 16 30 16ZM33.94 20.73L28 26.78L26.43 25C26.1336 24.7182 25.6762 24.6943 25.352 24.9436C25.0279 25.193 24.9337 25.6413 25.13 26L27 29.2C27.1823 29.4942 27.5039 29.6732 27.85 29.6732C28.1961 29.6732 28.5177 29.4942 28.7 29.2C29 28.79 34.7 21.63 34.7 21.63C35.45 20.83 34.54 20.12 33.94 20.73Z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                            <path fillRule="evenodd" clipRule="evenodd" d="M32 16.223C31.3568 16.0771 30.6874 16 30 16C25.0294 16 21 20.0294 21 25C21 26.0519 21.1805 27.0617 21.5121 28H26.2987L25.13 26C24.9337 25.6413 25.0279 25.193 25.352 24.9436C25.6762 24.6943 26.1336 24.7182 26.43 25L28 26.78L32 22.7059V16.223ZM30.123 27.3907C30.6247 26.7574 31.2075 26.023 31.7857 25.2949C31.4866 26.1696 30.893 26.9076 30.123 27.3907Z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                            <g clipPath="url(#CardWithCheckmarkIconClipPath-)">
                              <path fillRule="evenodd" clipRule="evenodd" d="M32 16.223C31.3568 16.0771 30.6874 16 30 16C25.0294 16 21 20.0294 21 25C21 26.0519 21.1805 27.0617 21.5121 28H26.2987L25.13 26C24.9337 25.6413 25.0279 25.193 25.352 24.9436C25.6762 24.6943 26.1336 24.7182 26.43 25L28 26.78L32 22.7059V16.223ZM30.123 27.3907C30.6247 26.7574 31.2075 26.023 31.7857 25.2949C31.4866 26.1696 30.893 26.9076 30.123 27.3907Z" className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} />
                            </g>
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Reduce customer churn "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Automatically keep card information up-to-date, even if a card has been replaced, and retry false declines to mitigate involuntary churn."}
                        </p>
                      </div>
                      <footer className="Copy__footer">
                        <a className="CtaButton variant--Link CtaButton--arrow CtaButton--jumpArrowLink" href="https://stripe.com/authorization#lifecycle-management" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="authorization_lifecycle_management_jump">
                          {"Explore"}
                          <svg className="JumpArrow" width="28" height="28" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
                            <rect width="28" height="28" rx="14" className="JumpArrow__iconRect" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--a" strokeWidth="1.75" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--b" strokeWidth="1.75" />
                          </svg>
                        </a>
                      </footer>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <defs>
                              <clipPath id="HeartbeatWithCheckmarkIconClipPath-">
                                <path fillRule="evenodd" clipRule="evenodd" d="M38 21C38 31.4934 29.4934 40 19 40C8.50659 40 0 31.4934 0 21C0 10.5066 8.50659 2 19 2C29.4934 2 38 10.5066 38 21ZM18.0127 9.50008C18.4784 9.50597 18.8783 9.83259 18.9772 10.2877L21.9561 24H35.7361C35.6148 24.6816 35.4528 25.3491 35.2528 26H21.15C20.6795 26 20.2727 25.672 20.1728 25.2123L17.9437 14.9512L13.9715 31.237C13.8675 31.6633 13.4978 31.972 13.0597 31.9982C12.6217 32.0244 12.2178 31.762 12.0637 31.3511L8.46416 21.7524L6.99687 25.3754C6.84396 25.7529 6.47734 26 6.07 26H2.7472C2.5472 25.3491 2.38522 24.6816 2.26387 24H5.3961L7.57313 18.6246C7.72782 18.2427 8.10097 17.9947 8.51302 18.0001C8.92507 18.0054 9.29164 18.263 9.43633 18.6489L12.7972 27.6112L17.0285 10.263C17.1388 9.81057 17.547 9.49419 18.0127 9.50008Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                              </clipPath>
                            </defs>
                            <path fillRule="evenodd" clipRule="evenodd" d="M38 21C38 31.4934 29.4934 40 19 40C8.50659 40 0 31.4934 0 21C0 10.5066 8.50659 2 19 2C29.4934 2 38 10.5066 38 21ZM18.0127 9.50008C18.4784 9.50597 18.8783 9.83259 18.9772 10.2877L21.9561 24H35.7361C35.6148 24.6816 35.4528 25.3491 35.2528 26H21.15C20.6795 26 20.2727 25.672 20.1728 25.2123L17.9437 14.9512L13.9715 31.237C13.8675 31.6633 13.4978 31.972 13.0597 31.9982C12.6217 32.0244 12.2178 31.762 12.0637 31.3511L8.46416 21.7524L6.99687 25.3754C6.84396 25.7529 6.47734 26 6.07 26H2.7472C2.5472 25.3491 2.38522 24.6816 2.26387 24H5.3961L7.57313 18.6246C7.72782 18.2427 8.10097 17.9947 8.51302 18.0001C8.92507 18.0054 9.29164 18.263 9.43633 18.6489L12.7972 27.6112L17.0285 10.263C17.1388 9.81057 17.547 9.49419 18.0127 9.50008Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                            <path fillRule="evenodd" clipRule="evenodd" d="M31 0C35.9706 0 40 4.02944 40 9C40 13.9706 35.9706 18 31 18C26.0294 18 22 13.9706 22 9C22 4.02944 26.0294 0 31 0ZM34.94 4.73L29 10.78L27.43 9C27.1336 8.71821 26.6762 8.69428 26.352 8.94363C26.0279 9.19297 25.9337 9.64126 26.13 10L28 13.2C28.1823 13.4942 28.5039 13.6732 28.85 13.6732C29.1961 13.6732 29.5177 13.4942 29.7 13.2C30 12.79 35.7 5.63 35.7 5.63C36.45 4.83 35.54 4.12 34.94 4.73Z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                            <g clipPath="url(#HeartbeatWithCheckmarkIconClipPath-)">
                              <path fillRule="evenodd" clipRule="evenodd" d="M31 0C35.9706 0 40 4.02944 40 9C40 13.9706 35.9706 18 31 18C26.0294 18 22 13.9706 22 9C22 4.02944 26.0294 0 31 0ZM34.94 4.73L29 10.78L27.43 9C27.1336 8.71821 26.6762 8.69428 26.352 8.94363C26.0279 9.19297 25.9337 9.64126 26.13 10L28 13.2C28.1823 13.4942 28.5039 13.6732 28.85 13.6732C29.1961 13.6732 29.5177 13.4942 29.7 13.2C30 12.79 35.7 5.63 35.7 5.63C36.45 4.83 35.54 4.12 34.94 4.73Z" className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} />
                            </g>
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Manage performance from the Dashboard "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Get a comprehensive view of your payments performance, including insights and recommendations."}
                        </p>
                      </div>
                      <footer className="Copy__footer">
                        <a className="CtaButton variant--Link CtaButton--arrow CtaButton--jumpArrowLink" href="https://stripe.com/authorization#analytics" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="authorization_analytics_jump">
                          {"Explore"}
                          <svg className="JumpArrow" width="28" height="28" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
                            <rect width="28" height="28" rx="14" className="JumpArrow__iconRect" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--a" strokeWidth="1.75" />
                            <path d="m14 19 4-4m-4 4-4-4m4 4V8" className="JumpArrow__iconArrow JumpArrow__iconArrow--b" strokeWidth="1.75" />
                          </svg>
                        </a>
                      </footer>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
