/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S10IssuerAndNetworkPartnerships() {
  return (
    <section className="Section Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section">
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"Issuer and network partnerships"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Tap into the industry’s richest data to improve performance "}
                    </h1>
                  </header>
                  <div className="Copy__body">
                    <p>
                      {"Stripe has direct connections to card networks to ensure our data is as rich as possible. Our industry-first Enhanced Issuer Network enables card issuers to make more informed decisions about whether to authorize transactions."}
                    </p>
                  </div>
                </section>
                <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2" data-columns-tablet="1">
                  <div className="RowLayout SideBySide__leftRowLayout">
                    <section className="Copy variant--Subsection" style={{ "--footerPaddingRight": "var(--columnPaddingLarge)" }}>
                      <header className="Copy__header">
                        <h1 className="Copy__title">
                          {" Enhanced Issuer Network "}
                        </h1>
                      </header>
                      <footer className="Copy__footer">
                        <section className="List" data-column-count="1">
                          <ul className="List__list">
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <g fill="var(--accentColor)" fillRule="evenodd">
                                  <circle opacity=".15" cx="8" cy="8" r="8" />
                                  <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                                </g>
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Comprises several major US and European issuers, including Capital One, Discover, and American Express"}
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <g fill="var(--accentColor)" fillRule="evenodd">
                                  <circle opacity=".15" cx="8" cy="8" r="8" />
                                  <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                                </g>
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Provides issuers with secure access to transaction fraud scores from Radar"}
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <g fill="var(--accentColor)" fillRule="evenodd">
                                  <circle opacity=".15" cx="8" cy="8" r="8" />
                                  <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                                </g>
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Helps businesses achieve a 1%–2% authorization rate uplift on eligible volume and up to 8% reduction in fraud"}
                              </span>
                            </li>
                          </ul>
                        </section>
                      </footer>
                    </section>
                  </div>
                  <div className="RowLayout SideBySide__rightRowLayout">
                    <section className="Copy variant--Subsection" style={{ "--footerPaddingRight": "var(--columnPaddingLarge)" }}>
                      <header className="Copy__header">
                        <h1 className="Copy__title">
                          {" Direct platform "}
                        </h1>
                      </header>
                      <footer className="Copy__footer">
                        <section className="List" data-column-count="1">
                          <ul className="List__list">
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <g fill="var(--accentColor)" fillRule="evenodd">
                                  <circle opacity=".15" cx="8" cy="8" r="8" />
                                  <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                                </g>
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Connect to Visa, Mastercard, Discover, American Express, and local networks through a single integration"}
                              </span>
                            </li>
                            <li className="List__item ListItem ListItem--hasIcon">
                              <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                                <g fill="var(--accentColor)" fillRule="evenodd">
                                  <circle opacity=".15" cx="8" cy="8" r="8" />
                                  <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                                </g>
                              </svg>
                              {" "}
                              <span className="ListItem__label">
                                {"Improve reliability through Stripe’s direct integrations with global card networks and issuers"}
                              </span>
                            </li>
                          </ul>
                        </section>
                      </footer>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
