/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S01AutomateDataDeliveryAt() {
  return (
    <section className="Section theme--White Section--angleTop Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div>
                  <div className="ColumnLayout" data-columns="1,1,1,1">
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <defs>
                              <clipPath id="DataWithGearIconClipPath-">
                                <path fillRule="evenodd" clipRule="evenodd" d="M14 6C21.732 6 28 4.65685 28 3C28 1.34315 21.732 0 14 0C6.26801 0 0 1.34315 0 3C0 4.65685 6.26801 6 14 6ZM0 6.00004V14C0 15.6569 6.26801 17 14 17C21.732 17 28 15.6569 28 14V6.00004C28 7.65689 21.732 9.00004 14 9.00004C6.26801 9.00004 0 7.65689 0 6.00004ZM0 25V17C0 18.6569 6.26801 20 14 20C21.732 20 28 18.6569 28 17V25V25C28 26.6569 21.732 28 14 28C6.26801 28 0 26.6569 0 25V25Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                              </clipPath>
                            </defs>
                            <path fillRule="evenodd" clipRule="evenodd" d="M14 6C21.732 6 28 4.65685 28 3C28 1.34315 21.732 0 14 0C6.26801 0 0 1.34315 0 3C0 4.65685 6.26801 6 14 6ZM0 6.00004V14C0 15.6569 6.26801 17 14 17C21.732 17 28 15.6569 28 14V6.00004C28 7.65689 21.732 9.00004 14 9.00004C6.26801 9.00004 0 7.65689 0 6.00004ZM0 25V17C0 18.6569 6.26801 20 14 20C21.732 20 28 18.6569 28 17V25V25C28 26.6569 21.732 28 14 28C6.26801 28 0 26.6569 0 25V25Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                            <path fillRule="evenodd" clipRule="evenodd" d="M27.5 14L28.6294 17.1321C28.8458 17.1675 29.0599 17.21 29.2715 17.2591L31.5129 14.7982L32.4368 15.1809L32.2816 18.507C32.4668 18.6224 32.6479 18.7437 32.8247 18.8706L35.8388 17.4541L36.5459 18.1612L35.1294 21.1753C35.2563 21.3521 35.3776 21.5332 35.493 21.7184L38.8191 21.5632L39.2018 22.4871L36.7409 24.7285C36.79 24.9401 36.8325 25.1542 36.8679 25.3706L40 26.5V27.5L36.8679 28.6294C36.8274 28.8767 36.7778 29.121 36.7194 29.362L39.2018 31.5129L38.8191 32.4368L35.5419 32.2025C35.3958 32.4418 35.2399 32.6745 35.0749 32.9L36.5459 35.8388L35.8388 36.5459L32.9 35.0749C32.6745 35.2399 32.4418 35.3958 32.2025 35.5419L32.4368 38.8191L31.5129 39.2018L29.362 36.7194C29.0913 36.785 28.8164 36.8395 28.5376 36.8825L27.5 40H26.5L25.4624 36.8825C25.1836 36.8395 24.9087 36.785 24.638 36.7194L22.4871 39.2018L21.5632 38.8191L21.7975 35.5419C21.5582 35.3958 21.3255 35.2399 21.1 35.0749L18.1612 36.5459L17.4541 35.8388L18.9251 32.9C18.7601 32.6745 18.6042 32.4418 18.4581 32.2025L15.1809 32.4368L14.7982 31.5129L17.2806 29.362C17.215 29.0913 17.1605 28.8164 17.1175 28.5376L14 27.5V26.5L17.1175 25.4624C17.1557 25.2146 17.203 24.9699 17.2591 24.7285L14.7982 22.4871L15.1809 21.5632L18.507 21.7184C18.6224 21.5332 18.7437 21.3521 18.8706 21.1753L17.4541 18.1612L18.1612 17.4541L21.1753 18.8706C21.3521 18.7437 21.5332 18.6224 21.7184 18.507L21.5632 15.1809L22.4871 14.7982L24.7285 17.2591C24.7285 17.2591 25.1542 17.1675 25.3706 17.1321L26.5 14H27.5ZM27 25C25.8954 25 25 25.8954 25 27C25 28.1046 25.8954 29 27 29C28.1046 29 29 28.1046 29 27C29 25.8954 28.1046 25 27 25Z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                            <g clipPath="url(#DataWithGearIconClipPath-)">
                              <path fillRule="evenodd" clipRule="evenodd" d="M27.5 14L28.6294 17.1321C28.8458 17.1675 29.0599 17.21 29.2715 17.2591L31.5129 14.7982L32.4368 15.1809L32.2816 18.507C32.4668 18.6224 32.6479 18.7437 32.8247 18.8706L35.8388 17.4541L36.5459 18.1612L35.1294 21.1753C35.2563 21.3521 35.3776 21.5332 35.493 21.7184L38.8191 21.5632L39.2018 22.4871L36.7409 24.7285C36.79 24.9401 36.8325 25.1542 36.8679 25.3706L40 26.5V27.5L36.8679 28.6294C36.8274 28.8767 36.7778 29.121 36.7194 29.362L39.2018 31.5129L38.8191 32.4368L35.5419 32.2025C35.3958 32.4418 35.2399 32.6745 35.0749 32.9L36.5459 35.8388L35.8388 36.5459L32.9 35.0749C32.6745 35.2399 32.4418 35.3958 32.2025 35.5419L32.4368 38.8191L31.5129 39.2018L29.362 36.7194C29.0913 36.785 28.8164 36.8395 28.5376 36.8825L27.5 40H26.5L25.4624 36.8825C25.1836 36.8395 24.9087 36.785 24.638 36.7194L22.4871 39.2018L21.5632 38.8191L21.7975 35.5419C21.5582 35.3958 21.3255 35.2399 21.1 35.0749L18.1612 36.5459L17.4541 35.8388L18.9251 32.9C18.7601 32.6745 18.6042 32.4418 18.4581 32.2025L15.1809 32.4368L14.7982 31.5129L17.2806 29.362C17.215 29.0913 17.1605 28.8164 17.1175 28.5376L14 27.5V26.5L17.1175 25.4624C17.1557 25.2146 17.203 24.9699 17.2591 24.7285L14.7982 22.4871L15.1809 21.5632L18.507 21.7184C18.6224 21.5332 18.7437 21.3521 18.8706 21.1753L17.4541 18.1612L18.1612 17.4541L21.1753 18.8706C21.3521 18.7437 21.5332 18.6224 21.7184 18.507L21.5632 15.1809L22.4871 14.7982L24.7285 17.2591C24.7285 17.2591 25.1542 17.1675 25.3706 17.1321L26.5 14H27.5ZM27 25C25.8954 25 25 25.8954 25 27C25 28.1046 25.8954 29 27 29C28.1046 29 29 28.1046 29 27C29 25.8954 28.1046 25 27 25Z" className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} />
                            </g>
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Automate data delivery at scale "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Set up Stripe Data Pipeline in minutes and automatically receive your Stripe data and reports in your data storage destination on an ongoing basis—no code required."}
                        </p>
                      </div>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                            <path className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} d="M36 11a4 4 0 0 1 4 4v21a4 4 0 0 1-4 4H12a4 4 0 0 1-4-4V15a4 4 0 0 1 4-4zm-7.9 18h-1.2a1 1 0 0 0-.54.09.59.59 0 0 0-.27.27 1 1 0 0 0-.09.54v5.2a1 1 0 0 0 .09.54.59.59 0 0 0 .27.27 1 1 0 0 0 .54.09h1.2a1 1 0 0 0 .54-.09.59.59 0 0 0 .27-.27 1 1 0 0 0 .09-.54v-5.2a1 1 0 0 0-.09-.54.59.59 0 0 0-.27-.27 1 1 0 0 0-.54-.09zm7-3h-1.2a1 1 0 0 0-.54.09.59.59 0 0 0-.27.27 1 1 0 0 0-.09.54v8.2a1 1 0 0 0 .09.54.59.59 0 0 0 .27.27 1 1 0 0 0 .54.09h1.2a1 1 0 0 0 .54-.09.59.59 0 0 0 .27-.27 1 1 0 0 0 .09-.54v-8.2a1 1 0 0 0-.09-.54.59.59 0 0 0-.27-.27 1 1 0 0 0-.54-.09zm-21 0h-1.2a1 1 0 0 0-.54.09.59.59 0 0 0-.27.27 1 1 0 0 0-.09.54v8.2a1 1 0 0 0 .09.54.59.59 0 0 0 .27.27 1 1 0 0 0 .54.09h1.2a1 1 0 0 0 .54-.09.59.59 0 0 0 .27-.27 1 1 0 0 0 .09-.54v-8.2a1 1 0 0 0-.09-.54.59.59 0 0 0-.27-.27 1 1 0 0 0-.54-.09zm7-7h-1.2a1 1 0 0 0-.54.09.59.59 0 0 0-.27.27 1 1 0 0 0-.09.54v15.2a1 1 0 0 0 .09.54.59.59 0 0 0 .27.27 1 1 0 0 0 .54.09h1.2a1 1 0 0 0 .54-.09.59.59 0 0 0 .27-.27 1 1 0 0 0 .09-.54V19.9a1 1 0 0 0-.09-.54.59.59 0 0 0-.27-.27 1 1 0 0 0-.54-.09z" />
                            <path className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} d="M28 0a4 4 0 0 1 4 4v14a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4a4 4 0 0 1 4-4zM16 6a5 5 0 1 0 5 5 5 5 0 0 0-5-5z" />
                            <path className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} d="M32 11v7a4 4 0 0 1-4 4h-6v-2.1a1 1 0 0 0-.09-.54.59.59 0 0 0-.27-.27 1 1 0 0 0-.54-.09h-1.2a1 1 0 0 0-.54.09.59.59 0 0 0-.27.27.9.9 0 0 0-.09.42V22H8v-7a4 4 0 0 1 3-3.87V11a5 5 0 0 0 10 0z" />
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Establish a single source of truth "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Centralize your Stripe data in one place to speed up your financial close, identify top payment methods, enhance AI models, and more. "}
                        </p>
                      </div>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <div className="AnimatedIcon ShieldWithCheckmarkIcon">
                            <div className="AnimatedIcon__iconContainer">
                              <svg className="AnimatedIcon__icon" width="96" height="96" preserveAspectRatio="xMinYMin" viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg" data-js-controller="ShieldWithCheckmarkIcon">
                                <defs>
                                  <path id="shieldWithCheckmarkIconShield" d="M29.5 31.2727C29.5 31.2727 35.8 35.866 43 35.866V45.9713C43 60.6698 31.3 66.1818 29.5 66.1818C27.7 66.1818 16 60.6698 16 45.9713V35.866C23.2 35.866 29.5 31.2727 29.5 31.2727Z" />
                                  <path id="shieldWithCheckmarkIconContent" fillRule="evenodd" clipRule="evenodd" d="M12 31.27H47V66.27H12V31.27ZM26.0385 46.7422C26.0385 44.8246 27.5882 43.27 29.5 43.27C31.4118 43.27 32.9615 44.8246 32.9615 46.7422V48.1311H33.3077C33.69 48.1311 34 48.442 34 48.8256V52.9922C34 53.7593 33.3801 54.3811 32.6154 54.3811H26.3846C25.6199 54.3811 25 53.7593 25 52.9922V48.8256C25 48.442 25.31 48.1311 25.6923 48.1311H26.0385V46.7422ZM29.5 44.6589C30.6471 44.6589 31.5769 45.5917 31.5769 46.7423V48.1312H27.4231V46.7423C27.4231 45.5917 28.353 44.6589 29.5 44.6589Z" />
                                  <path id="shieldWithCheckmarkIconCheck" className="ShieldWithCheckmarkIcon__check" d="M42 30C46.9706 30 51 34.0294 51 39C51 43.9706 46.9706 48 42 48C37.0294 48 33 43.9706 33 39C33 34.0294 37.0294 30 42 30ZM45.94 34.73L40 40.78L38.43 39C38.1336 38.7182 37.6762 38.6943 37.352 38.9436C37.0279 39.193 36.9337 39.6413 37.13 40L39 43.2C39.1823 43.4942 39.5039 43.6732 39.85 43.6732C40.1961 43.6732 40.5177 43.4942 40.7 43.2C41 42.79 46.7 35.63 46.7 35.63C47.45 34.83 46.54 34.12 45.94 34.73Z" data-js-target-list="ShieldWithCheckmarkIcon.checks" />
                                  <clipPath id="shieldWithCheckmarkIconShieldClipPath">
                                    <use href="#shieldWithCheckmarkIconShield" />
                                  </clipPath>
                                </defs>
                                <use className="ShieldWithCheckmarkIcon__check" href="#shieldWithCheckmarkIconCheck" fill="var(--blendForeground)" data-js-target-list="ShieldWithCheckmarkIcon.checks" />
                                <g clipPath="url(#shieldWithCheckmarkIconShieldClipPath)">
                                  <use className="ShieldWithCheckmarkIcon__content" href="#shieldWithCheckmarkIconContent" fill="var(--blendBackground)" data-js-target="ShieldWithCheckmarkIcon.content" />
                                  <use className="ShieldWithCheckmarkIcon__check" href="#shieldWithCheckmarkIconCheck" fill="var(--blendIntersection)" data-js-target-list="ShieldWithCheckmarkIcon.checks" />
                                </g>
                              </svg>
                            </div>
                          </div>
                        </div>
                        <h1 className="Copy__title">
                          {" Use a direct and secure integration "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Send your Stripe data directly to your data warehouse or cloud storage without involving a third-party extract, transform, and load (ETL) pipeline."}
                        </p>
                      </div>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <svg className="Icon" viewBox="0 0 40 36" xmlns="http://www.w3.org/2000/svg" width="40" height="36">
                            <defs>
                              <clipPath id="verticalArrowsIconClipPath--a">
                                <path d="M11.65 9.52a2 2 0 0 1 2.7 0l11 10a2 2 0 1 1-2.7 2.96L15 15.52V34a2 2 0 1 1-4 0V15.52l-7.65 6.96a2 2 0 0 1-2.7-.01l-.13-.12a2 2 0 0 1 .13-2.83z" className="Icon__blendBackground" fill="var(--blendBackground)" />
                              </clipPath>
                            </defs>
                            <path d="M11.65 9.52a2 2 0 0 1 2.7 0l11 10a2 2 0 1 1-2.7 2.96L15 15.52V34a2 2 0 1 1-4 0V15.52l-7.65 6.96a2 2 0 0 1-2.7-.01l-.13-.12a2 2 0 0 1 .13-2.83z" className="Icon__blendBackground" fill="var(--blendBackground)" />
                            <path d="M27 0a2 2 0 0 1 2 2v17.23l7.65-6.96a2 2 0 1 1 2.7 2.96l-11 10a2 2 0 0 1-2.7 0l-11-10a2 2 0 0 1 2.7-2.96L25 19.23V2c0-1.1.9-2 2-2z" className="Icon__blendForeground" fill="var(--blendForeground)" />
                            <g clipPath="url(#verticalArrowsIconClipPath--a)">
                              <path d="M27 0a2 2 0 0 1 2 2v17.23l7.65-6.96a2 2 0 1 1 2.7 2.96l-11 10a2 2 0 0 1-2.7 0l-11-10a2 2 0 0 1 2.7-2.96L25 19.23V2c0-1.1.9-2 2-2z" className="Icon__blendForeground" fill="var(--blendIntersection)" />
                            </g>
                          </svg>
                        </div>
                        <h1 className="Copy__title">
                          {" Avoid data outages and delays "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Offload ongoing maintenance with a pipeline that’s built into Stripe. No matter how much data you have, your data is always complete and accurate."}
                        </p>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
