/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S04HowItWorks() {
  return (
    <section className="Section theme--Light accent--Raspberry Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section">
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"How it works"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Set up your pipeline in minutes—no data engineering required "}
                    </h1>
                  </header>
                </section>
                <section className="StackedCarousel" data-js-controller="StackedCarousel" style={{ "--stackedCarouselItemCount": "3" }}>
                  <div data-js-controller="StackedCarouselControl">
                    <div className="StackedCarouselControl__itemList" data-js-target="StackedCarouselControl.items">
                      <div className="StackedCarousel__detailContainer StackedCarousel__detailContainer--isActive" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 1 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Select your data warehouse or cloud storage"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Data Pipeline can connect directly to your Snowflake, Redshift, BigQuery or Databricks account. It can also connect with cloud storage destinations. This allows you to send your data to a variety of additional warehouses."}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer StackedCarousel__imageContainer--isActive" data-js-target-list="StackedCarouselControl.images">
                        <picture className="Picture Picture--autosize">
                          <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/step1-data-pipeline_updated-Jul2026-en-US_2x-ce0fbc33d0.webp 2x,\n            /sites/stripe-com-9ababc9a/products/step1-data-pipeline_updated-Jul2026-en-US_2x-1e57f21181.webp\n          "} type="image/webp" />
                          <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/step1-data-pipeline_updated-Jul2026-en-US_2x-76d7f6ec8d.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/step1-data-pipeline_updated-Jul2026-en-US_2x-76d7f6ec8d.png 2x,\n          /sites/stripe-com-9ababc9a/products/step1-data-pipeline_updated-Jul2026-en-US_2x-0c1f5345bc.png\n        "} alt="" width="1080" height="1080" loading="lazy" />
                        </picture>
                      </div>
                      <div className="StackedCarousel__detailContainer" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 2 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Connect your account"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Provide the account information associated with your data storage destination. Stripe shares your data using industry-leading "}
                            <a className="Link" href="https://docs.stripe.com/security" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                              {"security practices"}
                            </a>
                            {"."}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer" data-js-target-list="StackedCarouselControl.images">
                        <picture className="Picture Picture--autosize">
                          <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/step2-data-pipeline_en-2f921574fa.webp 2x,\n            /sites/stripe-com-9ababc9a/products/step2-data-pipeline_en-8ae18ff9e4.webp\n          "} type="image/webp" />
                          <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/step2-data-pipeline_en-9fdd678a0f.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/step2-data-pipeline_en-9fdd678a0f.png 2x,\n          /sites/stripe-com-9ababc9a/products/step2-data-pipeline_en-bdbcd7b33b.png\n        "} alt="" width="1080" height="1110" loading="lazy" />
                        </picture>
                      </div>
                      <div className="StackedCarousel__detailContainer" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 3 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"You’re set"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Your historical data takes up to six hours to load, and new data will be regularly refreshed every three hours. Start querying your Stripe data and reports in your own data warehouse, or use the structured files exported to your cloud storage destination."}
                          </p>
                          <a className="CtaButton variant--Link CtaButton--arrow" href="https://docs.stripe.com/stripe-data/available-data" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="data_pipeline_data_freshness">
                            {"Learn more about data freshness"}
                            <span className="nobr">
                              <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                <g fillRule="evenodd">
                                  <path className="HoverArrow__linePath" d="M0 5h7" />
                                  <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                </g>
                              </svg>
                            </span>
                          </a>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer" data-js-target-list="StackedCarouselControl.images">
                        <div className="Card Card--shadowXLarge">
                          <picture className="Picture Picture--autosize">
                            <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/step3-data-pipeline_en-8433b461d5.webp 2x,\n            /sites/stripe-com-9ababc9a/products/step3-data-pipeline_en-c4b4cf8d96.webp\n          "} type="image/webp" />
                            <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/step3-data-pipeline_en-06fecc81a5.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/step3-data-pipeline_en-06fecc81a5.png 2x,\n          /sites/stripe-com-9ababc9a/products/step3-data-pipeline_en-eca3a13d10.png\n        "} alt="" width="1080" height="1080" loading="lazy" />
                          </picture>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
