/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S07HowItWorks() {
  return (
    <section className="Section theme--Light Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapLarge)" }}>
                <section className="Copy variant--Section" style={{ "--footerPaddingLeft": "var(--columnPaddingNone)", "--footerPaddingRight": "var(--columnPaddingNone)" }}>
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"How it works"}
                    </h2>
                    <h1 className="Copy__title">
                      {" End-to-end tax compliance solution "}
                    </h1>
                  </header>
                </section>
                <div>
                  <div className="ColumnLayout" data-columns="1,1,1,1">
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <div className="NumberIcon">
                            <span className="NumberIcon__label">
                              {" 1 "}
                            </span>
                          </div>
                        </div>
                        <h1 className="Copy__title">
                          {" Integrate in minutes "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Add a single line of code to your existing integration, or enable tax collection directly in the Dashboard."}
                        </p>
                      </div>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <div className="NumberIcon">
                            <span className="NumberIcon__label">
                              {" 2 "}
                            </span>
                          </div>
                        </div>
                        <h1 className="Copy__title">
                          {" Know your obligations "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"See when and where you have tax obligations. Stripe Tax monitors your transactions and helps you register globally—and submit in new locations in under a minute."}
                        </p>
                      </div>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <div className="NumberIcon">
                            <span className="NumberIcon__label">
                              {" 3 "}
                            </span>
                          </div>
                        </div>
                        <h1 className="Copy__title">
                          {" Collect taxes automatically "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Stripe Tax calculates and collects the right amount of tax based on your customer's location, and it validates VAT IDs when needed."}
                        </p>
                      </div>
                    </section>
                    <section className="Copy variant--Detail">
                      <header className="Copy__header">
                        <div className="Copy__icon">
                          <div className="NumberIcon">
                            <span className="NumberIcon__label">
                              {" 4 "}
                            </span>
                          </div>
                        </div>
                        <h1 className="Copy__title">
                          {" File with confidence "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Automate global filings through Stripe or our pre-integrated filing partners. You can also use our detailed reports to file on your own."}
                        </p>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
