/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S16Resources() {
  return (
    <section className="Section theme--White Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapSmall)" }}>
                <section className="Copy variant--Section" style={{ "--paddingRight": "var(--columnPaddingMedium)" }}>
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"Resources"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Sales tax, VAT, and GST resources "}
                    </h1>
                  </header>
                  <div className="Copy__body">
                    <p>
                      {"Learn more about global tax compliance and how to use Stripe Tax. "}
                    </p>
                  </div>
                </section>
                <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2" data-columns-tablet="1">
                  <div className="RowLayout SideBySide__leftRowLayout">
                    <section className="List" data-column-count="1">
                      <ul className="List__list">
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://docs.stripe.com/billing/subscriptions/tax/automatic-tax" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="setting_up_stripe_tax_for_billing">
                            {"Setting up Tax for Stripe Billing"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://docs.stripe.com/payments/checkout/automatic_taxes" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="setting_up_stripe_tax_for_checkout">
                            {"Setting up Tax for Stripe Checkout"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://docs.stripe.com/tax/invoicing" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="setting_up_stripe_tax_for_invoicing">
                            {"Setting up Tax for Stripe Invoicing"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://docs.stripe.com/tax/custom" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="setting_up_stripe_tax_with_custom_checkout_or_payment_flows">
                            {"Setting up Tax with custom checkout or payment flows"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/how-to-file-sales-tax-us" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="how_to_file_sales_tax_returns_in_the_us">
                            {"How to file sales tax returns in the US"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://docs.stripe.com/tax/reports" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="using_stripes_reports_to_file_taxes">
                            {"Using Stripe’s reports to file taxes"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/tools/sales-tax-calculator" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="sales_tax_calculator">
                            {"Sales tax calculator"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/tools/vat-calculator" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="vat_calculator">
                            {"VAT calculator"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/tools/gst-calculator" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="gst_calculator">
                            {"GST calculator"}
                          </a>
                        </li>
                      </ul>
                      <div className="CtaGroup CtaGroup--inline List__ctaGroup">
                        <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/guides/tax-guides" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="sales_tax_vat__see_all_tax_guides">
                          {"See all tax guides"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                      </div>
                    </section>
                  </div>
                  <div className="RowLayout SideBySide__rightRowLayout">
                    <section className="List" data-column-count="1">
                      <ul className="List__list">
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href={"https://stripe.com/guides/introduction-to-sales-tax-vat-and-gst-compliance?utm_medium=earned-event&utm_source=5f6d&utm_campaign=GLOBAL_461f&utm_content=a9d2&utm_term=0d80e72007d8"} data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="guide_to_sales_tax_vat_and_gst_compliance">
                            {"Guide to sales tax, VAT, and GST compliance"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/introduction-to-eu-vat-and-vat-oss" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="understanding_eu_vat_and_vat_oss">
                            {"Understanding EU VAT and VAT OSS"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href={"https://stripe.com/guides/introduction-to-us-sales-tax-and-economic-nexus?utm_medium=earned-event&utm_source=9209&utm_campaign=GLOBAL_47c4&utm_content=978a&utm_term=ae22bb043e68"} data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="understanding_us_sales_tax_and_economic_nexus">
                            {"Understanding US sales tax and economic nexus"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/blog/building-stripe-tax" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="understanding_how_we_built_stripe_tax">
                            {"Understanding how we built Stripe Tax"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/sales-tax-registration-process-us" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="navigating_the_sales_tax_registration_process_in_the_us">
                            {"Navigating the sales tax registration process in the US"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/tax-registration-process-europe" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="navigating_the_tax_registration_process_in_europe">
                            {"Navigating the tax registration process in Europe"}
                          </a>
                        </li>
                        <li className="List__item ListItem ListItem--hasIcon">
                          <svg className="ListIcon List__itemIcon" width="16" height="16" viewBox="0 0 16 16">
                            <g fill="var(--accentColor)" fillRule="evenodd">
                              <circle opacity=".15" cx="8" cy="8" r="8" />
                              <path d="M11.41 4.93L6.64 9.54 5.38 8.18a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36.24-.31 4.82-5.78 4.82-5.78.6-.6-.13-1.15-.6-.68z" />
                            </g>
                          </svg>
                          {" "}
                          <a className="Link ListItem__label" href="https://stripe.com/guides/tax-registration-process-canada" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="navigating_the_tax_registration_process_in_canada">
                            {"Navigating the tax registration process in Canada"}
                          </a>
                        </li>
                      </ul>
                    </section>
                  </div>
                </div>
                <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2">
                  <div className="RowLayout SideBySide__leftRowLayout">
                    <section className="Copy variant--Detail">
                      <footer className="Copy__footer">
                        <div className="CopyBody CopyBody--variantDetail CopyBody--anchored">
                          <p>
                            {"If you’re looking for help with 1099 tax forms for platforms, learn about "}
                            <a className="Link" href="https://stripe.com/connect/1099" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                              {"Connect capabilities"}
                            </a>
                            {"."}
                          </p>
                        </div>
                      </footer>
                    </section>
                  </div>
                  <div className="RowLayout SideBySide__rightRowLayout"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
