/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S07CheckoutStudio() {
  return (
    <section className="Section theme--Light flavor--Twilight accent--Purple Section--angleNone Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout">
                <div className="ColumnLayout" data-columns="3,1" style={{ "--columnRowGap": "var(--rowGapSmall)" }}>
                  <section className="Copy variant--Section" style={{ "--paddingRight": "var(--columnPaddingMedium)" }}>
                    <header className="Copy__header">
                      <h2 className="Copy__caption">
                        {"Checkout studio"}
                      </h2>
                      <h1 className="Copy__title">
                        {" AI-powered home for building, monitoring, and optimizing checkout "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      {" The Checkout studio provides integration guidance that gets you live faster, reports for monitoring performance and gathering a deeper understanding of your customers, and contextual recommendations powered by the strength of Stripe’s network to grow your business. "}
                    </div>
                  </section>
                </div>
                <div className="ColumnLayout" data-columns="1,1,1,1" style={{ "--columnRowGap": "var(--rowGapSmall)" }}>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <h1 className="Copy__title">
                        {" Configure "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      {" Add new checkout configurations with a visually guided Stripe Checkout builder "}
                    </div>
                  </section>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <h1 className="Copy__title">
                        {" Monitor "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      {" Access reporting to track checkout performance, features, and updates "}
                    </div>
                  </section>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <h1 className="Copy__title">
                        {" Optimize "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      {" Get tailored recommendations to test and optimize performance "}
                    </div>
                  </section>
                </div>
                <div className="Card Card--border Card--borderSoft">
                  <picture className="Picture Picture--autosize">
                    <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/checkout-studio-en-US_2x-d0ae12f1a9.webp 2x,\n            /sites/stripe-com-9ababc9a/products/checkout-studio-en-US_2x-ae9189403c.webp\n          "} type="image/webp" />
                    <img className="Picture__image" src="/sites/stripe-com-9ababc9a/products/checkout-studio-en-US_2x-05eda469a3.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/checkout-studio-en-US_2x-05eda469a3.png 2x,\n          /sites/stripe-com-9ababc9a/products/checkout-studio-en-US_2x-71ae344828.png\n        "} alt="A screenshot of the Checkout studio UI featuring the builder, an experiment and a funnel chart" width="1080" height="600" loading="lazy" />
                  </picture>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
