/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S01BuiltIntoStripe() {
  return (
    <section className="Section theme--White Section--angleBoth Section--bleed3 Section--paddingNormal Section--hasGuides" style={{ "--sectionPaddingBottom": "calc(var(--sectionAngleHeight)*0.46)" }}>
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section" style={{ "--footerPaddingLeft": "var(--columnPaddingNone)", "--footerPaddingRight": "var(--columnPaddingNone)" }}>
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"Built into Stripe"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Take the complexity out of revenue recognition "}
                    </h1>
                  </header>
                  <footer className="Copy__footer">
                    <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2" data-columns-tablet="1">
                      <div className="RowLayout SideBySide__leftRowLayout">
                        <section className="Copy variant--Subsection" style={{ "--paddingRight": "var(--columnPaddingLarge)" }}>
                          <div className="Copy__body">
                            <p>
                              {"As your business grows, accounting for revenue can quickly become tedious and error-prone. We built a "}
                              <a className="Link" href="https://stripe.com/guides/introduction-to-revenue-recognition" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                                {"revenue recognition"}
                              </a>
                              {" solution directly into Stripe, so you can automate GAAP accrual accounting for your transactions and billing terms."}
                            </p>
                          </div>
                        </section>
                      </div>
                      <div className="RowLayout SideBySide__rightRowLayout">
                        <section className="Copy variant--Subsection" style={{ "--paddingRight": "var(--columnPaddingLarge)" }}>
                          <div className="Copy__body">
                            <p>
                              {"Stripe Revenue Recognition effortlessly handles even the most complex scenarios—upgrades, downgrades, prorations, refunds, and disputes. With consistently updated data, you can prepare audit-ready financial statements and gain a comprehensive view of your business."}
                            </p>
                          </div>
                        </section>
                      </div>
                    </div>
                  </footer>
                </section>
                <div className="Card Card--shadowXLarge">
                  <picture className="Picture Picture--autosize">
                    <img className="Picture__image" src="/sites/stripe-com-9ababc9a/products/Revenue_recognition_dashboard-en-US-2c0d2d5a00.svg" alt="Revenue Recognition Dashboard" width="1080" height="693" loading="lazy" />
                  </picture>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
