/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S00ProductHeroSection() {
  return (
    <section className="Section ProductHeroSection ProductHeroSection--excludesNav ProductHeroSection--contentAngledMarginBottomNormal HeroSection HeroSection--hasGradient theme--Light Section--angleBottom Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="HeroSection__gradient Gradient">
                <canvas className="Gradient__canvas" data-js-controller="Gradient" data-transition-in=""></canvas>
              </div>
              <div className="RowLayout ProductHeroSection__layout">
                <div className="RowLayout ProductHeroSection__content">
                  <div className="ColumnLayout" data-columns="2,2" data-columns-tablet="1">
                    <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapNormal)" }}>
                      <div className="ProductHeroCaption">
                        <div className="ProductHeroCaption__content">
                          <div className="ProductHeroCaption__caption">
                            {"Frictionless checkout"}
                          </div>
                        </div>
                      </div>
                      <section className="Copy variant--Hero">
                        <header className="Copy__header">
                          <h1 className="Copy__title">
                            {" Boost conversion and reduce costs with Link "}
                          </h1>
                        </header>
                        <div className="Copy__body">
                          <p>
                            {"Link autofills your customers’ payment information to create an easy and secure checkout experience."}
                          </p>
                        </div>
                        <footer className="Copy__footer">
                          <div className="CtaGroup CtaGroup--inline Copy__ctaGroup">
                            <a className="CtaButton variant--Button CtaButton--arrow" href="https://stripe.com/docs/payments/link" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="payment_method_link_hero_docs_cta">
                              {"Explore the docs"}
                              <span className="nobr">
                                <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                  <g fillRule="evenodd">
                                    <path className="HoverArrow__linePath" d="M0 5h7" />
                                    <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                  </g>
                                </svg>
                              </span>
                            </a>
                            {" "}
                            <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/contact/sales" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="paymentmethod_link_hero_contact_sales">
                              {"Contact sales"}
                              <span className="nobr">
                                <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                  <g fillRule="evenodd">
                                    <path className="HoverArrow__linePath" d="M0 5h7" />
                                    <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                  </g>
                                </svg>
                              </span>
                            </a>
                          </div>
                        </footer>
                      </section>
                    </div>
                    <div className="LinkPaymentMethodHeroGraphic" data-js-controller="LinkPaymentMethodHeroGraphic">
                      <figure className="DomGraphic" aria-hidden="true" data-js-controller="DomGraphic" data-js-source-width="338" data-js-source-height="692" data-js-max-width="275px">
                        <div className="DomGraphic__heightContainer">
                          <div className="DomGraphic__scaleContainer" data-js-target="DomGraphic.scaleContainer">
                            <figure className="LinkPhoneAnimation LinkPaymentMethodHeroGraphic__phoneAnimation LinkPhoneAnimation--accentGreen" data-js-target="LinkPaymentMethodHeroGraphic.phone" data-js-controller="LinkPhoneAnimation" data-disable-replay="false" aria-hidden="true">
                              <div className="LinkPhoneAnimation__phone">
                                <div className="LinkPhoneAnimation__checkoutScreen" data-js-target="LinkPhoneAnimation.checkoutScreen">
                                  <div className="LinkPhoneAnimation__screenContent">
                                    <div className="LinkPhoneAnimation__nav">
                                      <svg className="LinkPhoneAnimation__navArrow" width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path fillRule="evenodd" clipRule="evenodd" d="M2.20002 4.14064H9.31384C9.65303 4.14064 9.92799 4.41561 9.92799 4.75479C9.92799 5.09398 9.65303 5.36895 9.31384 5.36895H2.20002L5.01978 8.18871C5.25984 8.42877 5.25984 8.81799 5.01978 9.05806C4.77972 9.29812 4.3905 9.29812 4.15043 9.05806L0.281443 5.18907C0.0416022 4.94922 0.0416022 4.56036 0.281443 4.32052L4.15043 0.451532C4.3905 0.211469 4.77972 0.211469 5.01978 0.451532C5.25984 0.691595 5.25984 1.08081 5.01978 1.32088L2.20002 4.14064Z" />
                                      </svg>
                                    </div>
                                    <div className="LinkPhoneAnimation__product" data-js-target="LinkPhoneAnimation.product">
                                      <div className="LinkPhoneAnimation__productPreview">
                                        <picture className="Picture LinkPhoneAnimation__productThumbnail">
                                          <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/link-powdur-mobile-a9cc3153b4.webp 2x,\n            /sites/stripe-com-9ababc9a/products/link-powdur-mobile-82dd8686cf.webp\n          "} type="image/webp" />
                                          <img className="Picture__image" src="/sites/stripe-com-9ababc9a/products/link-powdur-mobile-b7dc6c9c74.jpg" srcSet={"\n          /sites/stripe-com-9ababc9a/products/link-powdur-mobile-b7dc6c9c74.jpg 2x,\n          /sites/stripe-com-9ababc9a/products/link-powdur-mobile-1908b24f0a.jpg\n        "} alt="" width="142" height="142" loading="lazy" />
                                        </picture>
                                        <div className="LinkPhoneAnimation__productQuantity">
                                          {"1 item"}
                                        </div>
                                      </div>
                                      <div className="LinkPhoneAnimation__productPrice">
                                        <div className="LinkPhoneAnimation__productPriceLabel">
                                          {"Pay"}
                                        </div>
                                        <div className="LinkPhoneAnimation__productPriceAmount">
                                          {"$42.08"}
                                        </div>
                                      </div>
                                    </div>
                                    <div className="LinkPhoneAnimation__formContainer">
                                      <div className="LinkPhoneAnimation__form" data-js-target="LinkPhoneAnimation.form">
                                        <div className="LinkPhoneAnimation__field">
                                          <div className="LinkPhoneAnimation__fieldLabel" data-js-target="LinkPhoneAnimation.emailLabel">
                                            {"Email"}
                                          </div>
                                          <div className="LinkPhoneAnimation__fieldInput" data-js-target-list="LinkPhoneAnimation.secondaryFormElements" data-js-target="LinkPhoneAnimation.emailInput">
                                            <span className="LinkPhoneAnimation__emailFieldInput" data-js-target="LinkPhoneAnimation.emailInputText"></span>
                                            {" "}
                                            <svg className="Spinner LinkPhoneAnimation__fieldInputSpinner" data-js-target="LinkPhoneAnimation.emailSpinner" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
                                              <g className="Spinner__circle" fill="none" fillRule="evenodd">
                                                <circle cx="8" cy="8" r="8" />
                                                <path fill="currentColor" fillRule="nonzero" d="M8 16a.62.62 0 1 1 0-1.24A6.76 6.76 0 1 0 2.76 3.71a.62.62 0 1 1-.96-.77A7.99 7.99 0 0 1 16 8a8 8 0 0 1-8 8z" />
                                              </g>
                                            </svg>
                                          </div>
                                        </div>
                                        <div className="LinkPhoneAnimation__field" data-js-target-list="LinkPhoneAnimation.additionalFields">
                                          <div className="LinkPhoneAnimation__fieldLabel">
                                            {"Card information"}
                                          </div>
                                          <div className="LinkPhoneAnimation__fieldSet">
                                            <div className="LinkPhoneAnimation__fieldSelect LinkPhoneAnimation__fieldInput">
                                              <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                {"1234 1234 1234 1234"}
                                              </span>
                                              <div className="LinkPhoneAnimation__fieldCardContainer">
                                                <svg width="24" height="16" viewBox="0 0 24 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                  <path d="M21.9574 0H2.04255C0.914482 0 0 0.924315 0 2.06452V13.9355C0 15.0757 0.914482 16 2.04255 16H21.9574C23.0855 16 24 15.0757 24 13.9355V2.06452C24 0.924315 23.0855 0 21.9574 0Z" fill="white" />
                                                  <path d="M2.04255 0.25H21.9574C22.9449 0.25 23.75 1.05986 23.75 2.06452V13.9355C23.75 14.9401 22.9449 15.75 21.9574 15.75H2.04255C1.05507 15.75 0.25 14.9401 0.25 13.9355V2.06452C0.25 1.05986 1.05507 0.25 2.04255 0.25Z" stroke="black" strokeOpacity="0.2" strokeWidth="0.5" />
                                                  <path d="M2.5917 5.84716C2.05743 5.55098 1.44767 5.31276 0.76593 5.14745L0.794526 5.01872H3.58974C3.96862 5.03214 4.27605 5.14736 4.37609 5.55429L4.98356 8.48165L5.16966 9.36333L6.87109 5.01872H8.70818L5.97738 11.3833H4.14019L2.5917 5.84716ZM10.0595 11.39H8.32218L9.40884 5.01872H11.1461L10.0595 11.39ZM16.3575 5.17448L16.1213 6.55028L15.9641 6.48263C15.6498 6.35381 15.2348 6.22507 14.67 6.23867C13.984 6.23867 13.6764 6.51641 13.6693 6.78757C13.6693 7.08585 14.0414 7.28242 14.6491 7.57394C15.65 8.02807 16.1143 8.58381 16.1074 9.3091C16.0933 10.6309 14.9065 11.485 13.0836 11.485C12.3042 11.4781 11.5535 11.3219 11.146 11.1459L11.3891 9.71566L11.6179 9.81746C12.1827 10.0549 12.5543 10.1564 13.248 10.1564C13.7482 10.1564 14.2845 9.95962 14.2913 9.53279C14.2913 9.25487 14.0628 9.05136 13.3907 8.73957C12.733 8.43445 11.8538 7.92618 11.868 7.01108C11.8754 5.77076 13.0836 4.90323 14.7993 4.90323C15.4713 4.90323 16.0149 5.04557 16.3575 5.17448ZM18.6666 9.13289H20.1107C20.0392 8.81434 19.7102 7.28927 19.7102 7.28927L19.5888 6.74028C19.503 6.97748 19.353 7.36386 19.3602 7.35025C19.3602 7.35025 18.8097 8.76687 18.6666 9.13289ZM20.8111 5.01872L22.2127 11.3899H20.6041C20.6041 11.3899 20.4467 10.6579 20.3968 10.4342H18.1662C18.1017 10.6036 17.8016 11.3899 17.8016 11.3899H15.9787L18.5593 5.54735C18.7381 5.13385 19.0529 5.01872 19.4673 5.01872H20.8111Z" fill="#b0b0b0" />
                                                </svg>
                                                {" "}
                                                <svg width="24" height="16" viewBox="0 0 24 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                  <path d="M22 0H2C0.89543 0 0 0.89543 0 2V14C0 15.1046 0.89543 16 2 16H22C23.1046 16 24 15.1046 24 14V2C24 0.89543 23.1046 0 22 0Z" fill="#252525" />
                                                  <path d="M9 13C11.7614 13 14 10.7614 14 8C14 5.23858 11.7614 3 9 3C6.23858 3 4 5.23858 4 8C4 10.7614 6.23858 13 9 13Z" fill="#7d7d7d" />
                                                  <path d="M15 13C17.7614 13 20 10.7614 20 8C20 5.23858 17.7614 3 15 3C12.2386 3 10 5.23858 10 8C10 10.7614 12.2386 13 15 13Z" fill="#acacac" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M12 3.99963C13.2144 4.91184 14 6.36418 14 8C14 9.63582 13.2144 11.0882 12 12.0004C10.7856 11.0882 10 9.63582 10 8C10 6.36418 10.7856 4.91184 12 3.99963Z" fill="#9a9a9a" />
                                                </svg>
                                                {" "}
                                                <svg width="24" height="16" viewBox="0 0 24 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                  <path d="M22 0H2C0.89543 0 0 0.89543 0 2V14C0 15.1046 0.89543 16 2 16H22C23.1046 16 24 15.1046 24 14V2C24 0.89543 23.1046 0 22 0Z" fill="#bcbcbc" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M13.764 13.3939V7.69247L23.9116 7.70158V9.27647L22.7387 10.5299L23.9116 11.7948V13.4031H22.039L21.0438 12.3049L20.0557 13.4072L13.764 13.3939Z" fill="#ffffff" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M14.4418 12.7688V8.31992H18.2141V9.3448H15.6632V10.0405H18.1533V11.0483H15.6632V11.7316H18.2141V12.7688H14.4418Z" fill="#bcbcbc" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M18.1953 12.7688L20.2826 10.5418L18.1952 8.32001H19.8108L21.0863 9.73004L22.3654 8.32001H23.9116V8.35501L21.8687 10.5418L23.9116 12.7057V12.7688H22.3499L21.0518 11.3446L19.767 12.7688H18.1953Z" fill="#bcbcbc" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M14.2374 2.63196H16.6834L17.5426 4.58281V2.63196H20.5624L21.0832 4.09353L21.6057 2.63196H23.9116V8.33335H11.7251L14.2374 2.63196Z" fill="#ffffff" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M14.7005 3.25137L12.7264 7.69654H14.0803L14.4528 6.80638H16.4707L16.8429 7.69654H18.2304L16.2647 3.25137H14.7005ZM14.8701 5.80881L15.4621 4.39374L16.0536 5.80881H14.8701Z" fill="#bcbcbc" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M18.212 7.69572V3.25064L20.1151 3.25718L21.0944 5.98991L22.08 3.25064H23.9116V7.69572L22.733 7.70615V4.65281L21.6204 7.69572H20.5446L19.409 4.64238V7.69572H18.212Z" fill="#bcbcbc" />
                                                </svg>
                                              </div>
                                            </div>
                                            <div className="LinkPhoneAnimation__fieldInputRow">
                                              <div className="LinkPhoneAnimation__fieldInput">
                                                <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                  {"MM / YY"}
                                                </span>
                                              </div>
                                              <div className="LinkPhoneAnimation__fieldInput">
                                                <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                  {"CVC"}
                                                </span>
                                                {" "}
                                                <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                  <path opacity="0.2" fillRule="evenodd" clipRule="evenodd" d="M16.5181 1.5238H1.52381C0.822857 1.5238 0 2.33142 0 3.04761V14.4762C0 15.1924 0.822857 16 1.52381 16H20.5714C21.2724 16 22.0952 15.1924 22.0952 14.4762V8.73904C21.4534 9.31641 20.6607 9.69954 19.8095 9.8438V9.90476C19.8095 10.4076 19.5352 10.6667 19.0476 10.6667H2.28571C1.7981 10.6667 1.52381 10.4076 1.52381 9.90476V9.14285C1.52381 8.63999 1.7981 8.38095 2.28571 8.38095H15.6419C15.2021 7.89354 14.8728 7.31684 14.6766 6.69035C14.4804 6.06385 14.4219 5.40235 14.5051 4.75114C14.5883 4.09993 14.8113 3.47439 15.1587 2.91736C15.5061 2.36033 15.9699 1.88496 16.5181 1.5238V1.5238Z" fill="#565656" />
                                                  <path opacity="0.3" fillRule="evenodd" clipRule="evenodd" d="M14.7352 3.80951H0V6.09522H14.5371C14.4091 5.32881 14.4773 4.54247 14.7352 3.80951Z" fill="#565656" />
                                                  <path fillRule="evenodd" clipRule="evenodd" d="M19.0476 10.6667C17.6331 10.6667 16.2766 10.1048 15.2764 9.10457C14.2762 8.10437 13.7143 6.74782 13.7143 5.33333C13.7143 3.91885 14.2762 2.56229 15.2764 1.5621C16.2766 0.561903 17.6331 0 19.0476 0C20.4621 0 21.8187 0.561903 22.8188 1.5621C23.819 2.56229 24.3809 3.91885 24.3809 5.33333C24.3809 6.74782 23.819 8.10437 22.8188 9.10457C21.8187 10.1048 20.4621 10.6667 19.0476 10.6667ZM16.9295 3.12381H16.3276L14.8571 3.87048V4.63238L16.0229 4.02286V7.54286H16.9371V3.12381H16.9295ZM18.6819 3.73333C19.1162 3.73333 19.4209 3.97714 19.4209 4.32762C19.4209 4.70857 19.0629 4.97524 18.5448 4.97524H18.3162V5.62286H18.5905C19.139 5.62286 19.5124 5.89714 19.5124 6.29333C19.5124 6.67429 19.1467 6.93333 18.6286 6.93333C18.2476 6.93333 17.8667 6.81143 17.4705 6.57524V7.33714C17.8971 7.52 18.3238 7.61905 18.7429 7.61905C19.7409 7.61905 20.4267 7.10857 20.4267 6.36952C20.4267 5.85143 20.1067 5.43238 19.5733 5.26476C20.0305 5.11238 20.3276 4.70857 20.3276 4.25143C20.3276 3.53524 19.6952 3.04762 18.7809 3.04762C18.3688 3.05219 17.9619 3.14032 17.5848 3.30667V4.05333C17.9505 3.84762 18.3238 3.73333 18.6819 3.73333ZM21.9733 5.39429C22.5295 5.39429 22.9181 5.7219 22.9181 6.14857C22.9181 6.59809 22.5295 6.91048 21.9733 6.91048C21.6381 6.91048 21.2876 6.80381 20.9295 6.58286V7.36762C21.3029 7.53524 21.6838 7.61905 22.0571 7.61905C22.2552 7.61905 22.4381 7.58857 22.6133 7.54286C23.0095 6.89524 23.2381 6.14857 23.2381 5.34857L23.2229 5.02857C22.9396 4.86089 22.6148 4.7764 22.2857 4.78476C22.1486 4.78476 22.0038 4.79238 21.8514 4.81524V3.82476H22.9486C22.8534 3.58089 22.7361 3.34626 22.5981 3.12381H21.059V5.52381C21.3638 5.44762 21.6686 5.39429 21.9733 5.39429Z" fill="#565656" />
                                                </svg>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                        <div className="LinkPhoneAnimation__field" data-js-target-list="LinkPhoneAnimation.additionalFields">
                                          <div className="LinkPhoneAnimation__fieldLabel">
                                            {"Shipping address"}
                                          </div>
                                          <div className="LinkPhoneAnimation__fieldSet">
                                            <div className="LinkPhoneAnimation__fieldSelect LinkPhoneAnimation__fieldInput">
                                              {" United States "}
                                              <svg className="LinkPhoneAnimation__fieldSelectArrow" width="12" height="7" viewBox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fillRule="evenodd" clipRule="evenodd" d="M10.1934 0.866846C10.4866 0.573682 10.9619 0.573682 11.255 0.866846C11.5482 1.16001 11.5482 1.63532 11.255 1.92849L6.53023 6.65328C6.23734 6.94618 5.76247 6.94618 5.46957 6.65328L0.744776 1.92849C0.451611 1.63532 0.451611 1.16001 0.744776 0.866846C1.03794 0.573682 1.51325 0.573682 1.80642 0.866846L5.9999 5.06033L10.1934 0.866846Z" />
                                              </svg>
                                            </div>
                                            <div className="LinkPhoneAnimation__fieldInput">
                                              <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                {"Name"}
                                              </span>
                                            </div>
                                            <div className="LinkPhoneAnimation__fieldInput">
                                              <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                {"Address line 1"}
                                              </span>
                                            </div>
                                            <div className="LinkPhoneAnimation__fieldInput">
                                              <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                {"Address line 2 (optional)"}
                                              </span>
                                            </div>
                                            <div className="LinkPhoneAnimation__fieldInputRow">
                                              <div className="LinkPhoneAnimation__fieldInput">
                                                <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                  {"City"}
                                                </span>
                                              </div>
                                              <div className="LinkPhoneAnimation__fieldInput">
                                                <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                  {"ZIP"}
                                                </span>
                                              </div>
                                            </div>
                                            <div className="LinkPhoneAnimation__fieldSelect LinkPhoneAnimation__fieldInput">
                                              <span className="LinkPhoneAnimation__fieldPlaceholder">
                                                {"State"}
                                              </span>
                                              {" "}
                                              <svg className="LinkPhoneAnimation__fieldSelectArrow" width="12" height="7" viewBox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fillRule="evenodd" clipRule="evenodd" d="M10.1934 0.866846C10.4866 0.573682 10.9619 0.573682 11.255 0.866846C11.5482 1.16001 11.5482 1.63532 11.255 1.92849L6.53023 6.65328C6.23734 6.94618 5.76247 6.94618 5.46957 6.65328L0.744776 1.92849C0.451611 1.63532 0.451611 1.16001 0.744776 0.866846C1.03794 0.573682 1.51325 0.573682 1.80642 0.866846L5.9999 5.06033L10.1934 0.866846Z" />
                                              </svg>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="LinkPhoneAnimation__checkout" data-js-target="LinkPhoneAnimation.checkout">
                                        <div className="LinkPhoneAnimation__panel">
                                          <div className="LinkPhoneAnimation__panelField">
                                            <div className="LinkPhoneAnimation__panelFieldLabel"></div>
                                            <div className="LinkPhoneAnimation__panelFieldValue" data-js-target="LinkPhoneAnimation.panelEmail">
                                              <b>
                                                {"jane.diaz@example.com"}
                                              </b>
                                            </div>
                                          </div>
                                          <div className="LinkPhoneAnimation__panelPromptContainer">
                                            <div className="LinkPhoneAnimation__panelPrompt" data-js-target="LinkPhoneAnimation.panelPrompt">
                                              <div className="LinkPhoneAnimation__panelFieldContent">
                                                <div className="LinkPhoneAnimation__panelFieldTitle">
                                                  {" Use your saved information with Link "}
                                                </div>
                                                <div className="LinkPhoneAnimation__panelFieldBody">
                                                  {" Enter the code sent to "}
                                                  <b>
                                                    {"(•••) ••• ••35"}
                                                  </b>
                                                  {" to securely use your saved information. "}
                                                </div>
                                              </div>
                                              <div className="LinkPhoneAnimation__panelSmsContainer">
                                                <div className="LinkPhoneAnimation__panelSmsField">
                                                  <svg width="17" height="20" viewBox="0 0 17 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path opacity="0.3" fillRule="evenodd" clipRule="evenodd" d="M6.32362 4.58253C6.22847 4.58696 6.13968 4.59246 6.05602 4.5993C5.65388 4.63215 5.47953 4.68961 5.37496 4.7429C5.06666 4.89998 4.816 5.15064 4.65891 5.45894C4.60563 5.56351 4.54817 5.73786 4.51531 6.14001C4.48128 6.55649 4.48033 7.1 4.48033 7.92321V15.1325C4.48033 15.9557 4.48128 16.4992 4.51531 16.9157C4.54817 17.3179 4.60563 17.4922 4.65891 17.5968C4.816 17.9051 5.06666 18.1558 5.37496 18.3128C5.47953 18.3661 5.65388 18.4236 6.05602 18.4564C6.47251 18.4905 7.01601 18.4914 7.83922 18.4914H8.90423C9.72744 18.4914 10.2709 18.4905 10.6874 18.4564C11.0896 18.4236 11.2639 18.3661 11.3685 18.3128C11.6768 18.1558 11.9275 17.9051 12.0845 17.5968C12.1378 17.4922 12.1953 17.3179 12.2281 16.9157C12.2622 16.4992 12.2631 15.9557 12.2631 15.1325V7.9232C12.2631 7.09999 12.2622 6.55649 12.2281 6.14001C12.1953 5.73786 12.1378 5.56351 12.0845 5.45894C11.9275 5.15064 11.6768 4.89998 11.3685 4.7429C11.2639 4.68961 11.0896 4.63215 10.6874 4.5993C10.6038 4.59246 10.515 4.58696 10.4198 4.58253V5.07634C10.4198 5.52879 10.053 5.89558 9.60059 5.89558H7.14286C6.69041 5.89558 6.32362 5.52879 6.32362 5.07634V4.58253ZM3.25146 7.92321C3.25146 6.31734 3.25146 5.51441 3.56399 4.90105C3.83889 4.36152 4.27754 3.92287 4.81706 3.64797C5.43042 3.33545 6.23336 3.33545 7.83922 3.33545H8.90424C10.5101 3.33545 11.313 3.33545 11.9264 3.64797C12.4659 3.92287 12.9046 4.36152 13.1795 4.90105C13.492 5.51441 13.492 6.31734 13.492 7.9232V15.1325C13.492 16.7384 13.492 17.5413 13.1795 18.1547C12.9046 18.6942 12.4659 19.1329 11.9264 19.4078C11.313 19.7203 10.5101 19.7203 8.90423 19.7203H7.83922C6.23335 19.7203 5.43042 19.7203 4.81706 19.4078C4.27754 19.1329 3.83889 18.6942 3.56399 18.1547C3.25146 17.5413 3.25146 16.7384 3.25146 15.1325V7.92321Z" fill="black" />
                                                    <rect opacity="0.2" x="6.73315" y="16.4434" width="3.27697" height="0.819242" rx="0.409621" fill="black" />
                                                    <circle cx="12.4677" cy="4.1545" r="3.27697" fill="#bebebe" stroke="white" strokeWidth="1.63848" />
                                                  </svg>
                                                  <div className="LinkPhoneAnimation__panelSmsInput" data-js-target-list="LinkPhoneAnimation.smsInputs"></div>
                                                  <div className="LinkPhoneAnimation__panelSmsInput" data-js-target-list="LinkPhoneAnimation.smsInputs"></div>
                                                  <div className="LinkPhoneAnimation__panelSmsInput" data-js-target-list="LinkPhoneAnimation.smsInputs"></div>
                                                  <div className="LinkPhoneAnimation__panelSmsInput" data-js-target-list="LinkPhoneAnimation.smsInputs"></div>
                                                  <div className="LinkPhoneAnimation__panelSmsInput" data-js-target-list="LinkPhoneAnimation.smsInputs"></div>
                                                  <div className="LinkPhoneAnimation__panelSmsInput" data-js-target-list="LinkPhoneAnimation.smsInputs"></div>
                                                  <svg className="LinkPhoneAnimation__panelSmsCheck" data-js-target="LinkPhoneAnimation.smsCheck" width="14" height="10" viewBox="0 0 14 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path fillRule="evenodd" clipRule="evenodd" d="M5.10551 9.12915L1.00558 5.06695C0.685642 4.74434 0.685642 4.22129 1.00558 3.89868C1.32551 3.57608 1.84422 3.57608 2.16416 3.89868L5.68163 7.3599L12.4717 0.594495C12.7916 0.271887 13.3103 0.271887 13.6303 0.594495C13.9502 0.917104 13.9502 1.44016 13.6303 1.76276L6.25406 9.12536C5.93633 9.44234 5.42529 9.44402 5.10551 9.12915Z" fill="#bebebe" />
                                                  </svg>
                                                </div>
                                                <div className="LinkPhoneAnimation__panelLink">
                                                  {" Resend code "}
                                                </div>
                                              </div>
                                            </div>
                                            <div className="LinkPhoneAnimation__panelFieldSet">
                                              <div className="LinkPhoneAnimation__panelField LinkPhoneAnimation__panelField--isExpanded">
                                                <div className="LinkPhoneAnimation__panelFieldLabel">
                                                  {"Ship to"}
                                                </div>
                                                <div className="LinkPhoneAnimation__panelFieldValue LinkPhoneAnimation__panelFieldValue--hasChange">
                                                  {" Jane Diaz "}
                                                  <div className="LinkPhoneAnimation__panelLink">
                                                    {"Change"}
                                                  </div>
                                                  <div className="LinkPhoneAnimation__panelFieldSubvalue">
                                                    {" 27 Fredrick Ave"}
                                                    <br />
                                                    {" Brothers, OR 97712"}
                                                    <br />
                                                    {" United States "}
                                                  </div>
                                                </div>
                                              </div>
                                              <div className="LinkPhoneAnimation__panelField">
                                                <div className="LinkPhoneAnimation__panelFieldLabel">
                                                  {"Pay with"}
                                                </div>
                                                <div className="LinkPhoneAnimation__panelFieldValue LinkPhoneAnimation__panelFieldValue--hasChange">
                                                  <div className="LinkPhoneAnimation__panelFieldCard">
                                                    <svg width="21" height="14" viewBox="0 0 21 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                      <path d="M18.6937 0.769043H2.38596C1.46222 0.769043 0.713379 1.52594 0.713379 2.45961V12.1804C0.713379 13.1141 1.46222 13.871 2.38596 13.871H18.6937C19.6174 13.871 20.3662 13.1141 20.3662 12.1804V2.45961C20.3662 1.52594 19.6174 0.769043 18.6937 0.769043Z" fill="white" />
                                                      <path d="M2.38596 0.97376H18.6937C19.5023 0.97376 20.1615 1.63693 20.1615 2.45961V12.1804C20.1615 13.0031 19.5023 13.6662 18.6937 13.6662H2.38596C1.57734 13.6662 0.918096 13.0031 0.918096 12.1804V2.45961C0.918096 1.63693 1.57734 0.97376 2.38596 0.97376Z" stroke="black" strokeOpacity="0.2" strokeWidth="0.409435" />
                                                      <path d="M2.83589 5.55714C2.39839 5.3146 1.89908 5.11954 1.34082 4.98417L1.36424 4.87875H3.65315C3.9634 4.88974 4.21515 4.98409 4.29707 5.31731L4.79451 7.71443L4.9469 8.43642L6.34015 4.87875H7.84449L5.60832 10.0905H4.1039L2.83589 5.55714ZM8.95106 10.096H7.5284L8.41823 4.87875H9.84081L8.95106 10.096ZM14.1083 5.0063L13.9148 6.1329L13.7862 6.0775C13.5287 5.97201 13.1889 5.8666 12.7264 5.87774C12.1647 5.87774 11.9128 6.10517 11.907 6.32721C11.907 6.57146 12.2117 6.73243 12.7093 6.97114C13.529 7.34301 13.9092 7.7981 13.9035 8.39201C13.892 9.47436 12.9201 10.1738 11.4274 10.1738C10.7891 10.1682 10.1744 10.0402 9.84073 9.89609L10.0398 8.72493L10.2271 8.80829C10.6896 9.00275 10.994 9.08581 11.562 9.08581C11.9716 9.08581 12.4107 8.9247 12.4163 8.57518C12.4163 8.3476 12.2292 8.18096 11.6788 7.92564C11.1403 7.67579 10.4203 7.25958 10.432 6.51023C10.4381 5.49458 11.4274 4.78418 12.8323 4.78418C13.3826 4.78418 13.8277 4.90074 14.1083 5.0063ZM15.9991 8.24772H17.1816C17.1231 7.98687 16.8537 6.73803 16.8537 6.73803L16.7543 6.28848C16.6841 6.48272 16.5612 6.79911 16.5671 6.78797C16.5671 6.78797 16.1163 7.948 15.9991 8.24772ZM17.7552 4.87875L18.903 10.0959H17.5857C17.5857 10.0959 17.4568 9.49649 17.416 9.31332H15.5894C15.5366 9.452 15.2908 10.0959 15.2908 10.0959H13.7981L15.9112 5.31163C16.0576 4.97303 16.3155 4.87875 16.6548 4.87875H17.7552Z" fill="#727272" />
                                                    </svg>
                                                    {" •••• 9328 "}
                                                  </div>
                                                  <div className="LinkPhoneAnimation__panelLink">
                                                    {"Change"}
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                          <div className="LinkPhoneAnimation__panelFooter">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="10" fill="none" viewBox="0 0 60 20" className="LinkPhoneAnimation__panelFooterLogo">
                                              <path fill="#b5b5b5" d="M9.999 20c5.523 0 10-4.477 10-10s-4.477-10-10-10-10 4.477-10 10 4.477 10 10 10Z" />
                                              <path fill="#171717" d="M9.536 4.001H6.452c.602 2.508 2.351 4.655 4.545 6.001-2.196 1.347-3.943 3.493-4.545 6.001h3.084c.762-2.32 2.88-4.134 5.48-4.545V8.55c-2.599-.411-4.716-2.228-5.48-4.548v-.002ZM42.121 6.16c2.617 0 4.057 1.584 4.057 4.8v7.445h-3.025v-6.698c0-1.896-.72-2.688-2.305-2.688-1.585 0-2.641 1.199-2.641 3.335v6.05h-3.024V6.398h3.024V7.96c.792-1.104 2.042-1.8 3.914-1.8Zm-9.267 12.244H29.83V6.401h3.025v12.003Zm-5.354-.002h-3V1.6h3v16.802Zm24.03-7.825c1.99-.647 3.792-2.16 4.584-4.178h3.02c-.61 2.11-2.16 4.196-4.436 5.594 2.42 1.48 4.166 3.866 4.631 6.41h-3.046c-.623-2.425-2.449-4.416-4.754-4.994v4.993h-3.024V1.6h3.024v8.977ZM31.34 1.36c.936 0 1.728.77 1.728 1.704 0 .936-.768 1.728-1.727 1.728a1.722 1.722 0 0 1-1.728-1.728c0-.935.793-1.704 1.728-1.704Z" />
                                            </svg>
                                            <div className="LinkPhoneAnimation__panelFooterSecure">
                                              <svg width="8" height="9" viewBox="0 0 8 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fillRule="evenodd" clipRule="evenodd" d="M1.29614 3.67085V2.64813C1.29614 1.97002 1.55953 1.31968 2.02838 0.840183C2.49722 0.360687 3.1331 0.0913086 3.79614 0.0913086C4.45918 0.0913086 5.09507 0.360687 5.56391 0.840183C6.03275 1.31968 6.29614 1.97002 6.29614 2.64813V3.67085H6.54614C6.67875 3.67085 6.80593 3.72473 6.8997 3.82063C6.99346 3.91653 7.04614 4.0466 7.04614 4.18222V7.2504C7.04614 7.52164 6.94079 7.78178 6.75325 7.97358C6.56571 8.16538 6.31136 8.27313 6.04614 8.27313H1.54614C1.28093 8.27313 1.02657 8.16538 0.839036 7.97358C0.651499 7.78178 0.546143 7.52164 0.546143 7.2504V4.18222C0.546143 4.0466 0.598821 3.91653 0.692589 3.82063C0.786357 3.72473 0.913534 3.67085 1.04614 3.67085H1.29614ZM3.79614 4.94926C3.66353 4.94926 3.53636 5.00314 3.44259 5.09904C3.34882 5.19494 3.29614 5.32501 3.29614 5.46063V6.48335C3.29614 6.61898 3.34882 6.74904 3.44259 6.84494C3.53636 6.94084 3.66353 6.99472 3.79614 6.99472C3.92875 6.99472 4.05593 6.94084 4.1497 6.84494C4.24346 6.74904 4.29614 6.61898 4.29614 6.48335V5.46063C4.29614 5.32501 4.24346 5.19494 4.1497 5.09904C4.05593 5.00314 3.92875 4.94926 3.79614 4.94926ZM5.29614 3.67085V2.64813C5.29614 2.24126 5.13811 1.85106 4.8568 1.56336C4.5755 1.27566 4.19397 1.11404 3.79614 1.11404C3.39832 1.11404 3.01679 1.27566 2.73548 1.56336C2.45418 1.85106 2.29614 2.24126 2.29614 2.64813V3.67085H5.29614Z" fill="#ababab" />
                                              </svg>
                                              {" Safe and secure "}
                                            </div>
                                          </div>
                                        </div>
                                        <div className="LinkPhoneAnimation__buttonContainer">
                                          <div className="LinkPhoneAnimation__button LinkPhoneAnimation__button--isDisabled">
                                            <span>
                                              {"Pay"}
                                            </span>
                                          </div>
                                          <div className="LinkPhoneAnimation__button LinkPhoneAnimation__button--isActive" data-js-target="LinkPhoneAnimation.button">
                                            <span data-js-target="LinkPhoneAnimation.buttonText">
                                              {"Pay"}
                                            </span>
                                            {" "}
                                            <svg className="Spinner LinkPhoneAnimation__buttonSpinner" data-js-target="LinkPhoneAnimation.buttonSpinner" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
                                              <g className="Spinner__circle" fill="none" fillRule="evenodd">
                                                <circle cx="8" cy="8" r="8" />
                                                <path fill="currentColor" fillRule="nonzero" d="M8 16a.62.62 0 1 1 0-1.24A6.76 6.76 0 1 0 2.76 3.71a.62.62 0 1 1-.96-.77A7.99 7.99 0 0 1 16 8a8 8 0 0 1-8 8z" />
                                              </g>
                                            </svg>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                    <div className="LinkPhoneAnimation__notificationContainer">
                                      <div className="LinkPhoneAnimation__notification" data-js-target="LinkPhoneAnimation.notification">
                                        <div className="LinkPhoneAnimation__notificationIcon">
                                          <svg width="15" height="14" viewBox="0 0 15 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M7.5 13C11.6421 13 15 10.0899 15 6.5C15 2.91015 11.6421 0 7.5 0C3.35786 0 0 2.91015 0 6.5C0 10.0899 3.35786 13 7.5 13Z" fill="#ffffff" />
                                            <path d="M3.44036 11C3.60517 11.4009 3.49691 11.954 3.11557 12.6592C2.73424 13.3644 2.36238 13.8113 2 14C3.05752 13.7494 3.91081 13.4588 4.55989 13.1284C5.20897 12.798 5.689 12.4228 6 12.0027L3.44036 11Z" fill="#ffffff" />
                                          </svg>
                                        </div>
                                        <div className="LinkPhoneAnimation__notificationTitle">
                                          {"Messages"}
                                        </div>
                                        <div className="LinkPhoneAnimation__notificationBody">
                                          {"Your verification code is: 424242"}
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div className="LinkPhoneAnimation__successScreen" data-js-target="LinkPhoneAnimation.successScreen">
                                  <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path className="LinkPhoneAnimation__successCheck" data-js-target="LinkPhoneAnimation.successCheck" d="M28.3544 14.7715L17.1652 25.4396L11.9419 20.4842" stroke="var(--animationCheckColor, #bebebe)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                    <path d="M20.1479 38.5697C30.5719 38.5697 39.0223 30.1193 39.0223 19.6952C39.0223 9.27118 30.5719 0.820801 20.1479 0.820801C9.72381 0.820801 1.27344 9.27118 1.27344 19.6952C1.27344 30.1193 9.72381 38.5697 20.1479 38.5697Z" stroke="var(--animationCheckColor, #bebebe)" strokeWidth="1.64126" />
                                  </svg>
                                  <div className="LinkPhoneAnimation__successTitle">
                                    {"Payment successful"}
                                  </div>
                                  <div className="LinkPhoneAnimation__successPrice">
                                    {"$42.08"}
                                  </div>
                                  <div className="LinkPhoneAnimation__successBody">
                                    {"The payment will appear on your statement as “P Skincare”."}
                                  </div>
                                  <div className="LinkPhoneAnimation__successLink" data-js-target="LinkPhoneAnimation.replayLink">
                                    {"Back to home"}
                                  </div>
                                </div>
                              </div>
                            </figure>
                          </div>
                        </div>
                      </figure>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
