/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S03HowItWorks() {
  return (
    <section className="Section theme--White Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section">
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"How it works"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Link customer experience "}
                    </h1>
                  </header>
                  <div className="Copy__body">
                    <p>
                      {"Link autofills your customers’ saved information in a few simple steps across any device and browser and in supported AI agents. Your customers’ data is encrypted to keep it secure and, as a certified PCI Service Provider Level 1, Link meets the highest level of certification available in the payments industry."}
                    </p>
                  </div>
                </section>
                <section className="StackedCarousel" data-js-controller="StackedCarousel" style={{ "--stackedCarouselItemCount": "3" }}>
                  <div data-js-controller="StackedCarouselControl">
                    <div className="StackedCarouselControl__itemList" data-js-target="StackedCarouselControl.items">
                      <div className="StackedCarousel__detailContainer StackedCarousel__detailContainer--isActive" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 1 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Save payment info"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Customers choose to save their payment information at check out. "}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer StackedCarousel__imageContainer--isActive" data-js-target-list="StackedCarouselControl.images">
                        <div className="Card Card--shadowXLarge">
                          <picture className="Picture Picture--autosize">
                            <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/Link-HowItWorks-01-SavePaymentInfo-LinkUpdate-6ff89ce98a.webp 2x,\n            /sites/stripe-com-9ababc9a/products/Link-HowItWorks-01-SavePaymentInfo-LinkUpdate-8752a9af71.webp\n          "} type="image/webp" />
                            <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/Link-HowItWorks-01-SavePaymentInfo-LinkUpdate-2fde18c5a9.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/Link-HowItWorks-01-SavePaymentInfo-LinkUpdate-2fde18c5a9.png 2x,\n          /sites/stripe-com-9ababc9a/products/Link-HowItWorks-01-SavePaymentInfo-LinkUpdate-8b666f298e.png\n        "} alt="" width="1080" height="980" loading="lazy" />
                          </picture>
                        </div>
                      </div>
                      <div className="StackedCarousel__detailContainer" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 2 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Account verification"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"When customers use Link on a new site or new device, they’ll receive a one-time code via SMS to verify their identity and keep their payment information secure. "}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer" data-js-target-list="StackedCarouselControl.images">
                        <div className="Card Card--shadowXLarge">
                          <picture className="Picture Picture--autosize">
                            <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/Account-verification-en-US-f776d924f7.svg" alt="" width="540" height="490" loading="lazy" />
                          </picture>
                        </div>
                      </div>
                      <div className="StackedCarousel__detailContainer" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 3 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Check out faster"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Link instantly populates customers’ saved payment details when they enter their email address, allowing them to check out quickly on any Link-supported site. "}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer" data-js-target-list="StackedCarouselControl.images">
                        <div className="Card Card--shadowXLarge">
                          <picture className="Picture Picture--autosize">
                            <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/Check-out-faster-en-US-86f78e3512.svg" alt="" width="540" height="490" loading="lazy" />
                          </picture>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
