/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S08Pricing() {
  return (
    <section className="Section theme--Light Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section" style={{ "--footerGap": "var(--rowGapXLarge)", "--footerPaddingLeft": "var(--columnPaddingNone)", "--footerPaddingRight": "var(--columnPaddingNone)" }}>
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"Pricing"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Simple, transparent pricing "}
                    </h1>
                  </header>
                  <footer className="Copy__footer">
                    <section className="PricingGrid PricingGrid--hasBody">
                      <div className="StickyNav PricingGrid__header" data-js-controller="StickyNav">
                        <header className="PricingGridHeader">
                          <div className="PricingGridHeader__titleContainer">
                            <div className="AnimatedIcon PricingIcon">
                              <div className="AnimatedIcon__iconContainer">
                                <svg className="AnimatedIcon__icon" width="96" height="96" preserveAspectRatio="xMinYMin" viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg" data-js-controller="PricingIcon">
                                  <defs>
                                    <path id="pricingIconTag" d="M41.4 30.38l8.4 8.27A4 4 0 0 1 51 41.5V62a3 3 0 0 1-3 3H32a3 3 0 0 1-3-3V41.5a4 4 0 0 1 1.2-2.85l8.4-8.27a2 2 0 0 1 2.8 0zM40 36a3 3 0 1 0 0 6 3 3 0 0 0 0-6z" />
                                    <clipPath id="pricingClipPath">
                                      <use href="#pricingIconTag" style={{ transformOrigin: "40px 39px", transform: "rotate(45deg)" }} data-js-target-list="PricingIcon.tagBacks" />
                                    </clipPath>
                                  </defs>
                                  <use href="#pricingIconTag" fill="var(--blendBackground)" style={{ transformOrigin: "40px 39px", transform: "rotate(45deg)" }} data-js-target-list="PricingIcon.tagBacks" />
                                  <use className="PricingIcon__tag" href="#pricingIconTag" fill="var(--blendForeground)" style={{ transformOrigin: "40px 39px" }} data-js-target-list="PricingIcon.tagFronts" />
                                  <g clipPath="url(#pricingClipPath)">
                                    <use className="PricingIcon__tag" href="#pricingIconTag" fill="var(--blendIntersection)" style={{ transformOrigin: "40px 39px" }} data-js-target-list="PricingIcon.tagFronts" />
                                  </g>
                                </svg>
                              </div>
                            </div>
                            <h1 className="PricingGridHeader__title">
                              {"Pricing*"}
                            </h1>
                          </div>
                          <div className="PricingGridHeader__body"></div>
                        </header>
                      </div>
                      <div className="PricingGrid__body">
                        <section className="PricingGridRow">
                          <div className="PricingGridRow__content">
                            <div className="PricingGridRow__body">
                              <h1 id="cards">
                                {"Cards"}
                              </h1>
                              <p>
                                {"Accept widely used credit and debit cards."}
                              </p>
                            </div>
                          </div>
                          <div className="PricingGridRow__priceContainer">
                            <div className="PricingGridRow__priceList">
                              <section className="PricingGridPrice">
                                <strong className="PricingGridPrice__amount">
                                  <span className="Price">
                                    {" 2.9% + 30¢ "}
                                  </span>
                                </strong>
                                {" "}
                                <span className="PricingGridPrice__label">
                                  <p>
                                    {"per successful transaction"}
                                  </p>
                                </span>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      <span className="Price">
                                        {" +1.5% "}
                                      </span>
                                      <p>
                                        {"for international transactions"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      <span className="Price">
                                        {" +1% "}
                                      </span>
                                      <p>
                                        {"if currency conversion is required"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                              </section>
                            </div>
                          </div>
                        </section>
                        <section className="PricingGridRow">
                          <div className="PricingGridRow__content">
                            <div className="PricingGridRow__body">
                              <h1 id="stablecoins">
                                {"Stablecoins"}
                              </h1>
                              <p>
                                {"Reach more global customers, reduce costs, and minimize cross-border exchange fees by offering stablecoins."}
                              </p>
                            </div>
                          </div>
                          <div className="PricingGridRow__priceContainer">
                            <div className="PricingGridRow__priceList">
                              <section className="PricingGridPrice">
                                <strong className="PricingGridPrice__amount">
                                  <span className="Price">
                                    {" 0.8% "}
                                  </span>
                                </strong>
                                {" "}
                                <span className="PricingGridPrice__label">
                                  <p>
                                    {"per successful transaction"}
                                  </p>
                                </span>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      {" Promotional rate through January 1, 2027; "}
                                      <span className="Price">
                                        {" +0.2% "}
                                      </span>
                                      <p>
                                        {"thereafter"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                              </section>
                            </div>
                          </div>
                        </section>
                        <section className="PricingGridRow">
                          <div className="PricingGridRow__content">
                            <div className="PricingGridRow__body">
                              <h1 id="pix-and-upi">
                                {"Pix and UPI"}
                              </h1>
                              <p>
                                {"Convert buyers globally by offering the payment methods they prefer in their market."}
                              </p>
                            </div>
                          </div>
                          <div className="PricingGridRow__priceContainer">
                            <div className="PricingGridRow__priceList">
                              <section className="PricingGridPrice">
                                <strong className="PricingGridPrice__amount">
                                  <span className="Price">
                                    {" 1.8% + 30¢ "}
                                  </span>
                                </strong>
                                {" "}
                                <span className="PricingGridPrice__label">
                                  <p>
                                    {"per successful transaction"}
                                  </p>
                                </span>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      <span className="Price">
                                        {" +1.5% "}
                                      </span>
                                      <p>
                                        {"for international transactions"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      <span className="Price">
                                        {" +1% "}
                                      </span>
                                      <p>
                                        {"if currency conversion is required"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                              </section>
                            </div>
                          </div>
                        </section>
                        <section className="PricingGridRow">
                          <div className="PricingGridRow__content">
                            <div className="PricingGridRow__body">
                              <h1 id="instant-bank-payments">
                                {"Instant bank payments"}
                              </h1>
                              <p>
                                {"Reduce processing costs with frictionless bank payments with the confirmation speed of cards."}
                              </p>
                            </div>
                          </div>
                          <div className="PricingGridRow__priceContainer">
                            <div className="PricingGridRow__priceList">
                              <section className="PricingGridPrice">
                                <strong className="PricingGridPrice__amount">
                                  <span className="Price">
                                    {" 2.6% + 30¢ "}
                                  </span>
                                </strong>
                                {" "}
                                <span className="PricingGridPrice__label">
                                  <p>
                                    {"per successful transaction"}
                                  </p>
                                </span>
                              </section>
                            </div>
                          </div>
                        </section>
                        <section className="PricingGridRow">
                          <div className="PricingGridRow__content">
                            <div className="PricingGridRow__body">
                              <h1 id="klarna">
                                {"Klarna"}
                              </h1>
                              <p>
                                {"Offer flexible buy now, pay later options to reach new buyers."}
                              </p>
                            </div>
                          </div>
                          <div className="PricingGridRow__priceContainer">
                            <div className="PricingGridRow__priceList">
                              <section className="PricingGridPrice">
                                <strong className="PricingGridPrice__amount">
                                  <span className="Price">
                                    {" 5.99% + 30¢ "}
                                  </span>
                                </strong>
                                {" "}
                                <span className="PricingGridPrice__label">
                                  <p>
                                    {"per successful transaction"}
                                  </p>
                                </span>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      <span className="Price">
                                        {" +1.5% "}
                                      </span>
                                      <p>
                                        {"for international transactions"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                                <div className="PricingGridSubprice">
                                  <span className="PricingGridSubprice__label">
                                    <span className="PricingGridSubprice__text">
                                      <span className="Price">
                                        {" +1% "}
                                      </span>
                                      <p>
                                        {"if currency conversion is required"}
                                      </p>
                                    </span>
                                  </span>
                                </div>
                              </section>
                            </div>
                          </div>
                        </section>
                      </div>
                    </section>
                    <section className="PricingGrid PricingGrid--hasNoBody">
                      <div className="StickyNav PricingGrid__header" data-js-controller="StickyNav">
                        <header className="PricingGridHeader">
                          <div className="PricingGridHeader__titleContainer">
                            <div className="AnimatedIcon GearsIcon">
                              <div className="AnimatedIcon__iconContainer">
                                <svg className="AnimatedIcon__icon" width="96" height="96" preserveAspectRatio="xMinYMin" viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg" data-js-controller="GearsIcon">
                                  <defs>
                                    <path id="gearsIconSmall" d="M29.5 28l1.13 3.13.64.13 2.24-2.46.93.38-.16 3.33c.19.11.37.23.54.36l3.02-1.42.7.71-1.41 3.02c.13.17.25.35.36.54l3.33-.16.38.93-2.46 2.24c.05.21.1.42.13.64L42 40.5v1l-3.13 1.13c-.04.25-.1.5-.15.73l2.48 2.15-.38.93-3.28-.24c-.14.24-.3.47-.47.7l1.48 2.94-.71.7-2.94-1.47c-.23.17-.46.33-.7.47l.24 3.28-.93.38-2.15-2.48c-.27.06-.54.12-.82.16L29.5 54h-1l-1.04-3.12c-.28-.04-.55-.1-.82-.16l-2.15 2.48-.93-.38.24-3.28c-.24-.14-.47-.3-.7-.47l-2.94 1.48-.7-.71 1.47-2.94c-.17-.23-.33-.46-.47-.7l-3.28.24-.38-.93 2.48-2.15a9.95 9.95 0 0 1-.16-.82L16 41.5v-1l3.12-1.04c.04-.25.08-.49.14-.73l-2.46-2.24.38-.93 3.33.16c.11-.19.23-.37.36-.54l-1.42-3.02.71-.7 3.02 1.41c.17-.13.35-.25.54-.36l-.16-3.33.93-.38 2.24 2.46s.42-.1.64-.13L28.5 28h1zM29 39a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
                                    <path id="gearsIconLarge" d="M41.8 38l.88 3.12c.28.03.56.08.83.14l1.9-2.63 1.5.55-.24 3.22c.25.13.49.27.73.42L50.08 41l1.24 1.02-1.35 2.95c.19.2.37.42.54.64l3.16-.8.8 1.38-2.27 2.31c.1.26.2.52.28.79l3.24.32.28 1.57-2.94 1.4v.84l2.94 1.4-.28 1.57-3.24.32c-.08.27-.18.53-.28.79l2.27 2.3-.8 1.4-3.16-.81c-.17.22-.35.43-.54.64l1.35 2.95L50.08 65l-2.68-1.82c-.24.15-.48.29-.73.42l.25 3.22-1.52.55-1.9-2.63c-.26.06-.54.1-.82.14L41.8 68h-1.6l-.88-3.12a12.1 12.1 0 0 1-.83-.14l-1.9 2.63-1.5-.55.24-3.22c-.25-.13-.49-.27-.73-.42L31.92 65l-1.24-1.02 1.35-2.95c-.19-.2-.37-.42-.54-.64l-3.16.8-.8-1.38 2.27-2.31c-.1-.26-.2-.52-.28-.79l-3.24-.32-.28-1.57 2.94-1.4v-.84L26 51.18l.28-1.57 3.24-.32c.08-.27.18-.53.28-.79l-2.27-2.3.8-1.4 3.16.81c.17-.22.35-.43.54-.64l-1.35-2.95L31.92 41l2.68 1.82c.24-.15.48-.29.73-.42l-.25-3.22 1.52-.55 1.9 2.63c.26-.06.54-.1.82-.14L40.2 38h1.6zM41 50a3 3 0 0 0-3.02 3A3 3 0 0 0 41 56a3 3 0 0 0 3.02-3A3 3 0 0 0 41 50z" />
                                    <clipPath id="gearsIconClipPath">
                                      <use className="GearsIcon__gear--small" href="#gearsIconSmall" data-js-target-list="GearsIcon.smallGears" />
                                    </clipPath>
                                  </defs>
                                  <use className="GearsIcon__gear--small" href="#gearsIconSmall" fill="var(--blendBackground)" data-js-target-list="GearsIcon.smallGears" />
                                  <use className="GearsIcon__gear--large" href="#gearsIconLarge" fill="var(--blendForeground)" data-js-target-list="GearsIcon.largeGears" />
                                  <g clipPath="url(#gearsIconClipPath)">
                                    <use className="GearsIcon__gear--large" href="#gearsIconLarge" fill="var(--blendIntersection)" data-js-target-list="GearsIcon.largeGears" />
                                  </g>
                                </svg>
                              </div>
                            </div>
                            <h1 className="PricingGridHeader__title">
                              {"Custom pricing"}
                            </h1>
                          </div>
                          <div className="PricingGridHeader__body">
                            <p>
                              {"Custom pricing is available for companies with large payments volume, high-value transactions, or unique business models.** Contact our sales team to learn more."}
                            </p>
                          </div>
                          <div className="PricingGridHeader__ctaContainer">
                            <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/contact/sales" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="link_pricing_contact_sales">
                              {"Contact sales"}
                              <span className="nobr">
                                <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                  <g fillRule="evenodd">
                                    <path className="HoverArrow__linePath" d="M0 5h7" />
                                    <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                  </g>
                                </svg>
                              </span>
                            </a>
                          </div>
                        </header>
                      </div>
                    </section>
                  </footer>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
