/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S10LegalFooterSection() {
  return (
    <section className="Section LegalFooterSection theme--White Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="LegalFooterSection__content">
                <p>
                  {"*Companies on custom pricing for payments processing should contact sales about their Link pricing."}
                </p>
                <p>
                  {"**Stripe matches Link Payment Method rates to custom blended rates for cards. Businesses with custom blended rates for cards will have the same rate automatically applied to Link Payment Method transactions and disputes, unless the business also has a custom rate for Link Payment Method. Businesses with custom Klarna rates will have the same rate (including lost dispute fees) automatically applied to Klarna transactions accepted via Link."}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
