/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S00ProductHeroSection() {
  return (
    <section className="Section ProductHeroSection ProductHeroSection--contentAngledMarginBottomNone HeroSection HeroSection--bleed HeroSection--bleedNone HeroSection--hasGradient theme--Light Section--angleBottom Section--paddingNormal Section--hasGuides Section--hasStickyNav">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="HeroSection__gradient Gradient">
                <canvas className="Gradient__canvas" data-js-controller="Gradient" data-transition-in=""></canvas>
              </div>
              <div className="RowLayout ProductHeroSection__layout">
                <nav className="ProductNav" data-js-controller="ProductNav">
                  <header className="ProductNav__header">
                    <h1 className="ProductNav__title">
                      <a className="Link" href="/sigma" data-js-controller="AnalyticsButton" data-analytics-category="Navigation" data-analytics-action="Clicked" data-analytics-label="hero__top_nav__stripe_sigma">
                        {"Stripe Sigma"}
                      </a>
                    </h1>
                  </header>
                  <div className="HorizontalOverflowContainer" data-js-controller="HorizontalOverflowContainer" style={{ "--horizontalOverflowSpacing": "16px" }}>
                    <div className="HorizontalOverflowContainer__track" data-js-target="HorizontalOverflowContainer.track">
                      <div className="HorizontalOverflowContainer__items">
                        <ul className="ProductNav__linkList">
                          <li className="ProductNavItem ProductNavItem--isActive" data-js-target-list="ProductNav.items" data-js-active="">
                            <a className="Link" href="/sigma" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Sigma Overview Link">
                              {"Overview"}
                            </a>
                          </li>
                          <li className="ProductNavItem" data-js-target-list="ProductNav.items">
                            <a className="Link" href="https://stripe.com/sigma/pricing" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="product_nav_pricing">
                              {"Pricing"}
                            </a>
                          </li>
                          <li className="ProductNavItem" data-js-target-list="ProductNav.items">
                            <a className="Link" href="https://docs.stripe.com/stripe-data/how-sigma-works" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Sigma hero nav Docs link">
                              {"Docs"}
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </nav>
                <div className="RowLayout ProductHeroSection__content">
                  <div className="ColumnLayout" data-columns="3,1" data-columns-tablet="1">
                    <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapNormal)" }}>
                      <section className="Copy variant--Hero">
                        <header className="Copy__header">
                          <h1 className="Copy__title">
                            {" Gain deeper insights faster with Stripe Sigma "}
                          </h1>
                        </header>
                        <footer className="Copy__footer">
                          <div className="CtaGroup CtaGroup--inline Copy__ctaGroup">
                            <a className="CtaButton variant--Button CtaButton--arrow" href="https://dashboard.stripe.com/sigma/queries" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="Sigma_hero_button">
                              {"Try for free"}
                              <span className="nobr">
                                <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                  <g fillRule="evenodd">
                                    <path className="HoverArrow__linePath" d="M0 5h7" />
                                    <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                  </g>
                                </svg>
                              </span>
                            </a>
                            {" "}
                            <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/contact/sales" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="sigma_hero_link">
                              {"Contact sales"}
                              <span className="nobr">
                                <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                  <g fillRule="evenodd">
                                    <path className="HoverArrow__linePath" d="M0 5h7" />
                                    <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                  </g>
                                </svg>
                              </span>
                            </a>
                          </div>
                        </footer>
                      </section>
                    </div>
                  </div>
                  <div data-js-controller="Video" className="Video Video--playing Video--inCard Video--excludeControls" data-analytics-label="Sigma Hero Video">
                    <div className="Video__poster" aria-hidden="true">
                      <picture>
                        <source srcSet="/sites/stripe-com-9ababc9a/products/sigma-0bc03125f0.webp" type="image/webp" />
                        <source srcSet="/sites/stripe-com-9ababc9a/products/sigma-f122da88e6.jpg" type="image/jpg" />
                        <img className="Video__posterImage" src="/sites/stripe-com-9ababc9a/products/sigma-0bc03125f0.webp" width="2560" height="1440" loading="lazy" alt="" />
                      </picture>
                    </div>
                    <video data-js-target="Video.video" className="Video__video" controlsList="nodownload" crossOrigin="anonymous" preload="metadata" autoPlay muted loop playsInline>
                      <source type="video/mp4" src="/sites/stripe-com-9ababc9a/products/sigma-4fbff11ddb.mp4" />
                    </video>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
