/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S06EasytouseSchema() {
  return (
    <section className="Section Section--angleBoth Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="StripeSet StripeSet--TopRight StripeSet--layoutIntersecting" data-js-controller="StripeSet" aria-hidden="true">
                <div className="Stripe Stripe--accentNone Stripe--variantSolid Stripe--insetNormal Stripe--widthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes"></div>
                <div className="Stripe Stripe--accentNone Stripe--variantSolid Stripe--insetNone Stripe--widthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes"></div>
                <div className="Stripe Stripe--accentNone Stripe--variantIntersection Stripe--insetNormal Stripe--widthFull Stripe--intersectionInsetNone Stripe--intersectionWidthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes">
                  <div className="Stripe__intersection" data-js-target="StripeSet.intersection"></div>
                </div>
              </div>
              <div className="StripeSet StripeSet--BottomLeft StripeSet--layoutIntersecting" data-js-controller="StripeSet" aria-hidden="true" data-js-align="End">
                <div className="Stripe Stripe--accentNone Stripe--variantSolid Stripe--insetNone Stripe--widthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes"></div>
                <div className="Stripe Stripe--accentNone Stripe--variantSolid Stripe--insetNormal Stripe--widthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes"></div>
                <div className="Stripe Stripe--accentNone Stripe--variantIntersection Stripe--insetNone Stripe--widthFull Stripe--intersectionInsetNormal Stripe--intersectionWidthFull" aria-hidden="true" data-js-target-list="StripeSet.stripes">
                  <div className="Stripe__intersection" data-js-target="StripeSet.intersection"></div>
                </div>
              </div>
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div className="ColumnLayout ColumnLayout--alignTop" data-columns="2,2">
                  <div className="RowLayout SideBySide__leftRowLayout">
                    <section className="Copy variant--Section">
                      <header className="Copy__header">
                        <h2 className="Copy__caption">
                          {"Easy-to-use schema"}
                        </h2>
                        <h1 className="Copy__title">
                          {" Stripe data, at the ready "}
                        </h1>
                      </header>
                      <div className="Copy__body">
                        <p>
                          {"Quick sidebar access to a full map of the structure of your data stored in Stripe (including any "}
                          <a className="Link" href="https://stripe.com/docs/payments/charges-api#storing-information-in-metadata" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="Related content">
                            {"additional metadata"}
                          </a>
                          {" you send us) makes it easy to combine all the relevant data needed from across Stripe’s products—payments, payouts, customers, subscriptions, refunds, and more."}
                        </p>
                      </div>
                    </section>
                  </div>
                  <div className="RowLayout SideBySide__rightRowLayout">
                    <div className="SigmaSchemaTable">
                      <div className="Card Card--shadowLarge Card--hasShadowMargin">
                        <div className="SigmaSchemaTable__mask">
                          <div className="SigmaSchemaTable__search">
                            <div className="GraphicFormField">
                              <div className="GraphicFormField__content">
                                <div className="GraphicFormFieldInput">
                                  <div className="GraphicFormFieldInput__icon">
                                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                      <path fillRule="evenodd" clipRule="evenodd" d="M9.53006 8.46938C9.50477 8.44409 9.47812 8.42098 9.45034 8.40005C10.1094 7.5226 10.5 6.43191 10.5 5.25C10.5 2.35051 8.1495 0 5.25 0C2.35051 0 0 2.35051 0 5.25C0 8.1495 2.35051 10.5 5.25 10.5C6.43192 10.5 7.52262 10.1094 8.40008 9.45033C8.421 9.4781 8.44411 9.50475 8.4694 9.53004L10.7199 11.7806C11.0128 12.0735 11.4877 12.0735 11.7806 11.7806C12.0735 11.4877 12.0735 11.0128 11.7806 10.7199L9.53006 8.46938ZM9 5.25C9 7.32107 7.32107 9 5.25 9C3.17893 9 1.5 7.32107 1.5 5.25C1.5 3.17893 3.17893 1.5 5.25 1.5C7.32107 1.5 9 3.17893 9 5.25Z" fill="var(--formFieldIconColor)" />
                                    </svg>
                                  </div>
                                  <div className="GraphicFormFieldInput__valueContainer">
                                    <span className="GraphicFormFieldInput__value"></span>
                                    {" "}
                                    <span className="GraphicFormFieldInput__placeholder">
                                      {"Search..."}
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="SigmaSchemaTable__list">
                            <div className="SigmaSchemaTable__listSection">
                              <h5 className="SigmaSchemaTable__sectionName">
                                {"Payment Tables"}
                              </h5>
                              <div className="SigmaSchemaTable__sectionItems">
                                <div className="SigmaSchemaTable__sectionItem">
                                  <h5 className="SigmaSchemaTable__itemName">
                                    {"balance_transactions_fee_details"}
                                  </h5>
                                </div>
                                <div className="SigmaSchemaTable__sectionItem">
                                  <h5 className="SigmaSchemaTable__itemName">
                                    {"balance_transactions"}
                                  </h5>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"id"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"amount"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Bigint"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"available_on"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Timestamp"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"created"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Timestamp"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"currency"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"description"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"fee"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Bigint"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"net"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Bigint"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"status"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"type"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"source_id"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                  <div className="SigmaSchemaTable__itemDetail">
                                    <span className="SigmaSchemaTable__detailName">
                                      {"automatic_transfer_id"}
                                    </span>
                                    {" "}
                                    <span className="SigmaSchemaTable__detailType">
                                      {"Varchar"}
                                    </span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="SigmaSchemaTable__caption">
                        <h1 className="CopyTitle CopyTitle--variantDetail SigmaSchemaTable__captionTitle">
                          {"Preview the "}
                          <a className="Link" href="https://dashboard.stripe.com/stripe-schema" data-js-controller="AnalyticsButton" data-analytics-category="Links" data-analytics-action="Clicked" data-analytics-label="stripe_data_at__full_schema">
                            {"full schema"}
                          </a>
                        </h1>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
