/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S01HowItWorks() {
  return (
    <section className="Section theme--White Section--angleTop Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section">
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"How it works"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Accept payments in minutes, without a line of code "}
                    </h1>
                  </header>
                </section>
                <section className="StackedCarousel" data-js-controller="StackedCarousel" style={{ "--stackedCarouselItemCount": "3" }}>
                  <div data-js-controller="StackedCarouselControl">
                    <div className="StackedCarouselControl__itemList" data-js-target="StackedCarouselControl.items">
                      <div className="StackedCarousel__detailContainer StackedCarousel__detailContainer--isActive" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 1 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Create a link"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"You can use payment links to sell a product or service, start a subscription, or collect a donation. Match the look and feel of your brand by adding your logo and colors."}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer StackedCarousel__imageContainer--hasImageShadow StackedCarousel__imageContainer--isActive" data-js-target-list="StackedCarouselControl.images">
                        <picture className="Picture Picture--autosize">
                          <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/payments_links_togethere-en-US-dee9aa42e8.svg" alt="" width="660" height="714" loading="lazy" />
                        </picture>
                      </div>
                      <div className="StackedCarousel__detailContainer" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 2 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Share the link"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Paste or embed the link anywhere. The same payment link can be shared with many customers and used across multiple channels."}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer StackedCarousel__imageContainer--hasImageShadow" data-js-target-list="StackedCarouselControl.images">
                        <picture className="Picture Picture--autosize">
                          <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/pl_share_en-us-b3993e95b5.svg" alt="" width="660" height="700" loading="lazy" />
                        </picture>
                      </div>
                      <div className="StackedCarousel__detailContainer" data-js-target-list="StackedCarouselControl.buttons">
                        <div className="NumberIcon StackedCarousel__icon">
                          <span className="NumberIcon__label">
                            {" 3 "}
                          </span>
                        </div>
                        <h1 className="CopyTitle CopyTitle--variantDetail StackedCarousel__copyTitle" style={{ "--titlePaddingRight": "var(--columnPaddingXLarge)" }}>
                          {"Get paid"}
                        </h1>
                        <div className="CopyBody CopyBody--variantDetail" style={{ "--bodyPaddingRight": "var(--columnPaddingXLarge)" }}>
                          <p>
                            {"Use the Dashboard or email to be notified of a successful payment, and have the funds deposited into your bank account."}
                          </p>
                        </div>
                      </div>
                      <div className="StackedCarousel__imageContainer StackedCarousel__imageContainer--hasImageShadow" data-js-target-list="StackedCarouselControl.images">
                        <picture className="Picture Picture--autosize">
                          <img className="Picture__image StackedCarousel__image" src="/sites/stripe-com-9ababc9a/products/pl_get-paid_en-us-2baf30b82f.svg" alt="" width="660" height="780" loading="lazy" />
                        </picture>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
