/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S02PaymentLinksConfigureSection() {
  return (
    <section className="Section PaymentLinksConfigure__section theme--Light flavor--Twilight accent--Purple Section--paddingNormal Section--hasGuides" data-js-controller="PaymentLinksConfigure">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <section className="Copy PaymentLinksConfigure__copy variant--Section" style={{ "--paddingRight": "var(--columnPaddingSmall)" }}>
                <header className="Copy__header">
                  <h2 className="Copy__caption">
                    {"Try it out"}
                  </h2>
                  <h1 className="Copy__title">
                    {" Configure your payment link in a few clicks "}
                  </h1>
                </header>
                <div className="Copy__body">
                  {" Sell products, offer subscriptions, and collect tips or donations simply by creating a link — no code required. "}
                </div>
                <footer className="Copy__footer">
                  <div className="CtaGroup CtaGroup--inline Copy__ctaGroup">
                    <a className="CtaButton variant--Button CtaButton--arrow" href="https://dashboard.stripe.com/register" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="">
                      {"Create account"}
                      <span className="nobr">
                        <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                          <g fillRule="evenodd">
                            <path className="HoverArrow__linePath" d="M0 5h7" />
                            <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                          </g>
                        </svg>
                      </span>
                    </a>
                  </div>
                </footer>
              </section>
              <div className="DemoLayout flavor--Twilight" data-js-controller="DemoLayout">
                <div className="ColumnLayout" data-columns="1,3">
                  <div className="DemoLayout__controlsContainer">
                    <div className="DemoLayout__interactiveDemoHeader">
                      <div className="DemoLayout__interactiveDemoHeaderInner">
                        <svg xmlns="http://www.w3.org/2000/svg" width="8" height="12" fill="none" viewBox="0 0 8 12">
                          <path fill="#f9f9f9" d="M4.193.21a.563.563 0 0 1 .402.566l-.16 3.537h1.943a.937.937 0 0 1 .808 1.412l-3.418 5.81a.563.563 0 0 1-1.047-.31l.161-3.537H.94A.938.938 0 0 1 .13 6.275L3.548.465A.563.563 0 0 1 4.193.21Z" />
                        </svg>
                        {" "}
                        <span>
                          {"Interactive demo"}
                        </span>
                      </div>
                      <div className="DemoLayout__interactiveDemoHeaderMask">
                        <div className="DemoLayout__interactiveDemoHeaderGradient" data-js-target="DemoLayout.gradient"></div>
                      </div>
                    </div>
                    <div className="DemoLayout__controlsInner">
                      <div className="PaymentLinksConfigure__hidden PaymentLinksConfigure__controls theme--Dark" data-js-target="PaymentLinksConfigure.controls">
                        <div className="PaymentLinksConfigure__modeControls" data-js-target="PaymentLinksConfigure.modeControls">
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Payment type "}
                              <div className="SelectInput">
                                <select className="SelectInput__input" name="" required data-js-controller="SelectInput" data-js-target="PaymentLinksConfigure.modeSelect" defaultValue="">
                                  <option value="" disabled>
                                    {" Select product type "}
                                  </option>
                                  <option value="payment">
                                    {" Payment "}
                                  </option>
                                  <option value="subscription">
                                    {" Subscription "}
                                  </option>
                                  <option value="donation">
                                    {" Tip or donation "}
                                  </option>
                                </select>
                                {" "}
                                <svg aria-hidden="true" className="SelectInput__arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 7" width="10">
                                  <path fill="none" style={{ stroke: "var(--inputTextColor)" }} strokeWidth="1.8" d="M9 1L5 5 1 1" />
                                </svg>
                              </div>
                            </label>
                          </div>
                        </div>
                        <div className="PaymentLinksConfigure__paymentControls" data-js-target="PaymentLinksConfigure.paymentControls">
                          <div className="ProductImageSelect" data-js-controller="ProductImageSelect" data-js-target="PaymentLinksConfigure.productSelect">
                            <div className="ControlGroup">
                              <label className="ControlGroup__label">
                                {" Product "}
                                <button className="ProductImageSelect__trigger" data-js-target="ProductImageSelect.trigger">
                                  <span className="ProductImageSelect__label ProductImageSelect__placeholder" data-js-target="ProductImageSelect.label">
                                    {"Select product"}
                                  </span>
                                  {" "}
                                  <svg className="ProductImageSelect__caret" width="10" viewBox="0 0 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M9 1L5 5 1 1" strokeWidth="1.8" />
                                  </svg>
                                </button>
                                <ul className="ProductImageSelect__optionList" id="-list" data-js-target="ProductImageSelect.optionListEl" hidden>
                                  <li className="ProductImageSelect__option" data-option-value="extremePure" data-js-target-list="ProductImageSelect.options">
                                    <img className="ProductImageSelect__optionImage" src="/sites/stripe-com-9ababc9a/products/6d65726368616e745f69643d616363745f314f4146563648-eb2cd06aaa.bin" alt="" />
                                    <div className="ProductImageSelect__optionTextContainer">
                                      <p className="ProductImageSelect__optionLabel">
                                        {"Extreme pure"}
                                      </p>
                                      <p className="ProductImageSelect__optionDescription">
                                        {"Niacinamide + zinc serum"}
                                      </p>
                                    </div>
                                  </li>
                                  <li className="ProductImageSelect__option" data-option-value="pureGlowCream" data-js-target-list="ProductImageSelect.options">
                                    <img className="ProductImageSelect__optionImage" src="/sites/stripe-com-9ababc9a/products/6d65726368616e745f69643d616363745f314f4146563648-a27bab551c.bin" alt="" />
                                    <div className="ProductImageSelect__optionTextContainer">
                                      <p className="ProductImageSelect__optionLabel">
                                        {"Pure glow cream"}
                                      </p>
                                      <p className="ProductImageSelect__optionDescription">
                                        {"Niacinamide + zinc lotion"}
                                      </p>
                                    </div>
                                  </li>
                                  <li className="ProductImageSelect__option" data-option-value="glowTonic" data-js-target-list="ProductImageSelect.options">
                                    <img className="ProductImageSelect__optionImage" src="/sites/stripe-com-9ababc9a/products/6d65726368616e745f69643d616363745f314f4146563648-cfc569ba55.bin" alt="" />
                                    <div className="ProductImageSelect__optionTextContainer">
                                      <p className="ProductImageSelect__optionLabel">
                                        {"Glow tonic"}
                                      </p>
                                      <p className="ProductImageSelect__optionDescription">
                                        {"Niacinamide + zinc toner"}
                                      </p>
                                    </div>
                                  </li>
                                </ul>
                              </label>
                            </div>
                          </div>
                        </div>
                        <div className="PaymentLinksConfigure__afterPaymentControls" data-js-target="PaymentLinksConfigure.afterPaymentControls">
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Confirmation message "}
                              <div className="TextInput">
                                <textarea data-js-controller="TextInput" className="TextInput__input TextInput__input--multiline" name="" placeholder="A payment to Powdur will appear on your statement." autoComplete="off" rows={2} data-js-target="PaymentLinksConfigure.confirmationMessageInput" defaultValue="" />
                                <div className="TextInput__error" aria-label="Invalid field" hidden>
                                  <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                                    <g fill="var(--inputErrorAccentColor)" fillRule="evenodd">
                                      <circle cx="8" cy="8" r="8" fillOpacity=".2" />
                                      <path d="M8 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-8a1 1 0 0 1 1 1v5a1 1 0 1 1-2 0V4a1 1 0 0 1 1-1z" />
                                    </g>
                                  </svg>
                                </div>
                              </div>
                            </label>
                          </div>
                        </div>
                        <div data-js-target="PaymentLinksConfigure.priceControls" data-js-amount="$1.00">
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Price "}
                              <div className="PaymentLinksConfigure__priceRow">
                                <div className="TextInput">
                                  <input data-js-controller="TextInput" className="TextInput__input" name="" type="text" placeholder="" data-js-target="PaymentLinksConfigure.priceInput" />
                                  <div className="TextInput__error" aria-label="Invalid field" hidden>
                                    <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                                      <g fill="var(--inputErrorAccentColor)" fillRule="evenodd">
                                        <circle cx="8" cy="8" r="8" fillOpacity=".2" />
                                        <path d="M8 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-8a1 1 0 0 1 1 1v5a1 1 0 1 1-2 0V4a1 1 0 0 1 1-1z" />
                                      </g>
                                    </svg>
                                  </div>
                                </div>
                                <div className="SelectInput">
                                  <select className="SelectInput__input" name="" data-js-controller="SelectInput" data-js-target="PaymentLinksConfigure.currencySelect" defaultValue="usd">
                                    <option value="aud">
                                      {" AUD "}
                                    </option>
                                    <option value="cad">
                                      {" CAD "}
                                    </option>
                                    <option value="eur">
                                      {" EUR "}
                                    </option>
                                    <option value="gbp">
                                      {" GBP "}
                                    </option>
                                    <option value="inr">
                                      {" INR "}
                                    </option>
                                    <option value="jpy">
                                      {" JPY "}
                                    </option>
                                    <option value="mxn">
                                      {" MXN "}
                                    </option>
                                    <option value="php">
                                      {" PHP "}
                                    </option>
                                    <option value="usd">
                                      {" USD "}
                                    </option>
                                  </select>
                                  {" "}
                                  <svg aria-hidden="true" className="SelectInput__arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 7" width="10">
                                    <path fill="none" style={{ stroke: "var(--inputTextColor)" }} strokeWidth="1.8" d="M9 1L5 5 1 1" />
                                  </svg>
                                </div>
                              </div>
                            </label>
                          </div>
                        </div>
                        <div data-js-target="PaymentLinksConfigure.subscriptionControls">
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Billing frequency "}
                              <div className="SelectInput">
                                <select className="SelectInput__input" name="" data-js-controller="SelectInput" data-js-target="PaymentLinksConfigure.billingFrequencySelect" defaultValue="month">
                                  <option value="month">
                                    {" Monthly "}
                                  </option>
                                  <option value="year">
                                    {" Yearly "}
                                  </option>
                                </select>
                                {" "}
                                <svg aria-hidden="true" className="SelectInput__arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 7" width="10">
                                  <path fill="none" style={{ stroke: "var(--inputTextColor)" }} strokeWidth="1.8" d="M9 1L5 5 1 1" />
                                </svg>
                              </div>
                            </label>
                          </div>
                        </div>
                        <div data-js-target="PaymentLinksConfigure.paymentSubscriptionControls">
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Additional options "}
                              <label className="CheckboxField">
                                <input className="CheckboxField__hiddenInput" id="" type="checkbox" defaultValue="customQuantity" data-js-target-list="PaymentLinksConfigure.adjustQuantityInput" />
                                {" "}
                                <span className="CheckboxField__checkbox">
                                  <svg className="CheckboxField__check" width="16" height="8" viewBox="0 0 8 7">
                                    <path d="M7.16.18L2.4 4.79 1.13 3.43a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36C3.2 6.33 7.77.86 7.77.86c.6-.6-.13-1.15-.6-.68z" fill="var(--knockoutColor)" />
                                  </svg>
                                  <div className="CheckboxField__dash"></div>
                                </span>
                                {" "}
                                <span className="CheckboxField__label">
                                  <p>
                                    {"Let customers adjust quantity"}
                                  </p>
                                </span>
                              </label>
                              {" "}
                              <label className="CheckboxField">
                                <input className="CheckboxField__hiddenInput" id="" type="checkbox" defaultValue="hasPromotionCodes" data-js-target-list="PaymentLinksConfigure.allowPromotionCodeInput" />
                                {" "}
                                <span className="CheckboxField__checkbox">
                                  <svg className="CheckboxField__check" width="16" height="8" viewBox="0 0 8 7">
                                    <path d="M7.16.18L2.4 4.79 1.13 3.43a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36C3.2 6.33 7.77.86 7.77.86c.6-.6-.13-1.15-.6-.68z" fill="var(--knockoutColor)" />
                                  </svg>
                                  <div className="CheckboxField__dash"></div>
                                </span>
                                {" "}
                                <span className="CheckboxField__label">
                                  <p>
                                    {"Allow promotion codes"}
                                  </p>
                                </span>
                              </label>
                            </label>
                          </div>
                        </div>
                        <div className="PaymentLinksConfigure__donationControls" data-js-target="PaymentLinksConfigure.donationControls">
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Preset amount "}
                              <div className="PaymentLinksConfigure__priceRow">
                                <div className="TextInput">
                                  <input data-js-controller="TextInput" className="TextInput__input" name="" type="text" placeholder="" data-js-target="PaymentLinksConfigure.presetPriceInput" />
                                  <div className="TextInput__error" aria-label="Invalid field" hidden>
                                    <svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                                      <g fill="var(--inputErrorAccentColor)" fillRule="evenodd">
                                        <circle cx="8" cy="8" r="8" fillOpacity=".2" />
                                        <path d="M8 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-8a1 1 0 0 1 1 1v5a1 1 0 1 1-2 0V4a1 1 0 0 1 1-1z" />
                                      </g>
                                    </svg>
                                  </div>
                                </div>
                                <div className="SelectInput">
                                  <select className="SelectInput__input" name="" data-js-controller="SelectInput" data-js-target="PaymentLinksConfigure.presetCurrencySelect" defaultValue="usd">
                                    <option value="aud">
                                      {" AUD "}
                                    </option>
                                    <option value="cad">
                                      {" CAD "}
                                    </option>
                                    <option value="eur">
                                      {" EUR "}
                                    </option>
                                    <option value="gbp">
                                      {" GBP "}
                                    </option>
                                    <option value="inr">
                                      {" INR "}
                                    </option>
                                    <option value="jpy">
                                      {" JPY "}
                                    </option>
                                    <option value="mxn">
                                      {" MXN "}
                                    </option>
                                    <option value="php">
                                      {" PHP "}
                                    </option>
                                    <option value="usd">
                                      {" USD "}
                                    </option>
                                  </select>
                                  {" "}
                                  <svg aria-hidden="true" className="SelectInput__arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 7" width="10">
                                    <path fill="none" style={{ stroke: "var(--inputTextColor)" }} strokeWidth="1.8" d="M9 1L5 5 1 1" />
                                  </svg>
                                </div>
                              </div>
                            </label>
                          </div>
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Call to action "}
                              <div className="SelectInput">
                                <select className="SelectInput__input" name="" data-js-controller="SelectInput" data-js-target="PaymentLinksConfigure.donationCallToActionSelect" defaultValue="donate">
                                  <option value="pay">
                                    {" Pay "}
                                  </option>
                                  <option value="book">
                                    {" Book "}
                                  </option>
                                  <option value="donate">
                                    {" Donate "}
                                  </option>
                                </select>
                                {" "}
                                <svg aria-hidden="true" className="SelectInput__arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 7" width="10">
                                  <path fill="none" style={{ stroke: "var(--inputTextColor)" }} strokeWidth="1.8" d="M9 1L5 5 1 1" />
                                </svg>
                              </div>
                            </label>
                          </div>
                          <div className="ControlGroup">
                            <label className="ControlGroup__label">
                              {" Additional options "}
                              <label className="CheckboxField">
                                <input className="CheckboxField__hiddenInput" id="" type="checkbox" defaultValue="requirePhoneNumber" data-js-target-list="PaymentLinksConfigure.requirePhoneNumberInput" />
                                {" "}
                                <span className="CheckboxField__checkbox">
                                  <svg className="CheckboxField__check" width="16" height="8" viewBox="0 0 8 7">
                                    <path d="M7.16.18L2.4 4.79 1.13 3.43a.7.7 0 0 0-.87-.04.61.61 0 0 0-.18.8l1.5 2.45c.15.22.41.36.69.36.28 0 .53-.14.68-.36C3.2 6.33 7.77.86 7.77.86c.6-.6-.13-1.15-.6-.68z" fill="var(--knockoutColor)" />
                                  </svg>
                                  <div className="CheckboxField__dash"></div>
                                </span>
                                {" "}
                                <span className="CheckboxField__label">
                                  <p>
                                    {"Require phone number"}
                                  </p>
                                </span>
                              </label>
                            </label>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="DemoLayout__displaySection">
                    <div className="PaymentLinksConfigure__displayContainer">
                      <div className="PaymentLinksConfigure__pageSelectorContainer">
                        <div className="PaymentLinksConfigure__pageSelector" data-js-target="PaymentLinksConfigure.pageSelector">
                          <button className="PaymentLinksConfigure__pageSelectorButton PaymentLinksConfigure__pageSelectorButton--selected" data-js-target-list="PaymentLinksConfigure.paymentPageButtons" value="paymentPage">
                            {"Payment page"}
                          </button>
                          {" "}
                          <button className="PaymentLinksConfigure__pageSelectorButton" data-js-target-list="PaymentLinksConfigure.paymentPageButtons" value="afterPayment">
                            {"After payment"}
                          </button>
                        </div>
                      </div>
                      <div className="FakeChrome__wrapper PaymentLinksConfigure__fakeChrome" data-js-target="DemoLayout.iframe">
                        <div className="FakeChrome__header">
                          <div className="FakeChrome__buttons">
                            <div className="FakeChrome__button"></div>
                            <div className="FakeChrome__button"></div>
                            <div className="FakeChrome__button"></div>
                          </div>
                          <div className="FakeChrome__search">
                            <svg xmlns="http://www.w3.org/2000/svg" width="5" height="7" fill="none">
                              <path fill="#7a7a7a" fillRule="evenodd" d="M.615 3.01v-.645a1.615 1.615 0 0 1 3.23 0v.645h.16c.18 0 .324.145.324.323v1.938c0 .357-.29.646-.646.646H.777A.646.646 0 0 1 .13 5.27V3.333c0-.178.144-.323.323-.323h.161Zm1.615.808a.323.323 0 0 0-.323.323v.645a.323.323 0 0 0 .646 0v-.645a.323.323 0 0 0-.323-.323Zm.969-.808v-.645a.969.969 0 0 0-1.938 0v.645H3.2Z" clipRule="evenodd" />
                            </svg>
                            {" buy.stripe.com "}
                          </div>
                        </div>
                        <iframe id="PaymentLinksConfigure__iframe" data-js-target="PaymentLinksConfigure.iframeElement"></iframe>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
