/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S08ReadyToGetStarted() {
  return (
    <section className="Section theme--Light Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div className="ColumnLayout" data-columns="2,1,1" style={{ "--columnRowGap": "var(--rowGapXLarge)" }}>
                  <section className="Copy variant--Subsection">
                    <header className="Copy__header">
                      <h1 className="Copy__title">
                        {" Ready to get started? Get in touch or create an account. "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      <p>
                        {"Access a complete payments platform with simple, pay-as-you-go pricing or contact us to design a custom package specifically for your business. "}
                      </p>
                    </div>
                    <footer className="Copy__footer">
                      <div className="CtaGroup CtaGroup--inline">
                        <a className="CtaButton variant--Button CtaButton--arrow" href="https://dashboard.stripe.com/register" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_ge__start_now">
                          {"Start now"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                        {" "}
                        <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/contact/sales" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get_started__contact_sales">
                          {"Contact sales"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                      </div>
                    </footer>
                  </section>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <div className="Copy__icon">
                        <svg className="Icon" width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <defs>
                            <clipPath id="BrowserWithPrebuiltUIIconClipPath-">
                              <path fillRule="evenodd" clipRule="evenodd" d="M4 2C1.79086 2 0 3.79086 0 6V26C0 28.2091 1.79086 30 4 30H32C34.2091 30 36 28.2091 36 26V6C36 3.79086 34.2091 2 32 2H4ZM4.5 8C5.32843 8 6 7.32843 6 6.5C6 5.67157 5.32843 5 4.5 5C3.67157 5 3 5.67157 3 6.5C3 7.32843 3.67157 8 4.5 8ZM11 6.5C11 7.32843 10.3284 8 9.5 8C8.67157 8 8 7.32843 8 6.5C8 5.67157 8.67157 5 9.5 5C10.3284 5 11 5.67157 11 6.5ZM14.5 8C15.3284 8 16 7.32843 16 6.5C16 5.67157 15.3284 5 14.5 5C13.6716 5 13 5.67157 13 6.5C13 7.32843 13.6716 8 14.5 8Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                            </clipPath>
                          </defs>
                          <path fillRule="evenodd" clipRule="evenodd" d="M4 2C1.79086 2 0 3.79086 0 6V26C0 28.2091 1.79086 30 4 30H32C34.2091 30 36 28.2091 36 26V6C36 3.79086 34.2091 2 32 2H4ZM4.5 8C5.32843 8 6 7.32843 6 6.5C6 5.67157 5.32843 5 4.5 5C3.67157 5 3 5.67157 3 6.5C3 7.32843 3.67157 8 4.5 8ZM11 6.5C11 7.32843 10.3284 8 9.5 8C8.67157 8 8 7.32843 8 6.5C8 5.67157 8.67157 5 9.5 5C10.3284 5 11 5.67157 11 6.5ZM14.5 8C15.3284 8 16 7.32843 16 6.5C16 5.67157 15.3284 5 14.5 5C13.6716 5 13 5.67157 13 6.5C13 7.32843 13.6716 8 14.5 8Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                          <path fillRule="evenodd" clipRule="evenodd" d="M12 13C9.79086 13 8 14.7909 8 17V34C8 36.2091 9.79086 38 12 38H36C38.2091 38 40 36.2091 40 34V17C40 14.7909 38.2091 13 36 13H12ZM12.75 17C12.3358 17 12 17.3358 12 17.75V20.25C12 20.6642 12.3358 21 12.75 21H17.25C17.6642 21 18 20.6642 18 20.25V17.75C18 17.3358 17.6642 17 17.25 17H12.75ZM21.75 17C21.3358 17 21 17.3358 21 17.75V33.25C21 33.6642 21.3358 34 21.75 34H26.25C26.6642 34 27 33.6642 27 33.25V17.75C27 17.3358 26.6642 17 26.25 17H21.75ZM12 24.75C12 24.3358 12.3358 24 12.75 24H17.25C17.6642 24 18 24.3358 18 24.75V33.25C18 33.6642 17.6642 34 17.25 34H12.75C12.3358 34 12 33.6642 12 33.25V24.75ZM30.75 30C30.3358 30 30 30.3358 30 30.75V33.25C30 33.6642 30.3358 34 30.75 34H35.25C35.6642 34 36 33.6642 36 33.25V30.75C36 30.3358 35.6642 30 35.25 30H30.75ZM30 17.75C30 17.3358 30.3358 17 30.75 17H35.25C35.6642 17 36 17.3358 36 17.75V26.25C36 26.6642 35.6642 27 35.25 27H30.75C30.3358 27 30 26.6642 30 26.25V17.75Z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                          <g clipPath="url(#BrowserWithPrebuiltUIIconClipPath-)">
                            <path fillRule="evenodd" clipRule="evenodd" d="M12 13C9.79086 13 8 14.7909 8 17V34C8 36.2091 9.79086 38 12 38H36C38.2091 38 40 36.2091 40 34V17C40 14.7909 38.2091 13 36 13H12ZM12.75 17C12.3358 17 12 17.3358 12 17.75V20.25C12 20.6642 12.3358 21 12.75 21H17.25C17.6642 21 18 20.6642 18 20.25V17.75C18 17.3358 17.6642 17 17.25 17H12.75ZM21.75 17C21.3358 17 21 17.3358 21 17.75V33.25C21 33.6642 21.3358 34 21.75 34H26.25C26.6642 34 27 33.6642 27 33.25V17.75C27 17.3358 26.6642 17 26.25 17H21.75ZM12 24.75C12 24.3358 12.3358 24 12.75 24H17.25C17.6642 24 18 24.3358 18 24.75V33.25C18 33.6642 17.6642 34 17.25 34H12.75C12.3358 34 12 33.6642 12 33.25V24.75ZM30.75 30C30.3358 30 30 30.3358 30 30.75V33.25C30 33.6642 30.3358 34 30.75 34H35.25C35.6642 34 36 33.6642 36 33.25V30.75C36 30.3358 35.6642 30 35.25 30H30.75ZM30 17.75C30 17.3358 30.3358 17 30.75 17H35.25C35.6642 17 36 17.3358 36 17.75V26.25C36 26.6642 35.6642 27 35.25 27H30.75C30.3358 27 30 26.6642 30 26.25V17.75Z" className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} />
                          </g>
                        </svg>
                      </div>
                      <h1 className="Copy__title">
                        {" Design your payments page "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      <p>
                        {"Create your own payments page using Stripe Elements, our suite of prebuilt embeddable UI components."}
                      </p>
                    </div>
                    <footer className="Copy__footer">
                      <a className="CtaButton variant--Link CtaButton--arrow" href="/payments/elements" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get__design_your_payments__stripe_elements">
                        {"Stripe Elements"}
                        <span className="nobr">
                          <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                            <g fillRule="evenodd">
                              <path className="HoverArrow__linePath" d="M0 5h7" />
                              <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                            </g>
                          </svg>
                        </span>
                      </a>
                    </footer>
                  </section>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <div className="Copy__icon">
                        <svg className="Icon" width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <defs>
                            <clipPath id="BrowserWithLightningBoltIconClipPath-">
                              <path fillRule="evenodd" clipRule="evenodd" d="M4 2C1.79086 2 0 3.79086 0 6V26C0 28.2091 1.79086 30 4 30H32C34.2091 30 36 28.2091 36 26V6C36 3.79086 34.2091 2 32 2H4ZM4.5 8C5.32843 8 6 7.32843 6 6.5C6 5.67157 5.32843 5 4.5 5C3.67157 5 3 5.67157 3 6.5C3 7.32843 3.67157 8 4.5 8ZM11 6.5C11 7.32843 10.3284 8 9.5 8C8.67157 8 8 7.32843 8 6.5C8 5.67157 8.67157 5 9.5 5C10.3284 5 11 5.67157 11 6.5ZM14.5 8C15.3284 8 16 7.32843 16 6.5C16 5.67157 15.3284 5 14.5 5C13.6716 5 13 5.67157 13 6.5C13 7.32843 13.6716 8 14.5 8Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                            </clipPath>
                          </defs>
                          <path fillRule="evenodd" clipRule="evenodd" d="M4 2C1.79086 2 0 3.79086 0 6V26C0 28.2091 1.79086 30 4 30H32C34.2091 30 36 28.2091 36 26V6C36 3.79086 34.2091 2 32 2H4ZM4.5 8C5.32843 8 6 7.32843 6 6.5C6 5.67157 5.32843 5 4.5 5C3.67157 5 3 5.67157 3 6.5C3 7.32843 3.67157 8 4.5 8ZM11 6.5C11 7.32843 10.3284 8 9.5 8C8.67157 8 8 7.32843 8 6.5C8 5.67157 8.67157 5 9.5 5C10.3284 5 11 5.67157 11 6.5ZM14.5 8C15.3284 8 16 7.32843 16 6.5C16 5.67157 15.3284 5 14.5 5C13.6716 5 13 5.67157 13 6.5C13 7.32843 13.6716 8 14.5 8Z" className="Icon__blendBackground" style={{ fill: "var(--blendBackground)" }} />
                          <path fillRule="evenodd" clipRule="evenodd" d="M34.8722 13C36.6553 13 37.3018 13.1857 37.9537 13.5343C38.6055 13.8829 39.1171 14.3945 39.4657 15.0463C39.8144 15.6982 40 16.3447 40 18.1278V32.8722C40 34.6553 39.8144 35.3018 39.4657 35.9537C39.1171 36.6055 38.6055 37.1171 37.9537 37.4657C37.3018 37.8144 36.6553 38 34.8722 38H13.1278C11.3447 38 10.6982 37.8144 10.0463 37.4657C9.39446 37.1171 8.88288 36.6055 8.53427 35.9537C8.18565 35.3018 8 34.6553 8 32.8722V18.1278C8 16.3447 8.18565 15.6982 8.53427 15.0463C8.88288 14.3945 9.39446 13.8829 10.0463 13.5343C10.6982 13.1857 11.3447 13 13.1278 13H34.8722ZM25.1147 18.032C24.8105 17.9351 24.4785 18.0642 24.3273 18.3381L20.0944 26.2178C19.9685 26.4602 19.9685 26.7462 20.0944 26.9885C20.2237 27.2279 20.4607 27.3949 20.7351 27.4403H20.8392L24.226 27.5918L23.4375 32.2611C23.3848 32.5705 23.5725 32.8708 23.8795 32.9684C24.1865 33.0659 24.5209 32.9315 24.6669 32.6518L28.9052 24.7588C29.0316 24.5166 29.0316 24.2304 28.9052 23.9881C28.7754 23.7481 28.5373 23.5809 28.2618 23.5363H28.1578L24.7736 23.3928L25.5622 18.7314C25.6076 18.4238 25.419 18.1289 25.1147 18.032Z" className="Icon__blendForeground" style={{ fill: "var(--blendForeground)" }} />
                          <g clipPath="url(#BrowserWithLightningBoltIconClipPath-)">
                            <path fillRule="evenodd" clipRule="evenodd" d="M34.8722 13C36.6553 13 37.3018 13.1857 37.9537 13.5343C38.6055 13.8829 39.1171 14.3945 39.4657 15.0463C39.8144 15.6982 40 16.3447 40 18.1278V32.8722C40 34.6553 39.8144 35.3018 39.4657 35.9537C39.1171 36.6055 38.6055 37.1171 37.9537 37.4657C37.3018 37.8144 36.6553 38 34.8722 38H13.1278C11.3447 38 10.6982 37.8144 10.0463 37.4657C9.39446 37.1171 8.88288 36.6055 8.53427 35.9537C8.18565 35.3018 8 34.6553 8 32.8722V18.1278C8 16.3447 8.18565 15.6982 8.53427 15.0463C8.88288 14.3945 9.39446 13.8829 10.0463 13.5343C10.6982 13.1857 11.3447 13 13.1278 13H34.8722ZM25.1147 18.032C24.8105 17.9351 24.4785 18.0642 24.3273 18.3381L20.0944 26.2178C19.9685 26.4602 19.9685 26.7462 20.0944 26.9885C20.2237 27.2279 20.4607 27.3949 20.7351 27.4403H20.8392L24.226 27.5918L23.4375 32.2611C23.3848 32.5705 23.5725 32.8708 23.8795 32.9684C24.1865 33.0659 24.5209 32.9315 24.6669 32.6518L28.9052 24.7588C29.0316 24.5166 29.0316 24.2304 28.9052 23.9881C28.7754 23.7481 28.5373 23.5809 28.2618 23.5363H28.1578L24.7736 23.3928L25.5622 18.7314C25.6076 18.4238 25.419 18.1289 25.1147 18.032Z" className="Icon__blendForeground" style={{ fill: "var(--blendIntersection)" }} />
                          </g>
                        </svg>
                      </div>
                      <h1 className="Copy__title">
                        {" Prebuilt payment form "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      <p>
                        {"Accept payments on your website by integrating Stripe Checkout, our prebuilt payment form optimized for conversion."}
                      </p>
                    </div>
                    <footer className="Copy__footer">
                      <a className="CtaButton variant--Link CtaButton--arrow" href="/payments/checkout" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get__prebuilt_payment_form__stripe_checkout">
                        {"Stripe Checkout"}
                        <span className="nobr">
                          <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                            <g fillRule="evenodd">
                              <path className="HoverArrow__linePath" d="M0 5h7" />
                              <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                            </g>
                          </svg>
                        </span>
                      </a>
                    </footer>
                  </section>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
