/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
import { Footer } from "@/components/stripe/Footer/Footer";
import { Navigation } from "@/components/stripe/Navigation/Navigation";
import { V1Runtime } from "@/components/sites/stripe-com-9ababc9a/v1/V1Runtime";
import { S00ProductHeroSection } from "./sections/S00ProductHeroSection";
import { S01IncreaseConversion } from "./sections/S01IncreaseConversion";
import { S02Block } from "./sections/S02Block";
import { S03HowItWorks } from "./sections/S03HowItWorks";
import { S04BuildForAgents } from "./sections/S04BuildForAgents";
import { S05Bank } from "./sections/S05Bank";
import { S06FullyIntegrated } from "./sections/S06FullyIntegrated";
import { S07CaseStudies } from "./sections/S07CaseStudies";
import { S08Pricing } from "./sections/S08Pricing";
import { S09ReadyToGetStarted } from "./sections/S09ReadyToGetStarted";
import { S10LegalFooterSection } from "./sections/S10LegalFooterSection";
import { S11MobileStickyNav } from "./sections/S11MobileStickyNav";

export function LinkPage() {
  return (
    <>
      <div className="mobile-safari-solid-bars" />
      <Navigation />
      <div className="v1-root" data-page="link">
        <div className="MktRoot v1-html">
          <div className="MktBody v1-body MktBody theme--Light flavor--Twilight accent--Purple">
            <main id="MktContent">
              <S00ProductHeroSection />
              <S01IncreaseConversion />
              <S02Block />
              <S03HowItWorks />
              <S04BuildForAgents />
              <S05Bank />
              <S06FullyIntegrated />
              <S07CaseStudies />
              <S08Pricing />
              <S09ReadyToGetStarted />
              <S10LegalFooterSection />
              <S11MobileStickyNav />
            </main>
          </div>
        </div>
      </div>
      <Footer />
      <V1Runtime page="link" />
    </>
  );
}
