/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
import { Footer } from "@/components/stripe/Footer/Footer";
import { Navigation } from "@/components/stripe/Navigation/Navigation";
import { V1Runtime } from "@/components/sites/stripe-com-9ababc9a/v1/V1Runtime";
import { S00ProductHeroSection } from "./sections/S00ProductHeroSection";
import { S01CustomizableComponents } from "./sections/S01CustomizableComponents";
import { S02Block } from "./sections/S02Block";
import { S03CustomizableModularComponents } from "./sections/S03CustomizableModularComponents";
import { S04BuiltByUsDesigned } from "./sections/S04BuiltByUsDesigned";
import { S05Block } from "./sections/S05Block";
import { S06LessCodeFewerErrors } from "./sections/S06LessCodeFewerErrors";
import { S07Pricing } from "./sections/S07Pricing";
import { S08PickYourPath } from "./sections/S08PickYourPath";
import { S09ReadyToGetStarted } from "./sections/S09ReadyToGetStarted";
import { S10MobileStickyNav } from "./sections/S10MobileStickyNav";

export function ElementsPage() {
  return (
    <>
      <div className="mobile-safari-solid-bars" />
      <Navigation />
      <div className="v1-root" data-page="elements">
        <div className="MktRoot v1-html">
          <div className="MktBody v1-body MktBody theme--Light flavor--Twilight accent--Purple">
            <main id="MktContent">
              <S00ProductHeroSection />
              <S01CustomizableComponents />
              <S02Block />
              <S03CustomizableModularComponents />
              <S04BuiltByUsDesigned />
              <S05Block />
              <S06LessCodeFewerErrors />
              <S07Pricing />
              <S08PickYourPath />
              <S09ReadyToGetStarted />
              <S10MobileStickyNav />
            </main>
          </div>
        </div>
      </div>
      <Footer />
      <V1Runtime page="elements" />
    </>
  );
}
