/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S03Block() {
  return (
    <section className="hds-color-mode section hds-mode--light">
      <div className="section-container">
        <div className="manifesto-container">
          <div className="manifesto-eyebrow">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="none" viewBox="0 0 14 14">
              <path fill="#2b2b2b" fillRule="evenodd" d="m0 14 14-2.9416V0L0 2.88716z" clipRule="evenodd" />
            </svg>
            <p className="hds-text hds-text--sm hds-text--emphasized">
              {"The opportunity"}
            </p>
          </div>
          <span className="hds-heading manifesto-heading hds-heading--md">
            {"AI has made software value dynamic—but many billing systems haven’t kept up. Metronome lets you charge for the value you deliver, the moment you deliver it."}
          </span>
          <div className="manifesto-body">
            <p className="hds-text hds-text--md hds-text--soft">
              {"Customers increasingly expect to pay only for the value they receive. That means product teams need to regularly test and iterate pricing, while finance teams need to track usage, account for revenue accurately, and maintain clear, continuous reporting on all of it."}
            </p>
            <p className="hds-text hds-text--md hds-text--soft">
              {"With Metronome, you can launch new pricing models in days; test and adjust on the fly; and meter, bill, and track revenue in one place—with clear visibility into usage and spend for you and your customers. The result: billing that keeps pace with your product."}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
