/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S02Block() {
  return (
    <section className="hds-color-mode section hds-mode--light">
      <div className="section-container">
        <div className="manifesto-container">
          <div className="manifesto-eyebrow">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="none" viewBox="0 0 14 14">
              <path fill="#2b2b2b" fillRule="evenodd" d="m0 14 14-2.9416V0L0 2.88716z" clipRule="evenodd" />
            </svg>
            <p className="hds-text hds-text--sm hds-text--emphasized">
              {"The opportunity"}
            </p>
          </div>
          <span className="hds-heading manifesto-heading hds-heading--md">
            {"AI is changing how software is monetized. You need the flexibility to handle new business models, new markets, and the complexity that comes with them."}
          </span>
          <div className="manifesto-body">
            <p className="hds-text hds-text--md hds-text--soft">
              {"Consumption-based billing, hybrid models, flexible tiers—pricing models are evolving and you need to keep up. But if your billing infrastructure isn’t flexible enough, every pricing change can slow you down, especially as you expand globally."}
            </p>
            <p className="hds-text hds-text--md hds-text--soft">
              {"Stripe Billing lets you localize pricing, customize billing logic, and collect payments faster. Unify subscriptions and usage-based billing into one automated flow that supports any way you monetize."}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
