/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S12Footnotes() {
  return (
    <section className="hds-color-mode footnotes section section--white hds-mode--light">
      <div className="section-container footnotes__divider-container">
        <div className="divider-wrapper"></div>
      </div>
      <div className="section-container">
        <div className="section-row section-row-gap" style={{ "--section-row-gap-mb": "var(--hds-space-core-200)" }}>
          <p className="hds-text footnotes__item hds-text--sm hds-text--subdued">
            <sup>
              {"1"}
            </sup>
            {" Metronome, a Stripe product, is not included in Stripe Billing. See "}
            <a className="hds-link hds-link--secondary" href="https://stripe.com/billing/pricing" data-analytics-label="footnotes__metronome_footnote__pricing_page_link">
              {"pricing page"}
            </a>
            {" for more details."}
          </p>
          <p className="hds-text footnotes__item hds-text--sm hds-text--subdued">
            <sup>
              {"2"}
            </sup>
            {" Forrester does not endorse any company, product, brand, or service included in its research publications and does not advise any person to select the products or services of any company or brand based on the ratings included in such publications. Information is based on the best available resources. Opinions reflect judgment at the time and are subject to change. For more information, read about Forrester's objectivity "}
            <a className="hds-link hds-link--secondary" href="https://www.forrester.com/about-us/objectivity" data-analytics-label="footnotes__forrester_footnote__objectivity_page_link">
              {"here"}
            </a>
            {"."}
          </p>
          <p className="hds-text footnotes__item hds-text--sm hds-text--subdued">
            <sup>
              {"3"}
            </sup>
            {" Gartner and Magic Quadrant are registered trademarks of Gartner, Inc. and /or its affiliates in the U.S. and internationally and are used herein with permission. All rights reserved. Gartner does not endorse any vendor, product or service depicted in its research publications, and does not advise technology users to select only those vendors with the highest ratings or other designation. Gartner research publications consist of the opinions of Gartner's research organization and should not be construed as statements of fact. Gartner disclaims all warranties, expressed or implied, with respect to this research, including any warranties of merchantability or fitness for a particular purpose."}
          </p>
        </div>
      </div>
    </section>
  );
}
