/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
import { Footer } from "@/components/stripe/Footer/Footer";
import { Navigation } from "@/components/stripe/Navigation/Navigation";
import { V1Runtime } from "@/components/sites/stripe-com-9ababc9a/v1/V1Runtime";
import { S00ProductHeroSection } from "./sections/S00ProductHeroSection";
import { S01IncreaseAuthorizationRatesWith } from "./sections/S01IncreaseAuthorizationRatesWith";
import { S02Block } from "./sections/S02Block";
import { S03CoreTechnology } from "./sections/S03CoreTechnology";
import { S04AiPowered } from "./sections/S04AiPowered";
import { S05CostOptimization } from "./sections/S05CostOptimization";
import { S06LifecycleManagement } from "./sections/S06LifecycleManagement";
import { S07Analytics } from "./sections/S07Analytics";
import { S08Block } from "./sections/S08Block";
import { S09PaymentsIntelligenceSuite } from "./sections/S09PaymentsIntelligenceSuite";
import { S10IssuerAndNetworkPartnerships } from "./sections/S10IssuerAndNetworkPartnerships";
import { S11IndustryExpertise } from "./sections/S11IndustryExpertise";
import { S12Pricing } from "./sections/S12Pricing";
import { S13MoreResources } from "./sections/S13MoreResources";
import { S14ReadyToGetStarted } from "./sections/S14ReadyToGetStarted";
import { S15MobileStickyNav } from "./sections/S15MobileStickyNav";

export function AuthorizationBoostPage() {
  return (
    <>
      <div className="mobile-safari-solid-bars" />
      <Navigation />
      <div className="v1-root" data-page="authorization-boost">
        <div className="MktRoot v1-html">
          <div className="MktBody v1-body MktBody theme--Light flavor--Twilight accent--Purple">
            <main id="MktContent">
              <S00ProductHeroSection />
              <S01IncreaseAuthorizationRatesWith />
              <S02Block />
              <S03CoreTechnology />
              <S04AiPowered />
              <S05CostOptimization />
              <S06LifecycleManagement />
              <S07Analytics />
              <S08Block />
              <S09PaymentsIntelligenceSuite />
              <S10IssuerAndNetworkPartnerships />
              <S11IndustryExpertise />
              <S12Pricing />
              <S13MoreResources />
              <S14ReadyToGetStarted />
              <S15MobileStickyNav />
            </main>
          </div>
        </div>
      </div>
      <Footer />
      <V1Runtime page="authorization-boost" />
    </>
  );
}
