/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
import { Footer } from "@/components/stripe/Footer/Footer";
import { Navigation } from "@/components/stripe/Navigation/Navigation";
import { HdsRuntime } from "@/components/sites/stripe-com-9ababc9a/hds/HdsRuntime";
import { S00ManagedPaymentsHero } from "./sections/S00ManagedPaymentsHero";
import { S01Block } from "./sections/S01Block";
import { S02Block } from "./sections/S02Block";
import { S03ManagedPaymentsManifesto } from "./sections/S03ManagedPaymentsManifesto";
import { S04ReduceOverheadAndGet } from "./sections/S04ReduceOverheadAndGet";
import { S05BuiltForYourGlobal } from "./sections/S05BuiltForYourGlobal";
import { S06Block } from "./sections/S06Block";
import { S07Block } from "./sections/S07Block";
import { S08Block } from "./sections/S08Block";
import { S09FrequentlyAskedQuestions } from "./sections/S09FrequentlyAskedQuestions";
import { S10Block } from "./sections/S10Block";

export function ManagedPaymentsPage() {
  return (
    <>
      <div className="mobile-safari-solid-bars" />
      <Navigation />
      <main id="main-content" data-page="managed-payments">
        <S00ManagedPaymentsHero />
        <S01Block />
        <S02Block />
        <S03ManagedPaymentsManifesto />
        <S04ReduceOverheadAndGet />
        <S05BuiltForYourGlobal />
        <S06Block />
        <S07Block />
        <S08Block />
        <S09FrequentlyAskedQuestions />
        <S10Block />
      </main>
      <Footer />
      <HdsRuntime page="managed-payments" />
    </>
  );
}
