/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S05DeviceOrderingAndManagement() {
  return (
    <section className="Section theme--White Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <section className="Copy variant--Section">
                  <header className="Copy__header">
                    <h2 className="Copy__caption">
                      {"Device ordering and management"}
                    </h2>
                    <h1 className="Copy__title">
                      {" Simplify your hardware logistics "}
                    </h1>
                  </header>
                  <div className="Copy__body">
                    <p>
                      {"Stripe makes it easy to order, manage, and monitor your readers, wherever they are."}
                    </p>
                  </div>
                </section>
                <div className="TerminalDeviceManagementLayout" data-js-controller="TerminalDeviceManagementLayout">
                  <div className="ColumnLayout" data-columns="1,3">
                    <div className="TerminalDeviceManagementLayout__copyContainer" data-js-target="TerminalDeviceManagementLayout.copyContainer">
                      <div className="TerminalDeviceManagementLayout__copyTrack">
                        <section className="Copy variant--Detail">
                          <header className="Copy__header">
                            <h1 className="Copy__title">
                              {" Device ordering "}
                            </h1>
                          </header>
                          <div className="Copy__body">
                            {" Order readers from the Stripe Dashboard or offer white-labeled ordering with the Terminal Hardware Orders API (Preview)—we’ll handle the warehousing and delivery. "}
                          </div>
                          <footer className="Copy__footer">
                            <div className="CtaGroup CtaGroup--inline Copy__ctaGroup">
                              <a className="CtaButton variant--Link CtaButton--arrow TerminalDeviceManagementLayout__copyCta" href="https://docs.stripe.com/terminal/fleet/order-and-return-readers#use-the-hardware-orders-api" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="simplify_your_hardware__device_ordering__learn_how_to">
                                {"Learn how to place orders"}
                                <span className="nobr">
                                  <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                    <g fillRule="evenodd">
                                      <path className="HoverArrow__linePath" d="M0 5h7" />
                                      <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                    </g>
                                  </svg>
                                </span>
                              </a>
                            </div>
                          </footer>
                        </section>
                        <section className="Copy variant--Detail">
                          <header className="Copy__header">
                            <h1 className="Copy__title">
                              {" Device management "}
                            </h1>
                          </header>
                          <div className="Copy__body">
                            {" Easily manage your readers across locations. Register and configure your devices, and monitor their status in real time for quick troubleshooting. "}
                          </div>
                          <footer className="Copy__footer">
                            <div className="CtaGroup CtaGroup--inline Copy__ctaGroup">
                              <a className="CtaButton variant--Link CtaButton--arrow TerminalDeviceManagementLayout__copyCta" href="https://docs.stripe.com/terminal/fleet/locations" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="simplify_your_hardware__device_management__view_management_capabilities">
                                {"View management capabilities"}
                                <span className="nobr">
                                  <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                                    <g fillRule="evenodd">
                                      <path className="HoverArrow__linePath" d="M0 5h7" />
                                      <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                                    </g>
                                  </svg>
                                </span>
                              </a>
                            </div>
                          </footer>
                        </section>
                      </div>
                    </div>
                    <figure className="TerminalDeviceManagementLayout__graphicContainer">
                      <nav className="SegmentedControl" data-js-controller="SegmentedControl" data-selection-mode="single">
                        <div className="SegmentedControl__container">
                          <div className="HorizontalOverflowContainer" data-js-controller="HorizontalOverflowContainer" style={{ "--horizontalOverflowSpacing": "16px" }}>
                            <div className="HorizontalOverflowContainer__track" data-js-target="HorizontalOverflowContainer.track">
                              <div className="SegmentedControl__backContainer" data-js-target="SegmentedControl.backButtonContainer" aria-hidden="true"></div>
                              <div className="HorizontalOverflowContainer__items">
                                <div className="SegmentedControl__buttons" data-js-target="SegmentedControl.items">
                                  <button className="SegmentedControlButton SegmentedControlButton--active" data-js-target-list="SegmentedControl.buttons">
                                    {" Device ordering "}
                                  </button>
                                  {" "}
                                  <button className="SegmentedControlButton" data-js-target-list="SegmentedControl.buttons">
                                    {" Device management "}
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </nav>
                      <div className="Card Card--shadowLarge">
                        <div className="TerminalDeviceManagementLayout__graphicTrack">
                          <figure className="DomGraphic TerminalDeviceManagementLayout__hardwareOrderingDomGraphic" aria-hidden="true" data-js-controller="DomGraphic" data-js-source-width="810" data-js-source-height="432">
                            <div className="DomGraphic__heightContainer">
                              <div className="DomGraphic__scaleContainer" data-js-target="DomGraphic.scaleContainer">
                                <div className="TerminalDeviceManagementLayout__hardwareOrderingGraphic">
                                  <div className="Card TerminalDeviceManagementLayout__hardwareOrderingGraphicCodeEditor theme--Dark">
                                    <div className="CodeEditor CodeEditor--focused" style={{ "--codeEditorVisibleNumberOfLines": "17" }} aria-hidden="true" data-js-controller="CodeEditor" data-js-language-mode="bash">
                                      <div data-js-target="CodeEditor.finalCode" style={{ display: "none" }}>
                                        {"curl https://api.stripe.com/v1/terminal/hardware_orders \\ -u sk_test_••••••••••••••••••••••••••••••••••: \\ -H \"Stripe-Version: 2023-08-16;terminal_hardware_orders_beta=v4\" \\ -d \"shipping[name]\"=\"Jenny Rosen\" \\ -d \"shipping[address][line1]\"=\"1234 Main Street\" \\ -d \"shipping[address][line2]\"=\"Apt. 123\" \\ -d \"shipping[address][city]\"=\"San Francisco\" \\ -d \"shipping[address][state]\"=\"CA\" \\ -d \"shipping[address][country]\"=\"US\" \\ -d \"shipping[address][postal_code]\"=\"94111\" \\ -d \"shipping[company]\"=\"Rocket Rides\" \\ -d \"shipping[phone]\"=\"15555555555\" \\ -d \"shipping[email]\"=\"test@example.com\" \\ -d \"hardware_order_items[][terminal_hardware_sku]\"=\"thsku_JokaJ6KpLMlDID\" \\ -d \"hardware_order_items[][quantity]\"=\"2\" \\ -d shipping_method=\"thsm_MfuTjLaPEgXMa4\" \\ -d payment_type=\"monthly_invoice\""}
                                      </div>
                                      <code className="CodeEditor__scrollContainer" data-js-target="CodeEditor.scrollContainer">
                                        <pre className="CodeSyntax CodeEditor__editor">
                                          <div className="CodeEditorLineNumbers" data-js-controller="CodeEditorLineNumbers">
                                            {"\n  "}
                                            <div className="CodeEditorLineNumbers__lineNumbersContainer" data-js-target="CodeEditorLineNumbers.lineNumbersContainer">
                                              {"\n    "}
                                              <span className="CodeEditorLineNumbers__number" data-js-target="CodeEditorLineNumbers.firstLineNumber">
                                                {"~"}
                                              </span>
                                              {"\n  "}
                                            </div>
                                            {"\n\n  \n"}
                                          </div>
                                          {"\n        \n        "}
                                          <span className="CodeEditorAsciiLoader"></span>
                                          {"\n        \n        "}
                                          <span className="CodeEditor__typingArea">
                                            <span data-js-target="CodeEditor.editor"></span>
                                            {"\n          \n        "}
                                          </span>
                                        </pre>
                                      </code>
                                    </div>
                                  </div>
                                  <picture className="Picture TerminalDeviceManagementLayout__hardwareOrderingGraphicWebUI">
                                    <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/furni-white-label-en-jp-28c9e676f3.webp 2x,\n            /sites/stripe-com-9ababc9a/products/furni-white-label-en-jp-12d19b8ba5.webp\n          "} type="image/webp" />
                                    <img className="Picture__image" src="/sites/stripe-com-9ababc9a/products/furni-white-label-en-jp-3c7bad25a8.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/furni-white-label-en-jp-3c7bad25a8.png 2x,\n          /sites/stripe-com-9ababc9a/products/furni-white-label-en-jp-1ea01e301c.png\n        "} alt="Stylized product layout showing two devices and 4 accessories" width="522" height="400" loading="lazy" />
                                  </picture>
                                </div>
                              </div>
                            </div>
                          </figure>
                          <picture className="Picture Picture--autosize TerminalDeviceManagementLayout__graphic">
                            <source srcSet={"\n            /sites/stripe-com-9ababc9a/products/device_management_en-us-f4ef550a7f.webp 2x,\n            /sites/stripe-com-9ababc9a/products/device_management_en-us-93613ca392.webp\n          "} type="image/webp" />
                            <img className="Picture__image" src="/sites/stripe-com-9ababc9a/products/device_management_en-us-4a55f715f2.png" srcSet={"\n          /sites/stripe-com-9ababc9a/products/device_management_en-us-4a55f715f2.png 2x,\n          /sites/stripe-com-9ababc9a/products/device_management_en-us-8e6e60efdf.png\n        "} alt="Screenshot of a Stripe dashboard showing the management of devices by location" width="810" height="432" loading="lazy" />
                          </picture>
                        </div>
                      </div>
                    </figure>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
