/* Generated by scripts/forensics/products/build_pages.py from the stripe.com page captured 2026-09-24.
   Markup and class names are the reference's; behaviours live in the page runtime. Do not hand-edit
   structure here without re-running the capture; visual fixes belong in the page stylesheet. */
export function S12ReadyToGetStarted() {
  return (
    <section className="Section theme--Light Section--paddingNormal Section--hasGuides">
      <div className="Section__masked">
        <div className="Section__backgroundMask">
          <div className="Section__background">
            <div className="Guides" aria-hidden="true">
              <div className="Guides__container">
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
                <div className="Guides__guide"></div>
              </div>
            </div>
          </div>
        </div>
        <div className="Section__container">
          <div className="Section__layoutContainer">
            <div className="Section__layout">
              <div className="RowLayout" style={{ "--rowLayoutGap": "var(--rowLayoutGapXLarge)" }}>
                <div className="ColumnLayout" data-columns="2,1,1" style={{ "--columnRowGap": "var(--rowGapXLarge)" }}>
                  <section className="Copy variant--Subsection">
                    <header className="Copy__header">
                      <h1 className="Copy__title">
                        {" Ready to get started? "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      <p>
                        {"Get started in the Dashboard or contact sales."}
                      </p>
                    </div>
                    <footer className="Copy__footer">
                      <div className="CtaGroup CtaGroup--inline">
                        <a className="CtaButton variant--Button CtaButton--arrow" href="https://dashboard.stripe.com/get-started/terminal" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get__get_started">
                          {"Get started"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                        {" "}
                        <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/contact/sales" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get__contact_sales">
                          {"Contact sales"}
                          <span className="nobr">
                            <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                              <g fillRule="evenodd">
                                <path className="HoverArrow__linePath" d="M0 5h7" />
                                <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                              </g>
                            </svg>
                          </span>
                        </a>
                      </div>
                    </footer>
                  </section>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <div className="Copy__icon">
                        <div className="AnimatedIcon TerminalIcon">
                          <div className="AnimatedIcon__iconContainer">
                            <svg className="AnimatedIcon__icon" width="96" height="96" preserveAspectRatio="xMinYMin" viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg" data-js-controller="TerminalIcon">
                              <defs>
                                <path id="terminalIconCode" d="M44 28a4 4 0 0 1 4 4v17a4 4 0 0 1-4 4H20a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h24zm-23.2 5.17l-.67.75a.5.5 0 0 0-.02.64l.06.06 3.29 2.92-3.3 2.92a.5.5 0 0 0-.03.7l.66.76c.18.2.5.22.7.04l4.97-4.42-4.96-4.41a.5.5 0 0 0-.7.04z" />
                                <path id="terminalIconCursor" d="M27.64 40h6.72c.22 0 .3.02.38.07.09.04.15.1.2.19.04.08.06.16.06.38v.72c0 .22-.02.3-.07.38a.45.45 0 0 1-.19.2c-.08.04-.16.06-.38.06h-6.72c-.22 0-.3-.02-.38-.07a.45.45 0 0 1-.2-.19c-.04-.08-.06-.16-.06-.38v-.72c0-.22.02-.3.07-.38.04-.09.1-.15.19-.2.08-.04.16-.06.38-.06z" />
                                <path id="terminalIconGear" d="M42.5 42l1.13 3.13.64.13 2.24-2.46.93.38-.16 3.33c.19.11.37.23.54.36l3.02-1.42.7.71-1.41 3.02c.13.17.25.35.36.54l3.33-.16.38.93-2.46 2.24c.05.21.1.42.13.64L55 54.5v1l-3.13 1.13c-.04.25-.1.5-.15.73l2.48 2.15-.38.93-3.28-.24c-.14.24-.3.47-.47.7l1.48 2.94-.71.7-2.94-1.47c-.23.17-.46.33-.7.47l.24 3.28-.93.38-2.15-2.48c-.27.06-.54.12-.82.16L42.5 68h-1l-1.04-3.12c-.28-.04-.55-.1-.82-.16l-2.15 2.48-.93-.38.24-3.28c-.24-.14-.47-.3-.7-.47l-2.94 1.48-.7-.71 1.47-2.94c-.17-.23-.33-.46-.47-.7l-3.28.24-.38-.93 2.48-2.15a9.95 9.95 0 0 1-.16-.82L29 55.5v-1l3.12-1.04c.04-.25.08-.49.14-.73l-2.46-2.24.38-.93 3.33.16c.11-.19.23-.37.36-.54l-1.42-3.02.71-.7 3.02 1.41c.17-.13.35-.25.54-.36l-.16-3.33.93-.38 2.24 2.46s.42-.1.64-.13L41.5 42h1zM42 53a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
                                <clipPath id="terminalIconClipPath">
                                  <use href="#terminalIconCode" />
                                </clipPath>
                              </defs>
                              <use href="#terminalIconCode" fill="var(--blendBackground)" />
                              <use href="#terminalIconCursor" fill="var(--knockoutColor)" data-js-target="TerminalIcon.cursor" />
                              <use href="#terminalIconGear" fill="var(--blendForeground)" transform-origin="42 55" data-js-target-list="TerminalIcon.gears" />
                              <g clipPath="url(#terminalIconClipPath)">
                                <use href="#terminalIconGear" fill="var(--blendIntersection)" transform-origin="42 55" data-js-target-list="TerminalIcon.gears" />
                              </g>
                            </svg>
                          </div>
                        </div>
                      </div>
                      <h1 className="Copy__title">
                        {" Terminal APIs and SDKs "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      <p>
                        {"Support flexible in-person payments experiences."}
                      </p>
                    </div>
                    <footer className="Copy__footer">
                      <a className="CtaButton variant--Link CtaButton--arrow" href="https://stripe.com/docs/terminal" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get__terminal_apis_and__read_the_docs">
                        {"Read the docs"}
                        <span className="nobr">
                          <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                            <g fillRule="evenodd">
                              <path className="HoverArrow__linePath" d="M0 5h7" />
                              <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                            </g>
                          </svg>
                        </span>
                      </a>
                    </footer>
                  </section>
                  <section className="Copy variant--Detail">
                    <header className="Copy__header">
                      <div className="Copy__icon">
                        <div className="AnimatedIcon NodesIcon">
                          <div className="AnimatedIcon__iconContainer">
                            <svg className="AnimatedIcon__icon" width="96" height="96" preserveAspectRatio="xMinYMin" viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg" data-js-controller="NodesIcon">
                              <defs>
                                <path id="nodesIconSegment" d="M20 41.15l9.7 5.55a1.5 1.5 0 0 1 0 2.6L20 54.85v-13.7z" />
                                <circle id="nodesIconDot" cx="34" cy="48" r="6" />
                                <clipPath id="nodesIconClipPath">
                                  <use className="NodesIcon__dot" href="#nodesIconDot" x="0" y="-24" data-js-target-list="NodesIcon.clipPathDots" />
                                  <use className="NodesIcon__dot" href="#nodesIconDot" x="21" y="-12" data-js-target-list="NodesIcon.clipPathDots" />
                                  <use className="NodesIcon__dot" href="#nodesIconDot" x="21" y="12" data-js-target-list="NodesIcon.clipPathDots" />
                                  <use className="NodesIcon__dot" href="#nodesIconDot" x="0" y="24" data-js-target-list="NodesIcon.clipPathDots" />
                                  <use className="NodesIcon__dot" href="#nodesIconDot" x="-21" y="12" data-js-target-list="NodesIcon.clipPathDots" />
                                  <use className="NodesIcon__dot" href="#nodesIconDot" x="-21" y="-12" data-js-target-list="NodesIcon.clipPathDots" />
                                </clipPath>
                              </defs>
                              <g className="NodesIcon__segments">
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(0deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendBackground)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(60deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendBackground)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(120deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendBackground)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(180deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendBackground)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(240deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendBackground)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(300deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendBackground)" data-js-target-list="NodesIcon.segments" />
                                </g>
                              </g>
                              <g className="NodesIcon__dots">
                                <use className="NodesIcon__dot" href="#nodesIconDot" x="0" y="-24" fill="var(--blendForeground)" data-js-target-list="NodesIcon.dots" />
                                <use className="NodesIcon__dot" href="#nodesIconDot" x="21" y="-12" fill="var(--blendForeground)" data-js-target-list="NodesIcon.dots" />
                                <use className="NodesIcon__dot" href="#nodesIconDot" x="21" y="12" fill="var(--blendForeground)" data-js-target-list="NodesIcon.dots" />
                                <use className="NodesIcon__dot" href="#nodesIconDot" x="0" y="24" fill="var(--blendForeground)" data-js-target-list="NodesIcon.dots" />
                                <use className="NodesIcon__dot" href="#nodesIconDot" x="-21" y="12" fill="var(--blendForeground)" data-js-target-list="NodesIcon.dots" />
                                <use className="NodesIcon__dot" href="#nodesIconDot" x="-21" y="-12" fill="var(--blendForeground)" data-js-target-list="NodesIcon.dots" />
                              </g>
                              <g clipPath="url(#nodesIconClipPath)">
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(0deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendIntersection)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(60deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendIntersection)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(120deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendIntersection)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(180deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendIntersection)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(240deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendIntersection)" data-js-target-list="NodesIcon.segments" />
                                </g>
                                <g className="NodesIcon__segmentRotator" style={{ transform: "rotate(300deg)" }} data-js-target-list="NodesIcon.segmentRotators">
                                  <use className="NodesIcon__segment" href="#nodesIconSegment" fill="var(--blendIntersection)" data-js-target-list="NodesIcon.segments" />
                                </g>
                              </g>
                            </svg>
                          </div>
                        </div>
                      </div>
                      <h1 className="Copy__title">
                        {" POS and commerce integrations "}
                      </h1>
                    </header>
                    <div className="Copy__body">
                      <p>
                        {"Easily connect supported third-party POS, credit card readers, and more."}
                      </p>
                    </div>
                    <footer className="Copy__footer">
                      <a className="CtaButton variant--Link CtaButton--arrow" href="https://docs.stripe.com/connectors#in-person" data-js-controller="AnalyticsButton" data-analytics-category="Buttons" data-analytics-action="Clicked" data-analytics-label="ready_to_get__pos_and_commerce__learn_more">
                        {"Learn more"}
                        <span className="nobr">
                          <svg className="HoverArrow" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
                            <g fillRule="evenodd">
                              <path className="HoverArrow__linePath" d="M0 5h7" />
                              <path className="HoverArrow__tipPath" d="M1 1l4 4-4 4" />
                            </g>
                          </svg>
                        </span>
                      </a>
                    </footer>
                  </section>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
